// Generated by CIRCT firtool-1.128.0
module CacheArbiter(
  input          clock,
                 reset,
                 io_cache_req_0_valid,
  input  [31:0]  io_cache_req_0_bits_addr,
  input          io_cache_req_0_bits_write,
  input  [511:0] io_cache_req_0_bits_wdata,
  input          io_cache_req_1_valid,
  input  [31:0]  io_cache_req_1_bits_addr,
  input          io_mem_req_ready,
  output         io_mem_req_valid,
  output [31:0]  io_mem_req_bits_addr,
  output         io_mem_req_bits_write,
  output [511:0] io_mem_req_bits_wdata,
  input          io_mem_valid,
  output         io_resp_to_cache_0,
                 io_resp_to_cache_1
);

  reg          busy;
  reg          owner;
  reg          mem_req_accepted;
  reg  [31:0]  latched_req_addr;
  reg          latched_req_write;
  reg  [511:0] latched_req_wdata;
  wire         io_mem_req_valid_0 = busy & ~mem_req_accepted;
  wire         _io_resp_to_cache_1_T = io_mem_valid & busy;
  always @(posedge clock) begin
    if (reset) begin
      busy <= 1'h0;
      owner <= 1'h0;
      mem_req_accepted <= 1'h0;
      latched_req_addr <= 32'h0;
      latched_req_write <= 1'h0;
      latched_req_wdata <= 512'h0;
    end
    else begin
      automatic logic [1:0] _GEN = {io_cache_req_1_valid, io_cache_req_0_valid};
      automatic logic       _GEN_0 = ~busy & (|_GEN);
      busy <= ~io_mem_valid & (_GEN_0 | busy);
      if (_GEN_0) begin
        owner <= ~io_cache_req_0_valid;
        latched_req_addr <=
          io_cache_req_0_valid ? io_cache_req_0_bits_addr : io_cache_req_1_bits_addr;
        latched_req_write <= io_cache_req_0_valid & io_cache_req_0_bits_write;
        latched_req_wdata <= io_cache_req_0_valid ? io_cache_req_0_bits_wdata : 512'h0;
      end
      mem_req_accepted <=
        ~io_mem_valid
        & (busy
             ? io_mem_req_ready & io_mem_req_valid_0 | mem_req_accepted
             : ~(|_GEN) & mem_req_accepted);
    end
  end // always @(posedge)
  assign io_mem_req_valid = io_mem_req_valid_0;
  assign io_mem_req_bits_addr = latched_req_addr;
  assign io_mem_req_bits_write = latched_req_write;
  assign io_mem_req_bits_wdata = latched_req_wdata;
  assign io_resp_to_cache_0 = _io_resp_to_cache_1_T & ~owner;
  assign io_resp_to_cache_1 = _io_resp_to_cache_1_T & owner;
endmodule

