// Generated by CIRCT firtool-1.128.0
module Core(
  input         clock,
                reset,
                io_execute,
  output        io_complete,
  output [31:0] io_icache_req_address,
  output        io_icache_start,
  input         io_icache_ready,
                io_icache_valid,
  input  [31:0] io_icache_data,
  output [31:0] io_dcache_req_address,
                io_dcache_req_write_data,
  output [2:0]  io_dcache_req_op,
  output        io_dcache_req_read,
                io_dcache_req_write,
                io_dcache_start,
  input         io_dcache_ready,
  input  [31:0] io_dcache_data,
  output [6:0]  io_dcache_rd,
  output        io_dcache_lane,
                io_dcache_wen,
  input  [6:0]  io_mem_rd,
  input         io_mem_wen
);

  wire         _lsu_io_req_ready;
  wire         _lsu_io_busy;
  wire         _writeback_io_write_enable;
  wire [6:0]   _writeback_io_write_address;
  wire         _writeback_io_write_mask;
  wire [31:0]  _writeback_io_write_val_0;
  wire [127:0] _writeback_io_reg_mem_rum;
  wire         _writeback_io_mem_write_enable;
  wire [6:0]   _writeback_io_mem_write_address;
  wire [31:0]  _writeback_io_mem_write_val_0;
  wire         _execute_io_next_instruction_valid;
  wire [6:0]   _execute_io_next_instruction_bits_rd;
  wire [31:0]  _execute_io_next_instruction_bits_rd_val_0;
  wire         _execute_io_next_instruction_bits_mask;
  wire         _execute_io_next_instruction_bits_rd_wen;
  wire [31:0]  _execute_io_pc_redirect_bits;
  wire         _execute_io_lsu_req_valid;
  wire [31:0]  _execute_io_lsu_req_bits_base_0;
  wire [31:0]  _execute_io_lsu_req_bits_wdata_0;
  wire [31:0]  _execute_io_lsu_req_bits_imm;
  wire         _execute_io_lsu_req_bits_mask;
  wire [6:0]   _execute_io_lsu_req_bits_rd;
  wire [2:0]   _execute_io_lsu_req_bits_func3;
  wire         _execute_io_lsu_req_bits_write;
  wire         _execute_io_memory_stall;
  wire         _execute_io_jump_flush;
  wire         _execute_io_mem_issue;
  wire [6:0]   _execute_io_mem_issue_rd;
  wire         _execute_io_mem_issue_count;
  wire         _execute_io_warp_swap;
  wire         _execute_io_warp_terminate;
  wire         _execute_io_mark;
  wire [31:0]  _execute_io_mark_pc;
  wire [1:0]   _execute_io_mark_warp;
  wire         _execute_io_spawn;
  wire [31:0]  _execute_io_spawn_count;
  wire [31:0]  _execute_io_spawn_pc_in;
  wire         _execute_io_barrier;
  wire [31:0]  _execute_io_barrier_target;
  wire [6:0]   _read_io_register_read_a;
  wire [6:0]   _read_io_register_read_b;
  wire         _read_io_next_instruction_valid;
  wire [31:0]  _read_io_next_instruction_bits_rs1_val_0;
  wire [31:0]  _read_io_next_instruction_bits_rs2_val_0;
  wire [6:0]   _read_io_next_instruction_bits_rd;
  wire [31:0]  _read_io_next_instruction_bits_immediate;
  wire [6:0]   _read_io_next_instruction_bits_opcode;
  wire [2:0]   _read_io_next_instruction_bits_func3;
  wire [6:0]   _read_io_next_instruction_bits_func7;
  wire [31:0]  _read_io_next_instruction_bits_pc;
  wire [1:0]   _read_io_next_instruction_bits_warp;
  wire         _read_io_raw_hazard_stall;
  wire         _decode_io_decoded_valid;
  wire [6:0]   _decode_io_decoded_bits_rs1;
  wire [6:0]   _decode_io_decoded_bits_rs2;
  wire [6:0]   _decode_io_decoded_bits_rd;
  wire         _decode_io_decoded_bits_rd_wen;
  wire [31:0]  _decode_io_decoded_bits_immediate;
  wire [6:0]   _decode_io_decoded_bits_opcode;
  wire [2:0]   _decode_io_decoded_bits_func3;
  wire [6:0]   _decode_io_decoded_bits_func7;
  wire [31:0]  _decode_io_decoded_bits_pc;
  wire [1:0]   _decode_io_decoded_bits_warp;
  wire         _fetch_io_fetch_result_valid;
  wire [31:0]  _fetch_io_fetch_result_bits_pc;
  wire [1:0]   _fetch_io_fetch_result_bits_warp;
  wire [31:0]  _fetch_io_fetch_result_bits_inst;
  wire [1:0]   _warp_scheduler_io_active_warp;
  wire [31:0]  _warp_scheduler_io_warp_ids_out_0;
  wire [31:0]  _warp_scheduler_io_warp_ids_out_1;
  wire [31:0]  _warp_scheduler_io_warp_ids_out_2;
  wire [31:0]  _warp_scheduler_io_warp_ids_out_3;
  wire         _warp_scheduler_io_warp_swap_flush;
  wire         _warp_scheduler_io_allocate_warp;
  wire [1:0]   _warp_scheduler_io_allocate_id;
  wire [31:0]  _warp_scheduler_io_allocate_pc;
  wire [31:0]  _registers_io_out_a_0;
  wire [31:0]  _registers_io_out_b_0;
  wire         fetch_stall =
    _read_io_raw_hazard_stall | _execute_io_memory_stall | ~io_execute;
  wire         read_io_flush =
    _execute_io_jump_flush | _warp_scheduler_io_warp_swap_flush;
  reg          execute_io_flush_REG;
  always @(posedge clock)
    execute_io_flush_REG <= _execute_io_jump_flush;
  Registers registers (
    .clock             (clock),
    .reset             (reset),
    .io_write_enable   (_writeback_io_write_enable),
    .io_write_address  (_writeback_io_write_address),
    .io_write_mask     (_writeback_io_write_mask),
    .io_in_0           (_writeback_io_write_val_0),
    .io_write_enable2  (_writeback_io_mem_write_enable),
    .io_write_address2 (_writeback_io_mem_write_address),
    .io_in2_0          (_writeback_io_mem_write_val_0),
    .io_read_address_a (_read_io_register_read_a),
    .io_read_address_b (_read_io_register_read_b),
    .io_out_a_0        (_registers_io_out_a_0),
    .io_out_b_0        (_registers_io_out_b_0)
  );
  WarpScheduler warp_scheduler (
    .clock              (clock),
    .reset              (reset),
    .io_execute         (io_execute),
    .io_active_warp     (_warp_scheduler_io_active_warp),
    .io_warp_ids_out_0  (_warp_scheduler_io_warp_ids_out_0),
    .io_warp_ids_out_1  (_warp_scheduler_io_warp_ids_out_1),
    .io_warp_ids_out_2  (_warp_scheduler_io_warp_ids_out_2),
    .io_warp_ids_out_3  (_warp_scheduler_io_warp_ids_out_3),
    .io_warp_swap       (_execute_io_warp_swap),
    .io_warp_terminate  (_execute_io_warp_terminate),
    .io_warp_swap_flush (_warp_scheduler_io_warp_swap_flush),
    .io_allocate_warp   (_warp_scheduler_io_allocate_warp),
    .io_allocate_id     (_warp_scheduler_io_allocate_id),
    .io_allocate_pc     (_warp_scheduler_io_allocate_pc),
    .io_complete        (io_complete),
    .io_spawn           (_execute_io_spawn),
    .io_spawn_count     (_execute_io_spawn_count),
    .io_spawn_pc_in     (_execute_io_spawn_pc_in),
    .io_barrier         (_execute_io_barrier),
    .io_barrier_target  (_execute_io_barrier_target),
    .io_lsu_busy        (_lsu_io_busy)
  );
  Fetch fetch (
    .clock                          (clock),
    .reset                          (reset),
    .io_execute                     (io_execute),
    .io_active_warp                 (_warp_scheduler_io_active_warp),
    .io_mark                        (_execute_io_mark),
    .io_mark_pc                     (_execute_io_mark_pc),
    .io_mark_warp                   (_execute_io_mark_warp),
    .io_allocate_warp               (_warp_scheduler_io_allocate_warp),
    .io_allocate_pc                 (_warp_scheduler_io_allocate_pc),
    .io_allocate_id                 (_warp_scheduler_io_allocate_id),
    .io_fetch_request_fetch_op
      (_warp_scheduler_io_warp_swap_flush
         ? 2'h3
         : _execute_io_jump_flush ? 2'h1 : {~fetch_stall, 1'h0}),
    .io_fetch_request_redirect_addr (_execute_io_pc_redirect_bits),
    .io_fetch_result_valid          (_fetch_io_fetch_result_valid),
    .io_fetch_result_bits_pc        (_fetch_io_fetch_result_bits_pc),
    .io_fetch_result_bits_warp      (_fetch_io_fetch_result_bits_warp),
    .io_fetch_result_bits_inst      (_fetch_io_fetch_result_bits_inst),
    .io_icache_req_address          (io_icache_req_address),
    .io_icache_start                (io_icache_start),
    .io_icache_ready                (io_icache_ready),
    .io_icache_valid                (io_icache_valid),
    .io_icache_data                 (io_icache_data)
  );
  Decode decode (
    .clock                     (clock),
    .reset                     (reset),
    .io_fetch_result_valid     (_fetch_io_fetch_result_valid),
    .io_fetch_result_bits_pc   (_fetch_io_fetch_result_bits_pc),
    .io_fetch_result_bits_warp (_fetch_io_fetch_result_bits_warp),
    .io_fetch_result_bits_inst (_fetch_io_fetch_result_bits_inst),
    .io_decoded_valid          (_decode_io_decoded_valid),
    .io_decoded_bits_rs1       (_decode_io_decoded_bits_rs1),
    .io_decoded_bits_rs2       (_decode_io_decoded_bits_rs2),
    .io_decoded_bits_rd        (_decode_io_decoded_bits_rd),
    .io_decoded_bits_rd_wen    (_decode_io_decoded_bits_rd_wen),
    .io_decoded_bits_immediate (_decode_io_decoded_bits_immediate),
    .io_decoded_bits_opcode    (_decode_io_decoded_bits_opcode),
    .io_decoded_bits_func3     (_decode_io_decoded_bits_func3),
    .io_decoded_bits_func7     (_decode_io_decoded_bits_func7),
    .io_decoded_bits_pc        (_decode_io_decoded_bits_pc),
    .io_decoded_bits_warp      (_decode_io_decoded_bits_warp),
    .io_flush                  (read_io_flush),
    .io_stall                  (fetch_stall)
  );
  Read read (
    .clock                              (clock),
    .reset                              (reset),
    .io_instruction_valid               (_decode_io_decoded_valid),
    .io_instruction_bits_rs1            (_decode_io_decoded_bits_rs1),
    .io_instruction_bits_rs2            (_decode_io_decoded_bits_rs2),
    .io_instruction_bits_rd             (_decode_io_decoded_bits_rd),
    .io_instruction_bits_rd_wen         (_decode_io_decoded_bits_rd_wen),
    .io_instruction_bits_immediate      (_decode_io_decoded_bits_immediate),
    .io_instruction_bits_opcode         (_decode_io_decoded_bits_opcode),
    .io_instruction_bits_func3          (_decode_io_decoded_bits_func3),
    .io_instruction_bits_func7          (_decode_io_decoded_bits_func7),
    .io_instruction_bits_pc             (_decode_io_decoded_bits_pc),
    .io_instruction_bits_warp           (_decode_io_decoded_bits_warp),
    .io_register_read_a                 (_read_io_register_read_a),
    .io_register_read_b                 (_read_io_register_read_b),
    .io_register_value_a_0              (_registers_io_out_a_0),
    .io_register_value_b_0              (_registers_io_out_b_0),
    .io_next_instruction_valid          (_read_io_next_instruction_valid),
    .io_next_instruction_bits_rs1_val_0 (_read_io_next_instruction_bits_rs1_val_0),
    .io_next_instruction_bits_rs2_val_0 (_read_io_next_instruction_bits_rs2_val_0),
    .io_next_instruction_bits_rd        (_read_io_next_instruction_bits_rd),
    .io_next_instruction_bits_immediate (_read_io_next_instruction_bits_immediate),
    .io_next_instruction_bits_opcode    (_read_io_next_instruction_bits_opcode),
    .io_next_instruction_bits_func3     (_read_io_next_instruction_bits_func3),
    .io_next_instruction_bits_func7     (_read_io_next_instruction_bits_func7),
    .io_next_instruction_bits_pc        (_read_io_next_instruction_bits_pc),
    .io_next_instruction_bits_warp      (_read_io_next_instruction_bits_warp),
    .io_flush                           (read_io_flush),
    .io_stall                           (_execute_io_memory_stall),
    .io_rum
      ({127'h0, _execute_io_next_instruction_valid}
       << _execute_io_next_instruction_bits_rd | {127'h0, _read_io_next_instruction_valid}
       << _read_io_next_instruction_bits_rd | {127'h0, _writeback_io_write_enable}
       << _writeback_io_write_address | _writeback_io_reg_mem_rum),
    .io_raw_hazard_stall                (_read_io_raw_hazard_stall)
  );
  Execute execute (
    .clock                             (clock),
    .reset                             (reset),
    .io_instruction_valid              (_read_io_next_instruction_valid),
    .io_instruction_bits_rs1_val_0     (_read_io_next_instruction_bits_rs1_val_0),
    .io_instruction_bits_rs2_val_0     (_read_io_next_instruction_bits_rs2_val_0),
    .io_instruction_bits_rd            (_read_io_next_instruction_bits_rd),
    .io_instruction_bits_immediate     (_read_io_next_instruction_bits_immediate),
    .io_instruction_bits_opcode        (_read_io_next_instruction_bits_opcode),
    .io_instruction_bits_func3         (_read_io_next_instruction_bits_func3),
    .io_instruction_bits_func7         (_read_io_next_instruction_bits_func7),
    .io_instruction_bits_pc            (_read_io_next_instruction_bits_pc),
    .io_instruction_bits_warp          (_read_io_next_instruction_bits_warp),
    .io_next_instruction_valid         (_execute_io_next_instruction_valid),
    .io_next_instruction_bits_rd       (_execute_io_next_instruction_bits_rd),
    .io_next_instruction_bits_rd_val_0 (_execute_io_next_instruction_bits_rd_val_0),
    .io_next_instruction_bits_mask     (_execute_io_next_instruction_bits_mask),
    .io_next_instruction_bits_rd_wen   (_execute_io_next_instruction_bits_rd_wen),
    .io_flush                          (execute_io_flush_REG),
    .io_pc_redirect_bits               (_execute_io_pc_redirect_bits),
    .io_lsu_req_ready                  (_lsu_io_req_ready),
    .io_lsu_req_valid                  (_execute_io_lsu_req_valid),
    .io_lsu_req_bits_base_0            (_execute_io_lsu_req_bits_base_0),
    .io_lsu_req_bits_wdata_0           (_execute_io_lsu_req_bits_wdata_0),
    .io_lsu_req_bits_imm               (_execute_io_lsu_req_bits_imm),
    .io_lsu_req_bits_mask              (_execute_io_lsu_req_bits_mask),
    .io_lsu_req_bits_rd                (_execute_io_lsu_req_bits_rd),
    .io_lsu_req_bits_func3             (_execute_io_lsu_req_bits_func3),
    .io_lsu_req_bits_write             (_execute_io_lsu_req_bits_write),
    .io_memory_stall                   (_execute_io_memory_stall),
    .io_jump_flush                     (_execute_io_jump_flush),
    .io_mem_issue                      (_execute_io_mem_issue),
    .io_mem_issue_rd                   (_execute_io_mem_issue_rd),
    .io_mem_issue_count                (_execute_io_mem_issue_count),
    .io_warp_swap                      (_execute_io_warp_swap),
    .io_warp_terminate                 (_execute_io_warp_terminate),
    .io_mark                           (_execute_io_mark),
    .io_mark_pc                        (_execute_io_mark_pc),
    .io_mark_warp                      (_execute_io_mark_warp),
    .io_warp_ids_0                     (_warp_scheduler_io_warp_ids_out_0),
    .io_warp_ids_1                     (_warp_scheduler_io_warp_ids_out_1),
    .io_warp_ids_2                     (_warp_scheduler_io_warp_ids_out_2),
    .io_warp_ids_3                     (_warp_scheduler_io_warp_ids_out_3),
    .io_spawn                          (_execute_io_spawn),
    .io_spawn_count                    (_execute_io_spawn_count),
    .io_spawn_pc_in                    (_execute_io_spawn_pc_in),
    .io_allocate_warp                  (_warp_scheduler_io_allocate_warp),
    .io_allocate_id                    (_warp_scheduler_io_allocate_id),
    .io_barrier                        (_execute_io_barrier),
    .io_barrier_target                 (_execute_io_barrier_target)
  );
  Writeback writeback (
    .clock                        (clock),
    .reset                        (reset),
    .io_instruction_valid         (_execute_io_next_instruction_valid),
    .io_instruction_bits_rd       (_execute_io_next_instruction_bits_rd),
    .io_instruction_bits_rd_val_0 (_execute_io_next_instruction_bits_rd_val_0),
    .io_instruction_bits_mask     (_execute_io_next_instruction_bits_mask),
    .io_instruction_bits_rd_wen   (_execute_io_next_instruction_bits_rd_wen),
    .io_write_enable              (_writeback_io_write_enable),
    .io_write_address             (_writeback_io_write_address),
    .io_write_mask                (_writeback_io_write_mask),
    .io_write_val_0               (_writeback_io_write_val_0),
    .io_mem_write_data_0          (io_dcache_data),
    .io_mem_rd                    (io_mem_rd),
    .io_mem_wen                   (io_mem_wen),
    .io_reg_mem_rum               (_writeback_io_reg_mem_rum),
    .io_mem_write_enable          (_writeback_io_mem_write_enable),
    .io_mem_write_address         (_writeback_io_mem_write_address),
    .io_mem_write_val_0           (_writeback_io_mem_write_val_0),
    .io_mem_issue                 (_execute_io_mem_issue),
    .io_mem_issue_rd              (_execute_io_mem_issue_rd),
    .io_mem_issue_count           ({1'h0, _execute_io_mem_issue_count})
  );
  LSU lsu (
    .clock                    (clock),
    .reset                    (reset),
    .io_req_ready             (_lsu_io_req_ready),
    .io_req_valid             (_execute_io_lsu_req_valid),
    .io_req_bits_base_0       (_execute_io_lsu_req_bits_base_0),
    .io_req_bits_wdata_0      (_execute_io_lsu_req_bits_wdata_0),
    .io_req_bits_imm          (_execute_io_lsu_req_bits_imm),
    .io_req_bits_mask         (_execute_io_lsu_req_bits_mask),
    .io_req_bits_rd           (_execute_io_lsu_req_bits_rd),
    .io_req_bits_func3        (_execute_io_lsu_req_bits_func3),
    .io_req_bits_write        (_execute_io_lsu_req_bits_write),
    .io_dcache_req_address    (io_dcache_req_address),
    .io_dcache_req_write_data (io_dcache_req_write_data),
    .io_dcache_req_op         (io_dcache_req_op),
    .io_dcache_req_read       (io_dcache_req_read),
    .io_dcache_req_write      (io_dcache_req_write),
    .io_dcache_start          (io_dcache_start),
    .io_dcache_ready          (io_dcache_ready),
    .io_dcache_rd             (io_dcache_rd),
    .io_dcache_lane           (io_dcache_lane),
    .io_dcache_wen            (io_dcache_wen),
    .io_busy                  (_lsu_io_busy)
  );
endmodule

