// Generated by CIRCT firtool-1.128.0
module Decode(
  input         clock,
                reset,
                io_fetch_result_valid,
  input  [31:0] io_fetch_result_bits_pc,
  input  [1:0]  io_fetch_result_bits_warp,
  input  [31:0] io_fetch_result_bits_inst,
  output        io_decoded_valid,
  output [6:0]  io_decoded_bits_rs1,
                io_decoded_bits_rs2,
                io_decoded_bits_rd,
  output        io_decoded_bits_rd_wen,
  output [31:0] io_decoded_bits_immediate,
  output [6:0]  io_decoded_bits_opcode,
  output [2:0]  io_decoded_bits_func3,
  output [6:0]  io_decoded_bits_func7,
  output [31:0] io_decoded_bits_pc,
  output [1:0]  io_decoded_bits_warp,
  input         io_flush,
                io_stall
);

  wire [4:0]  _decoder_io_rs1;
  wire [4:0]  _decoder_io_rs2;
  wire [4:0]  _decoder_io_rd;
  wire        _decoder_io_wen;
  wire [31:0] _decoder_io_immediate;
  wire [6:0]  _decoder_io_opcode;
  wire [2:0]  _decoder_io_func3;
  wire [6:0]  _decoder_io_func7;
  reg  [6:0]  rs1;
  reg  [6:0]  rs2;
  reg  [6:0]  rd;
  reg  [31:0] immediate;
  reg  [6:0]  opcode;
  reg  [2:0]  func3;
  reg  [6:0]  func7;
  reg  [31:0] pc;
  reg         valid;
  reg         wen;
  reg  [1:0]  warp;
  always @(posedge clock) begin
    if (reset) begin
      rs1 <= 7'h0;
      rs2 <= 7'h0;
      rd <= 7'h0;
      immediate <= 32'h0;
      opcode <= 7'h0;
      func3 <= 3'h0;
      func7 <= 7'h0;
      pc <= 32'h0;
      valid <= 1'h0;
      wen <= 1'h0;
      warp <= 2'h0;
    end
    else begin
      automatic logic _GEN = io_flush | io_stall;
      if (_GEN) begin
      end
      else begin
        automatic logic [6:0] _GEN_0 = {io_fetch_result_bits_warp, 5'h0};
        rs1 <= {2'h0, _decoder_io_rs1} + _GEN_0;
        rs2 <= {2'h0, _decoder_io_rs2} + _GEN_0;
        rd <= {2'h0, _decoder_io_rd} + _GEN_0;
        immediate <= _decoder_io_immediate;
        opcode <= _decoder_io_opcode;
        func3 <= _decoder_io_func3;
        func7 <= _decoder_io_func7;
        pc <= io_fetch_result_bits_pc;
      end
      valid <= ~io_flush & (io_stall ? valid : io_fetch_result_valid);
      if (_GEN) begin
      end
      else begin
        wen <= _decoder_io_wen;
        warp <= io_fetch_result_bits_warp;
      end
    end
  end // always @(posedge)
  Decoder decoder (
    .io_instruction (io_fetch_result_bits_inst),
    .io_rs1         (_decoder_io_rs1),
    .io_rs2         (_decoder_io_rs2),
    .io_rd          (_decoder_io_rd),
    .io_wen         (_decoder_io_wen),
    .io_immediate   (_decoder_io_immediate),
    .io_opcode      (_decoder_io_opcode),
    .io_func3       (_decoder_io_func3),
    .io_func7       (_decoder_io_func7)
  );
  assign io_decoded_valid = valid;
  assign io_decoded_bits_rs1 = rs1;
  assign io_decoded_bits_rs2 = rs2;
  assign io_decoded_bits_rd = rd;
  assign io_decoded_bits_rd_wen = wen;
  assign io_decoded_bits_immediate = immediate;
  assign io_decoded_bits_opcode = opcode;
  assign io_decoded_bits_func3 = func3;
  assign io_decoded_bits_func7 = func7;
  assign io_decoded_bits_pc = pc;
  assign io_decoded_bits_warp = warp;
endmodule

