// Generated by CIRCT firtool-1.128.0
module Decoder(
  input  [31:0] io_instruction,
  output [4:0]  io_rs1,
                io_rs2,
                io_rd,
  output        io_wen,
  output [31:0] io_immediate,
  output [6:0]  io_opcode,
  output [2:0]  io_func3,
  output [6:0]  io_func7
);

  wire [2:0]       format =
    io_instruction[6:0] == 7'h37 | io_instruction[6:0] == 7'h17
      ? 3'h4
      : io_instruction[6:0] == 7'h13
          ? 3'h1
          : io_instruction[6:0] == 7'h33
              ? 3'h0
              : io_instruction[6:0] == 7'hF
                  ? 3'h1
                  : io_instruction[6:0] == 7'h73
                      ? 3'h2
                      : io_instruction[6:0] == 7'h3
                          ? 3'h1
                          : io_instruction[6:0] == 7'h23
                              ? 3'h2
                              : io_instruction[6:0] == 7'h6F
                                  ? 3'h5
                                  : io_instruction[6:0] == 7'h67
                                      ? 3'h1
                                      : io_instruction[6:0] == 7'h63 ? 3'h3 : 3'h0;
  wire [7:0][31:0] _GEN =
    {{32'h0},
     {32'h0},
     {{{12{io_instruction[31]}},
       io_instruction[19:12],
       io_instruction[20],
       io_instruction[30:21],
       1'h0}},
     {{io_instruction[31:12], 12'h0}},
     {{{20{io_instruction[31]}},
       io_instruction[7],
       io_instruction[30:25],
       io_instruction[11:8],
       1'h0}},
     {{{20{io_instruction[31]}}, io_instruction[31:25], io_instruction[11:7]}},
     {{{21{io_instruction[31]}}, io_instruction[30:20]}},
     {32'h0}};
  assign io_rs1 = io_instruction[19:15];
  assign io_rs2 = io_instruction[24:20];
  assign io_rd = io_instruction[11:7];
  assign io_wen = format == 3'h1 | format != 3'h2 & format != 3'h3;
  assign io_immediate = _GEN[format];
  assign io_opcode = io_instruction[6:0];
  assign io_func3 = io_instruction[14:12];
  assign io_func7 = io_instruction[31:25];
endmodule

