// Generated by CIRCT firtool-1.128.0
module Execute(
  input         clock,
                reset,
                io_instruction_valid,
  input  [31:0] io_instruction_bits_rs1_val_0,
                io_instruction_bits_rs2_val_0,
  input  [6:0]  io_instruction_bits_rd,
  input  [31:0] io_instruction_bits_immediate,
  input  [6:0]  io_instruction_bits_opcode,
  input  [2:0]  io_instruction_bits_func3,
  input  [6:0]  io_instruction_bits_func7,
  input  [31:0] io_instruction_bits_pc,
  input  [1:0]  io_instruction_bits_warp,
  output        io_next_instruction_valid,
  output [6:0]  io_next_instruction_bits_rd,
  output [31:0] io_next_instruction_bits_rd_val_0,
  output        io_next_instruction_bits_mask,
                io_next_instruction_bits_rd_wen,
  input         io_flush,
  output [31:0] io_pc_redirect_bits,
  input         io_lsu_req_ready,
  output        io_lsu_req_valid,
  output [31:0] io_lsu_req_bits_base_0,
                io_lsu_req_bits_wdata_0,
                io_lsu_req_bits_imm,
  output        io_lsu_req_bits_mask,
  output [6:0]  io_lsu_req_bits_rd,
  output [2:0]  io_lsu_req_bits_func3,
  output        io_lsu_req_bits_write,
                io_memory_stall,
                io_jump_flush,
                io_mem_issue,
  output [6:0]  io_mem_issue_rd,
  output        io_mem_issue_count,
                io_warp_swap,
                io_warp_terminate,
                io_mark,
  output [31:0] io_mark_pc,
  output [1:0]  io_mark_warp,
  input  [31:0] io_warp_ids_0,
                io_warp_ids_1,
                io_warp_ids_2,
                io_warp_ids_3,
  output        io_spawn,
  output [31:0] io_spawn_count,
                io_spawn_pc_in,
  input         io_allocate_warp,
  input  [1:0]  io_allocate_id,
  output        io_barrier,
  output [31:0] io_barrier_target
);

  wire [31:0] _malus_0_io_output;
  wire        _malus_0_io_ready;
  wire        _malus_0_io_valid;
  wire [31:0] _alus_0_io_output;
  reg  [6:0]  bundle_rd;
  reg  [31:0] bundle_rd_val_0;
  reg         bundle_mask;
  reg         bundle_rd_wen;
  reg  [6:0]  bundle_opcode;
  reg         valid;
  reg         lmask_0;
  reg         lmask_1;
  reg         lmask_2;
  reg         lmask_3;
  wire [3:0]  _GEN = {{lmask_3}, {lmask_2}, {lmask_1}, {lmask_0}};
  wire        alus_0_io_isR = io_instruction_bits_opcode == 7'h33;
  wire        _GEN_0 = io_flush | ~io_instruction_valid;
  wire [31:0] _pc_plus_4_T = io_instruction_bits_pc + 32'h4;
  wire [31:0] _pc_plus_imm_T = io_instruction_bits_pc + io_instruction_bits_immediate;
  wire        _alu_b_T = io_instruction_bits_opcode == 7'h13;
  wire        _GEN_1 = _alu_b_T | alus_0_io_isR;
  wire        isM = alus_0_io_isR & io_instruction_bits_func7 == 7'h1;
  wire        _GEN_2 = io_instruction_valid & _GEN_1;
  wire [31:0] alus_0_io_b =
    io_flush | ~_GEN_2
      ? 32'h0
      : _alu_b_T
          ? io_instruction_bits_immediate
          : alus_0_io_isR & io_instruction_bits_func7 == 7'h20
            & io_instruction_bits_func3 == 3'h0
              ? 32'h0 - io_instruction_bits_rs2_val_0
              : io_instruction_bits_rs2_val_0;
  wire        _GEN_3 = io_instruction_bits_opcode == 7'hB;
  wire        _GEN_4 = io_instruction_bits_func7 == 7'h0;
  wire        _GEN_5 = io_instruction_bits_func7 == 7'h1;
  wire        _GEN_6 = io_instruction_bits_func7 == 7'h2;
  wire        _GEN_7 = _GEN_4 | _GEN_5;
  wire        _GEN_8 = io_instruction_bits_func7 == 7'h4;
  wire        _GEN_9 = io_instruction_bits_func7 == 7'h5;
  wire        _GEN_10 = io_instruction_bits_func7 == 7'h6;
  wire        _GEN_11 = _GEN_4 | _GEN_5 | _GEN_6 | _GEN_8 | _GEN_9;
  wire        _GEN_12 =
    io_flush | ~io_instruction_valid | _GEN_1 | ~_GEN_3 | _GEN_11 | ~_GEN_10;
  wire        _GEN_13 = io_instruction_bits_func7 == 7'h7;
  wire        _GEN_14 = _GEN_8 | _GEN_9 | _GEN_10;
  wire        _GEN_15 = _GEN_4 | _GEN_5 | _GEN_6 | _GEN_14;
  wire        _GEN_16 = io_instruction_bits_opcode == 7'h63;
  wire        take_branch =
    (io_instruction_bits_func3[2]
       ? (io_instruction_bits_func3[1]
            ? io_instruction_bits_rs1_val_0 < io_instruction_bits_rs2_val_0
            : $signed(io_instruction_bits_rs1_val_0) < $signed(io_instruction_bits_rs2_val_0))
       : io_instruction_bits_rs1_val_0 == io_instruction_bits_rs2_val_0)
    ^ io_instruction_bits_func3[0];
  wire [31:0] target = take_branch ? _pc_plus_imm_T : _pc_plus_4_T;
  wire        _GEN_17 = io_instruction_bits_opcode == 7'h37;
  wire        _GEN_18 = io_instruction_bits_opcode == 7'h17;
  wire        _GEN_19 = io_instruction_bits_opcode == 7'h6F;
  wire        _GEN_20 = io_instruction_bits_opcode == 7'h67;
  wire [31:0] target_1 =
    io_instruction_bits_rs1_val_0 + io_instruction_bits_immediate & 32'hFFFFFFFE;
  wire        _GEN_21 = _GEN_19 | _GEN_20;
  wire        _GEN_22 = _GEN_17 | _GEN_18;
  wire        _GEN_23 = _GEN_1 | _GEN_3;
  wire        _GEN_24 = io_instruction_bits_opcode == 7'h3;
  wire        _GEN_25 = _GEN_16 | _GEN_17 | _GEN_18 | _GEN_21;
  wire        _GEN_26 = _GEN_3 | _GEN_25;
  wire        _GEN_27 = _GEN_1 | _GEN_26;
  wire        _GEN_28 = io_instruction_bits_opcode == 7'h23;
  wire        _GEN_29 = _GEN_24 ? ~io_lsu_req_ready : _GEN_28 & ~io_lsu_req_ready;
  wire        io_mark_0 =
    ~io_flush & io_instruction_valid
    & (_GEN_27 | ~(_GEN_24 | _GEN_28) | io_lsu_req_ready);
  always @(posedge clock) begin
    if (reset) begin
      bundle_rd <= 7'h0;
      bundle_rd_val_0 <= 32'h0;
      bundle_mask <= 1'h0;
      bundle_rd_wen <= 1'h0;
      bundle_opcode <= 7'h0;
      valid <= 1'h0;
      lmask_0 <= 1'h1;
      lmask_1 <= 1'h1;
      lmask_2 <= 1'h1;
      lmask_3 <= 1'h1;
    end
    else begin
      automatic logic _GEN_30 = _GEN_4 | _GEN_5 | _GEN_6 | _GEN_8;
      if (_GEN_0) begin
      end
      else begin
        automatic logic [3:0][31:0] _GEN_31 =
          {{io_warp_ids_3}, {io_warp_ids_2}, {io_warp_ids_1}, {io_warp_ids_0}};
        bundle_rd <= io_instruction_bits_rd;
        bundle_rd_val_0 <=
          _GEN_1
            ? (isM ? _malus_0_io_output : _alus_0_io_output)
            : _GEN_3
                ? (_GEN_4
                     ? 32'h0
                     : _GEN_5
                         ? _GEN_31[io_instruction_bits_warp]
                         : _GEN_6
                             ? 32'h0
                             : _GEN_8
                                 ? {31'h0,
                                    (|io_instruction_bits_rs1_val_0)
                                      & _GEN[io_instruction_bits_warp]}
                                 : _GEN_9
                                     ? {31'h0, _GEN[io_instruction_bits_warp]}
                                     : 32'h0)
                : _GEN_16
                    ? 32'h0
                    : _GEN_17
                        ? io_instruction_bits_immediate
                        : _GEN_18 ? _pc_plus_imm_T : _GEN_21 ? _pc_plus_4_T : 32'h0;
        bundle_mask <= ~_GEN_1 & _GEN_3 | _GEN[io_instruction_bits_warp];
        bundle_rd_wen <=
          _GEN_1
          | (_GEN_3
               ? _GEN_7 | ~_GEN_6 & (_GEN_8 | _GEN_9)
               : ~_GEN_16 & (_GEN_17 | _GEN_18 | _GEN_19 | _GEN_20));
        bundle_opcode <= io_instruction_bits_opcode;
      end
      valid <= io_mark_0;
      lmask_0 <=
        io_allocate_warp & io_allocate_id == 2'h0
        | (io_flush | ~io_instruction_valid | _GEN_1 | ~_GEN_3 | _GEN_30
           | ~(_GEN_9 & io_instruction_bits_warp == 2'h0)
             ? lmask_0
             : io_instruction_bits_rs1_val_0[0]);
      lmask_1 <=
        io_allocate_warp & io_allocate_id == 2'h1
        | (io_flush | ~io_instruction_valid | _GEN_1 | ~_GEN_3 | _GEN_30
           | ~(_GEN_9 & io_instruction_bits_warp == 2'h1)
             ? lmask_1
             : io_instruction_bits_rs1_val_0[0]);
      lmask_2 <=
        io_allocate_warp & io_allocate_id == 2'h2
        | (io_flush | ~io_instruction_valid | _GEN_1 | ~_GEN_3 | _GEN_30
           | ~(_GEN_9 & io_instruction_bits_warp == 2'h2)
             ? lmask_2
             : io_instruction_bits_rs1_val_0[0]);
      lmask_3 <=
        io_allocate_warp & (&io_allocate_id)
        | (io_flush | ~io_instruction_valid | _GEN_1 | ~_GEN_3 | _GEN_30
           | ~(_GEN_9 & (&io_instruction_bits_warp))
             ? lmask_3
             : io_instruction_bits_rs1_val_0[0]);
    end
  end // always @(posedge)
  ALU alus_0 (
    .io_func7  (io_instruction_bits_func7),
    .io_func3  (io_instruction_bits_func3),
    .io_isR    (alus_0_io_isR),
    .io_a      (io_instruction_bits_rs1_val_0),
    .io_b      (alus_0_io_b),
    .io_output (_alus_0_io_output)
  );
  MALU malus_0 (
    .clock     (clock),
    .reset     (reset),
    .io_func3  (io_instruction_bits_func3),
    .io_a      (io_instruction_bits_rs1_val_0),
    .io_b      (alus_0_io_b),
    .io_output (_malus_0_io_output),
    .io_ready  (_malus_0_io_ready),
    .io_valid  (_malus_0_io_valid),
    .io_start  (~io_flush & _GEN_2 & isM & _malus_0_io_ready)
  );
  assign io_next_instruction_valid =
    valid
    & (~io_flush | bundle_opcode == 7'h6F | bundle_opcode == 7'h67
       | bundle_opcode == 7'h63);
  assign io_next_instruction_bits_rd = bundle_rd;
  assign io_next_instruction_bits_rd_val_0 = bundle_rd_val_0;
  assign io_next_instruction_bits_mask = bundle_mask;
  assign io_next_instruction_bits_rd_wen = bundle_rd_wen;
  assign io_pc_redirect_bits =
    io_flush | ~io_instruction_valid | _GEN_23
      ? 32'h0
      : _GEN_16
          ? target
          : _GEN_22 ? 32'h0 : _GEN_19 ? _pc_plus_imm_T : _GEN_20 ? target_1 : 32'h0;
  assign io_lsu_req_valid =
    ~io_flush & io_instruction_valid & ~_GEN_27 & (_GEN_24 | _GEN_28);
  assign io_lsu_req_bits_base_0 = io_instruction_bits_rs1_val_0;
  assign io_lsu_req_bits_wdata_0 = io_instruction_bits_rs2_val_0;
  assign io_lsu_req_bits_imm = io_instruction_bits_immediate;
  assign io_lsu_req_bits_mask = _GEN[io_instruction_bits_warp];
  assign io_lsu_req_bits_rd = io_instruction_bits_rd;
  assign io_lsu_req_bits_func3 = io_instruction_bits_func3;
  assign io_lsu_req_bits_write =
    ~io_flush & io_instruction_valid
    & ~(_GEN_1 | _GEN_3 | _GEN_16 | _GEN_17 | _GEN_18 | _GEN_19 | _GEN_20 | _GEN_24)
    & _GEN_28;
  assign io_memory_stall =
    ~io_flush & io_instruction_valid
    & (_GEN_1 ? isM & ~_malus_0_io_valid : ~_GEN_26 & _GEN_29);
  assign io_jump_flush =
    ~io_flush & io_instruction_valid & ~_GEN_23
    & (_GEN_16 ? take_branch : ~_GEN_22 & (_GEN_19 | _GEN_20));
  assign io_mem_issue =
    ~io_flush & io_instruction_valid & ~_GEN_27 & _GEN_24 & io_lsu_req_ready;
  assign io_mem_issue_rd =
    io_flush | ~io_instruction_valid | _GEN_27 | ~_GEN_24 ? 7'h0 : io_instruction_bits_rd;
  assign io_mem_issue_count =
    ~io_flush & io_instruction_valid & ~_GEN_27 & _GEN_24
    & _GEN[io_instruction_bits_warp];
  assign io_warp_swap =
    ~io_flush & io_instruction_valid & ~_GEN_1
    & (_GEN_3 ? ~_GEN_7 & (_GEN_6 | ~_GEN_14 & _GEN_13) : ~_GEN_25 & _GEN_29);
  assign io_warp_terminate =
    ~io_flush & io_instruction_valid & ~_GEN_1 & _GEN_3 & ~_GEN_7 & _GEN_6;
  assign io_mark = io_mark_0;
  assign io_mark_pc =
    _GEN_0
      ? 32'h0
      : _GEN_23
          ? _pc_plus_4_T
          : _GEN_16
              ? target
              : _GEN_22
                  ? _pc_plus_4_T
                  : _GEN_19 ? _pc_plus_imm_T : _GEN_20 ? target_1 : _pc_plus_4_T;
  assign io_mark_warp = _GEN_0 ? 2'h0 : io_instruction_bits_warp;
  assign io_spawn =
    ~io_flush & io_instruction_valid & ~_GEN_1 & _GEN_3 & ~_GEN_11 & _GEN_10;
  assign io_spawn_count = _GEN_12 ? 32'h0 : io_instruction_bits_rs1_val_0;
  assign io_spawn_pc_in = _GEN_12 ? 32'h0 : io_instruction_bits_rs2_val_0;
  assign io_barrier =
    ~io_flush & io_instruction_valid & ~_GEN_1 & _GEN_3 & ~_GEN_15 & _GEN_13;
  assign io_barrier_target =
    io_flush | ~io_instruction_valid | _GEN_1 | ~_GEN_3 | _GEN_15 | ~_GEN_13
      ? 32'h0
      : io_instruction_bits_rs1_val_0;
endmodule

