// Generated by CIRCT firtool-1.128.0
module MALU(
  input         clock,
                reset,
  input  [2:0]  io_func3,
  input  [31:0] io_a,
                io_b,
  output [31:0] io_output,
  output        io_ready,
                io_valid,
  input         io_start
);

  wire [31:0] _div_io_output;
  wire        _div_io_valid;
  wire        _GEN = io_func3 == 3'h0;
  wire        _GEN_0 = io_func3 == 3'h1;
  wire [63:0] _m_alu_T_3 = {{32{io_a[31]}}, io_a} * {{32{io_b[31]}}, io_b};
  wire        _GEN_1 = io_func3 == 3'h2;
  wire [63:0] _GEN_2 = {32'h0, io_b};
  wire [63:0] _m_alu_T_6 = {{32{io_a[31]}}, io_a} * _GEN_2;
  wire        _GEN_3 = io_func3 == 3'h3;
  wire [63:0] _m_alu_T_9 = {32'h0, io_a} * _GEN_2;
  Div div (
    .clock     (clock),
    .reset     (reset),
    .io_func3  (io_func3),
    .io_a      (io_a),
    .io_b      (io_b),
    .io_output (_div_io_output),
    .io_ready  (io_ready),
    .io_valid  (_div_io_valid),
    .io_start
      (io_start & ~(_GEN | _GEN_0 | _GEN_1 | _GEN_3)
       & (io_func3 == 3'h4 | io_func3 == 3'h5 | io_func3 == 3'h6 | (&io_func3)))
  );
  assign io_output =
    io_func3[2]
      ? _div_io_output
      : io_start
          ? (_GEN
               ? io_a * io_b
               : _GEN_0
                   ? _m_alu_T_3[63:32]
                   : _GEN_1 ? _m_alu_T_6[63:32] : _GEN_3 ? _m_alu_T_9[63:32] : 32'h0)
          : 32'h0;
  assign io_valid =
    io_func3 != 3'h4 & io_func3 != 3'h5 & ~(&io_func3) & io_func3 != 3'h6 | _div_io_valid;
endmodule

