// Generated by CIRCT firtool-1.128.0
module MemoryInterface(
  input          clock,
                 reset,
  input  [31:0]  io_icache_req_address,
  input          io_icache_start,
  output         io_icache_ready,
                 io_icache_valid,
  output [31:0]  io_icache_data,
  input  [31:0]  io_dcache_req_address,
                 io_dcache_req_write_data,
  input  [2:0]   io_dcache_req_op,
  input          io_dcache_req_read,
                 io_dcache_req_write,
                 io_dcache_start,
  output         io_dcache_ready,
                 io_dcache_valid,
  output [31:0]  io_dcache_data,
  input  [6:0]   io_dcache_rd,
  input          io_dcache_lane,
                 io_dcache_wen,
  output [6:0]   io_dcache_rd_out,
  output         io_dcache_wen_out,
  input          io_mem_req_ready,
  output         io_mem_req_valid,
  output [31:0]  io_mem_req_bits_addr,
  output         io_mem_req_bits_write,
  output [511:0] io_mem_req_bits_wdata,
  input  [511:0] io_mem_resp,
  input          io_mem_valid
);

  wire         _l2_cache_io_req_ready;
  wire [511:0] _l2_cache_io_mem_resp_in;
  wire         _l2_cache_io_mem_valid_in;
  wire [31:0]  _dcache_queue_io_dcache_req_address;
  wire [31:0]  _dcache_queue_io_dcache_req_write_data;
  wire [2:0]   _dcache_queue_io_dcache_req_op;
  wire         _dcache_queue_io_dcache_req_write;
  wire         _dcache_queue_io_dcache_start;
  wire         _arbiter_io_mem_req_valid;
  wire [31:0]  _arbiter_io_mem_req_bits_addr;
  wire         _arbiter_io_mem_req_bits_write;
  wire [511:0] _arbiter_io_mem_req_bits_wdata;
  wire         _arbiter_io_resp_to_cache_0;
  wire         _arbiter_io_resp_to_cache_1;
  wire         _dcache_io_ready;
  wire         _dcache_io_done;
  wire         _dcache_io_miss;
  wire [31:0]  _dcache_io_data;
  wire         _dcache_io_wb;
  wire [511:0] _dcache_io_wb_data;
  wire [31:0]  _dcache_io_wb_addr;
  wire [31:0]  _dcache_io_line_addr;
  wire         _icache_io_miss;
  wire [31:0]  _icache_io_line_addr;
  ICache icache (
    .clock          (clock),
    .reset          (reset),
    .io_req_address (io_icache_req_address),
    .io_start       (io_icache_start),
    .io_ready       (io_icache_ready),
    .io_done        (io_icache_valid),
    .io_miss        (_icache_io_miss),
    .io_data        (io_icache_data),
    .io_line_result (_l2_cache_io_mem_resp_in),
    .io_line_addr   (_icache_io_line_addr),
    .io_line_valid  (_arbiter_io_resp_to_cache_1)
  );
  DCache dcache (
    .clock             (clock),
    .reset             (reset),
    .io_req_address    (_dcache_queue_io_dcache_req_address),
    .io_req_write_data (_dcache_queue_io_dcache_req_write_data),
    .io_req_op         (_dcache_queue_io_dcache_req_op),
    .io_req_write      (_dcache_queue_io_dcache_req_write),
    .io_start          (_dcache_queue_io_dcache_start),
    .io_ready          (_dcache_io_ready),
    .io_done           (_dcache_io_done),
    .io_miss           (_dcache_io_miss),
    .io_data           (_dcache_io_data),
    .io_wb             (_dcache_io_wb),
    .io_wb_data        (_dcache_io_wb_data),
    .io_wb_addr        (_dcache_io_wb_addr),
    .io_line_result    (_l2_cache_io_mem_resp_in),
    .io_line_addr      (_dcache_io_line_addr),
    .io_line_valid     (_arbiter_io_resp_to_cache_0)
  );
  CacheArbiter arbiter (
    .clock                     (clock),
    .reset                     (reset),
    .io_cache_req_0_valid      (_dcache_io_miss | _dcache_io_wb),
    .io_cache_req_0_bits_addr
      (_dcache_io_wb ? _dcache_io_wb_addr : _dcache_io_line_addr),
    .io_cache_req_0_bits_write (_dcache_io_wb),
    .io_cache_req_0_bits_wdata (_dcache_io_wb_data),
    .io_cache_req_1_valid      (_icache_io_miss),
    .io_cache_req_1_bits_addr  (_icache_io_line_addr),
    .io_mem_req_ready          (_l2_cache_io_req_ready),
    .io_mem_req_valid          (_arbiter_io_mem_req_valid),
    .io_mem_req_bits_addr      (_arbiter_io_mem_req_bits_addr),
    .io_mem_req_bits_write     (_arbiter_io_mem_req_bits_write),
    .io_mem_req_bits_wdata     (_arbiter_io_mem_req_bits_wdata),
    .io_mem_valid              (_l2_cache_io_mem_valid_in),
    .io_resp_to_cache_0        (_arbiter_io_resp_to_cache_0),
    .io_resp_to_cache_1        (_arbiter_io_resp_to_cache_1)
  );
  DCacheQueue dcache_queue (
    .clock                    (clock),
    .reset                    (reset),
    .io_req_req_address       (io_dcache_req_address),
    .io_req_req_write_data    (io_dcache_req_write_data),
    .io_req_req_op            (io_dcache_req_op),
    .io_req_req_read          (io_dcache_req_read),
    .io_req_req_write         (io_dcache_req_write),
    .io_req_rd                (io_dcache_rd),
    .io_req_lane              (io_dcache_lane),
    .io_req_wen               (io_dcache_wen),
    .io_start                 (io_dcache_start),
    .io_ready                 (io_dcache_ready),
    .io_valid                 (io_dcache_valid),
    .io_data                  (io_dcache_data),
    .io_rd                    (io_dcache_rd_out),
    .io_wen                   (io_dcache_wen_out),
    .io_dcache_req_address    (_dcache_queue_io_dcache_req_address),
    .io_dcache_req_write_data (_dcache_queue_io_dcache_req_write_data),
    .io_dcache_req_op         (_dcache_queue_io_dcache_req_op),
    .io_dcache_req_write      (_dcache_queue_io_dcache_req_write),
    .io_dcache_start          (_dcache_queue_io_dcache_start),
    .io_dcache_ready          (_dcache_io_ready),
    .io_dcache_valid          (_dcache_io_done),
    .io_dcache_data           (_dcache_io_data)
  );
  L2Cache l2_cache (
    .clock                 (clock),
    .reset                 (reset),
    .io_req_ready          (_l2_cache_io_req_ready),
    .io_req_valid          (_arbiter_io_mem_req_valid),
    .io_req_bits_addr      (_arbiter_io_mem_req_bits_addr),
    .io_req_bits_write     (_arbiter_io_mem_req_bits_write),
    .io_req_bits_wdata     (_arbiter_io_mem_req_bits_wdata),
    .io_mem_resp_in        (_l2_cache_io_mem_resp_in),
    .io_mem_valid_in       (_l2_cache_io_mem_valid_in),
    .io_mem_req_ready      (io_mem_req_ready),
    .io_mem_req_valid      (io_mem_req_valid),
    .io_mem_req_bits_addr  (io_mem_req_bits_addr),
    .io_mem_req_bits_write (io_mem_req_bits_write),
    .io_mem_req_bits_wdata (io_mem_req_bits_wdata),
    .io_mem_resp           (io_mem_resp),
    .io_mem_valid          (io_mem_valid)
  );
endmodule

