// Generated by CIRCT firtool-1.128.0
// VCS coverage exclude_file
module meta_array_1024x18(
  input  [9:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [17:0] R0_data,
  input  [9:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [17:0] W0_data
);

  reg [17:0] Memory[0:1023];
  reg        _R0_en_d0;
  reg [9:0]  _R0_addr_d0;
  always @(posedge R0_clk) begin
    _R0_en_d0 <= R0_en;
    _R0_addr_d0 <= R0_addr;
  end // always @(posedge)
  always @(posedge W0_clk) begin
    if (W0_en)
      Memory[W0_addr] <= W0_data;
  end // always @(posedge)
  assign R0_data = _R0_en_d0 ? Memory[_R0_addr_d0] : 18'bx;
endmodule

