// Generated by CIRCT firtool-1.128.0
module Queue64_MemReqWrapped(
  input         clock,
                reset,
  output        io_enq_ready,
  input         io_enq_valid,
  input  [31:0] io_enq_bits_req_address,
                io_enq_bits_req_write_data,
  input  [2:0]  io_enq_bits_req_op,
  input         io_enq_bits_req_read,
                io_enq_bits_req_write,
  input  [6:0]  io_enq_bits_rd,
  input         io_enq_bits_lane,
                io_enq_bits_wen,
                io_deq_ready,
  output        io_deq_valid,
  output [31:0] io_deq_bits_req_address,
                io_deq_bits_req_write_data,
  output [2:0]  io_deq_bits_req_op,
  output        io_deq_bits_req_write,
  output [6:0]  io_deq_bits_rd,
  output        io_deq_bits_wen
);

  wire [75:0] _ram_ext_R0_data;
  reg  [5:0]  enq_ptr_value;
  reg  [5:0]  deq_ptr_value;
  reg         maybe_full;
  wire        ptr_match = enq_ptr_value == deq_ptr_value;
  wire        empty = ptr_match & ~maybe_full;
  wire        full = ptr_match & maybe_full;
  wire        io_deq_valid_0 = io_enq_valid | ~empty;
  wire        do_enq = ~(empty & io_deq_ready) & ~full & io_enq_valid;
  always @(posedge clock) begin
    if (reset) begin
      enq_ptr_value <= 6'h0;
      deq_ptr_value <= 6'h0;
      maybe_full <= 1'h0;
    end
    else begin
      automatic logic do_deq = ~empty & io_deq_ready & io_deq_valid_0;
      if (do_enq)
        enq_ptr_value <= enq_ptr_value + 6'h1;
      if (do_deq)
        deq_ptr_value <= deq_ptr_value + 6'h1;
      if (do_enq != do_deq)
        maybe_full <= do_enq;
    end
  end // always @(posedge)
  ram_64x76 ram_ext (
    .R0_addr (deq_ptr_value),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_ram_ext_R0_data),
    .W0_addr (enq_ptr_value),
    .W0_en   (do_enq),
    .W0_clk  (clock),
    .W0_data
      ({io_enq_bits_req_address,
        io_enq_bits_req_write_data,
        io_enq_bits_req_op,
        io_enq_bits_req_write,
        io_enq_bits_rd,
        io_enq_bits_wen})
  );
  assign io_enq_ready = ~full;
  assign io_deq_valid = io_deq_valid_0;
  assign io_deq_bits_req_address =
    empty ? io_enq_bits_req_address : _ram_ext_R0_data[75:44];
  assign io_deq_bits_req_write_data =
    empty ? io_enq_bits_req_write_data : _ram_ext_R0_data[43:12];
  assign io_deq_bits_req_op = empty ? io_enq_bits_req_op : _ram_ext_R0_data[11:9];
  assign io_deq_bits_req_write = empty ? io_enq_bits_req_write : _ram_ext_R0_data[8];
  assign io_deq_bits_rd = empty ? io_enq_bits_rd : _ram_ext_R0_data[7:1];
  assign io_deq_bits_wen = empty ? io_enq_bits_wen : _ram_ext_R0_data[0];
endmodule

