// Generated by CIRCT firtool-1.128.0
module Queue2_VecMemReq(
  input         clock,
                reset,
  output        io_enq_ready,
  input         io_enq_valid,
  input  [31:0] io_enq_bits_base_0,
                io_enq_bits_wdata_0,
                io_enq_bits_imm,
  input         io_enq_bits_mask,
  input  [6:0]  io_enq_bits_rd,
  input  [2:0]  io_enq_bits_func3,
  input         io_enq_bits_write,
                io_deq_ready,
  output        io_deq_valid,
  output [31:0] io_deq_bits_base_0,
                io_deq_bits_wdata_0,
                io_deq_bits_imm,
  output        io_deq_bits_mask,
  output [6:0]  io_deq_bits_rd,
  output [2:0]  io_deq_bits_func3,
  output        io_deq_bits_write
);

  wire [107:0] _ram_ext_R0_data;
  reg          enq_ptr_value;
  reg          deq_ptr_value;
  reg          maybe_full;
  wire         ptr_match = enq_ptr_value == deq_ptr_value;
  wire         empty = ptr_match & ~maybe_full;
  wire         full = ptr_match & maybe_full;
  wire         do_enq = ~full & io_enq_valid;
  always @(posedge clock) begin
    if (reset) begin
      enq_ptr_value <= 1'h0;
      deq_ptr_value <= 1'h0;
      maybe_full <= 1'h0;
    end
    else begin
      automatic logic do_deq = io_deq_ready & ~empty;
      if (do_enq)
        enq_ptr_value <= enq_ptr_value - 1'h1;
      if (do_deq)
        deq_ptr_value <= deq_ptr_value - 1'h1;
      if (do_enq != do_deq)
        maybe_full <= do_enq;
    end
  end // always @(posedge)
  ram_2x108 ram_ext (
    .R0_addr (deq_ptr_value),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_ram_ext_R0_data),
    .W0_addr (enq_ptr_value),
    .W0_en   (do_enq),
    .W0_clk  (clock),
    .W0_data
      ({io_enq_bits_base_0,
        io_enq_bits_wdata_0,
        io_enq_bits_imm,
        io_enq_bits_mask,
        io_enq_bits_rd,
        io_enq_bits_func3,
        io_enq_bits_write})
  );
  assign io_enq_ready = ~full;
  assign io_deq_valid = ~empty;
  assign io_deq_bits_base_0 = _ram_ext_R0_data[107:76];
  assign io_deq_bits_wdata_0 = _ram_ext_R0_data[75:44];
  assign io_deq_bits_imm = _ram_ext_R0_data[43:12];
  assign io_deq_bits_mask = _ram_ext_R0_data[11];
  assign io_deq_bits_rd = _ram_ext_R0_data[10:4];
  assign io_deq_bits_func3 = _ram_ext_R0_data[3:1];
  assign io_deq_bits_write = _ram_ext_R0_data[0];
endmodule

