// Generated by CIRCT firtool-1.128.0
// VCS coverage exclude_file
module ram_2x1083(
  input           R0_addr,
                  R0_en,
                  R0_clk,
  output [1082:0] R0_data,
  input           W0_addr,
                  W0_en,
                  W0_clk,
  input  [1082:0] W0_data
);

  reg [1082:0] Memory[0:1];
  always @(posedge W0_clk) begin
    if (W0_en)
      Memory[W0_addr] <= W0_data;
  end // always @(posedge)
  assign R0_data = R0_en ? Memory[R0_addr] : 1083'bx;
endmodule

