// Generated by CIRCT firtool-1.128.0
module Registers(
  input         clock,
                reset,
                io_write_enable,
  input  [6:0]  io_write_address,
  input         io_write_mask,
  input  [31:0] io_in_0,
  input         io_write_enable2,
  input  [6:0]  io_write_address2,
  input  [31:0] io_in2_0,
  input  [6:0]  io_read_address_a,
                io_read_address_b,
  output [31:0] io_out_a_0,
                io_out_b_0
);

  wire [31:0] _bank1_0_ext_R0_data;
  wire [31:0] _bank1_0_ext_R1_data;
  wire [31:0] _bank0_0_ext_R0_data;
  wire [31:0] _bank0_0_ext_R1_data;
  reg         lvt_0;
  reg         lvt_1;
  reg         lvt_2;
  reg         lvt_3;
  reg         lvt_4;
  reg         lvt_5;
  reg         lvt_6;
  reg         lvt_7;
  reg         lvt_8;
  reg         lvt_9;
  reg         lvt_10;
  reg         lvt_11;
  reg         lvt_12;
  reg         lvt_13;
  reg         lvt_14;
  reg         lvt_15;
  reg         lvt_16;
  reg         lvt_17;
  reg         lvt_18;
  reg         lvt_19;
  reg         lvt_20;
  reg         lvt_21;
  reg         lvt_22;
  reg         lvt_23;
  reg         lvt_24;
  reg         lvt_25;
  reg         lvt_26;
  reg         lvt_27;
  reg         lvt_28;
  reg         lvt_29;
  reg         lvt_30;
  reg         lvt_31;
  reg         lvt_32;
  reg         lvt_33;
  reg         lvt_34;
  reg         lvt_35;
  reg         lvt_36;
  reg         lvt_37;
  reg         lvt_38;
  reg         lvt_39;
  reg         lvt_40;
  reg         lvt_41;
  reg         lvt_42;
  reg         lvt_43;
  reg         lvt_44;
  reg         lvt_45;
  reg         lvt_46;
  reg         lvt_47;
  reg         lvt_48;
  reg         lvt_49;
  reg         lvt_50;
  reg         lvt_51;
  reg         lvt_52;
  reg         lvt_53;
  reg         lvt_54;
  reg         lvt_55;
  reg         lvt_56;
  reg         lvt_57;
  reg         lvt_58;
  reg         lvt_59;
  reg         lvt_60;
  reg         lvt_61;
  reg         lvt_62;
  reg         lvt_63;
  reg         lvt_64;
  reg         lvt_65;
  reg         lvt_66;
  reg         lvt_67;
  reg         lvt_68;
  reg         lvt_69;
  reg         lvt_70;
  reg         lvt_71;
  reg         lvt_72;
  reg         lvt_73;
  reg         lvt_74;
  reg         lvt_75;
  reg         lvt_76;
  reg         lvt_77;
  reg         lvt_78;
  reg         lvt_79;
  reg         lvt_80;
  reg         lvt_81;
  reg         lvt_82;
  reg         lvt_83;
  reg         lvt_84;
  reg         lvt_85;
  reg         lvt_86;
  reg         lvt_87;
  reg         lvt_88;
  reg         lvt_89;
  reg         lvt_90;
  reg         lvt_91;
  reg         lvt_92;
  reg         lvt_93;
  reg         lvt_94;
  reg         lvt_95;
  reg         lvt_96;
  reg         lvt_97;
  reg         lvt_98;
  reg         lvt_99;
  reg         lvt_100;
  reg         lvt_101;
  reg         lvt_102;
  reg         lvt_103;
  reg         lvt_104;
  reg         lvt_105;
  reg         lvt_106;
  reg         lvt_107;
  reg         lvt_108;
  reg         lvt_109;
  reg         lvt_110;
  reg         lvt_111;
  reg         lvt_112;
  reg         lvt_113;
  reg         lvt_114;
  reg         lvt_115;
  reg         lvt_116;
  reg         lvt_117;
  reg         lvt_118;
  reg         lvt_119;
  reg         lvt_120;
  reg         lvt_121;
  reg         lvt_122;
  reg         lvt_123;
  reg         lvt_124;
  reg         lvt_125;
  reg         lvt_126;
  reg         lvt_127;
  wire        w1 = io_write_enable & (|(io_write_address[4:0]));
  wire        w2 = io_write_enable2 & (|(io_write_address2[4:0]));
  wire        same = io_write_address == io_write_address2;
  wire        _mask2_T = w1 & same;
  wire        mask2 = ~_mask2_T | ~io_write_mask;
  reg         sel_a;
  reg         sel_b;
  reg         a_x0;
  reg         b_x0;
  always @(posedge clock) begin
    if (reset) begin
      lvt_0 <= 1'h0;
      lvt_1 <= 1'h0;
      lvt_2 <= 1'h0;
      lvt_3 <= 1'h0;
      lvt_4 <= 1'h0;
      lvt_5 <= 1'h0;
      lvt_6 <= 1'h0;
      lvt_7 <= 1'h0;
      lvt_8 <= 1'h0;
      lvt_9 <= 1'h0;
      lvt_10 <= 1'h0;
      lvt_11 <= 1'h0;
      lvt_12 <= 1'h0;
      lvt_13 <= 1'h0;
      lvt_14 <= 1'h0;
      lvt_15 <= 1'h0;
      lvt_16 <= 1'h0;
      lvt_17 <= 1'h0;
      lvt_18 <= 1'h0;
      lvt_19 <= 1'h0;
      lvt_20 <= 1'h0;
      lvt_21 <= 1'h0;
      lvt_22 <= 1'h0;
      lvt_23 <= 1'h0;
      lvt_24 <= 1'h0;
      lvt_25 <= 1'h0;
      lvt_26 <= 1'h0;
      lvt_27 <= 1'h0;
      lvt_28 <= 1'h0;
      lvt_29 <= 1'h0;
      lvt_30 <= 1'h0;
      lvt_31 <= 1'h0;
      lvt_32 <= 1'h0;
      lvt_33 <= 1'h0;
      lvt_34 <= 1'h0;
      lvt_35 <= 1'h0;
      lvt_36 <= 1'h0;
      lvt_37 <= 1'h0;
      lvt_38 <= 1'h0;
      lvt_39 <= 1'h0;
      lvt_40 <= 1'h0;
      lvt_41 <= 1'h0;
      lvt_42 <= 1'h0;
      lvt_43 <= 1'h0;
      lvt_44 <= 1'h0;
      lvt_45 <= 1'h0;
      lvt_46 <= 1'h0;
      lvt_47 <= 1'h0;
      lvt_48 <= 1'h0;
      lvt_49 <= 1'h0;
      lvt_50 <= 1'h0;
      lvt_51 <= 1'h0;
      lvt_52 <= 1'h0;
      lvt_53 <= 1'h0;
      lvt_54 <= 1'h0;
      lvt_55 <= 1'h0;
      lvt_56 <= 1'h0;
      lvt_57 <= 1'h0;
      lvt_58 <= 1'h0;
      lvt_59 <= 1'h0;
      lvt_60 <= 1'h0;
      lvt_61 <= 1'h0;
      lvt_62 <= 1'h0;
      lvt_63 <= 1'h0;
      lvt_64 <= 1'h0;
      lvt_65 <= 1'h0;
      lvt_66 <= 1'h0;
      lvt_67 <= 1'h0;
      lvt_68 <= 1'h0;
      lvt_69 <= 1'h0;
      lvt_70 <= 1'h0;
      lvt_71 <= 1'h0;
      lvt_72 <= 1'h0;
      lvt_73 <= 1'h0;
      lvt_74 <= 1'h0;
      lvt_75 <= 1'h0;
      lvt_76 <= 1'h0;
      lvt_77 <= 1'h0;
      lvt_78 <= 1'h0;
      lvt_79 <= 1'h0;
      lvt_80 <= 1'h0;
      lvt_81 <= 1'h0;
      lvt_82 <= 1'h0;
      lvt_83 <= 1'h0;
      lvt_84 <= 1'h0;
      lvt_85 <= 1'h0;
      lvt_86 <= 1'h0;
      lvt_87 <= 1'h0;
      lvt_88 <= 1'h0;
      lvt_89 <= 1'h0;
      lvt_90 <= 1'h0;
      lvt_91 <= 1'h0;
      lvt_92 <= 1'h0;
      lvt_93 <= 1'h0;
      lvt_94 <= 1'h0;
      lvt_95 <= 1'h0;
      lvt_96 <= 1'h0;
      lvt_97 <= 1'h0;
      lvt_98 <= 1'h0;
      lvt_99 <= 1'h0;
      lvt_100 <= 1'h0;
      lvt_101 <= 1'h0;
      lvt_102 <= 1'h0;
      lvt_103 <= 1'h0;
      lvt_104 <= 1'h0;
      lvt_105 <= 1'h0;
      lvt_106 <= 1'h0;
      lvt_107 <= 1'h0;
      lvt_108 <= 1'h0;
      lvt_109 <= 1'h0;
      lvt_110 <= 1'h0;
      lvt_111 <= 1'h0;
      lvt_112 <= 1'h0;
      lvt_113 <= 1'h0;
      lvt_114 <= 1'h0;
      lvt_115 <= 1'h0;
      lvt_116 <= 1'h0;
      lvt_117 <= 1'h0;
      lvt_118 <= 1'h0;
      lvt_119 <= 1'h0;
      lvt_120 <= 1'h0;
      lvt_121 <= 1'h0;
      lvt_122 <= 1'h0;
      lvt_123 <= 1'h0;
      lvt_124 <= 1'h0;
      lvt_125 <= 1'h0;
      lvt_126 <= 1'h0;
      lvt_127 <= 1'h0;
      sel_a <= 1'h0;
      sel_b <= 1'h0;
      a_x0 <= 1'h1;
      b_x0 <= 1'h1;
    end
    else begin
      automatic logic [127:0] _GEN =
        {{lvt_127},
         {lvt_126},
         {lvt_125},
         {lvt_124},
         {lvt_123},
         {lvt_122},
         {lvt_121},
         {lvt_120},
         {lvt_119},
         {lvt_118},
         {lvt_117},
         {lvt_116},
         {lvt_115},
         {lvt_114},
         {lvt_113},
         {lvt_112},
         {lvt_111},
         {lvt_110},
         {lvt_109},
         {lvt_108},
         {lvt_107},
         {lvt_106},
         {lvt_105},
         {lvt_104},
         {lvt_103},
         {lvt_102},
         {lvt_101},
         {lvt_100},
         {lvt_99},
         {lvt_98},
         {lvt_97},
         {lvt_96},
         {lvt_95},
         {lvt_94},
         {lvt_93},
         {lvt_92},
         {lvt_91},
         {lvt_90},
         {lvt_89},
         {lvt_88},
         {lvt_87},
         {lvt_86},
         {lvt_85},
         {lvt_84},
         {lvt_83},
         {lvt_82},
         {lvt_81},
         {lvt_80},
         {lvt_79},
         {lvt_78},
         {lvt_77},
         {lvt_76},
         {lvt_75},
         {lvt_74},
         {lvt_73},
         {lvt_72},
         {lvt_71},
         {lvt_70},
         {lvt_69},
         {lvt_68},
         {lvt_67},
         {lvt_66},
         {lvt_65},
         {lvt_64},
         {lvt_63},
         {lvt_62},
         {lvt_61},
         {lvt_60},
         {lvt_59},
         {lvt_58},
         {lvt_57},
         {lvt_56},
         {lvt_55},
         {lvt_54},
         {lvt_53},
         {lvt_52},
         {lvt_51},
         {lvt_50},
         {lvt_49},
         {lvt_48},
         {lvt_47},
         {lvt_46},
         {lvt_45},
         {lvt_44},
         {lvt_43},
         {lvt_42},
         {lvt_41},
         {lvt_40},
         {lvt_39},
         {lvt_38},
         {lvt_37},
         {lvt_36},
         {lvt_35},
         {lvt_34},
         {lvt_33},
         {lvt_32},
         {lvt_31},
         {lvt_30},
         {lvt_29},
         {lvt_28},
         {lvt_27},
         {lvt_26},
         {lvt_25},
         {lvt_24},
         {lvt_23},
         {lvt_22},
         {lvt_21},
         {lvt_20},
         {lvt_19},
         {lvt_18},
         {lvt_17},
         {lvt_16},
         {lvt_15},
         {lvt_14},
         {lvt_13},
         {lvt_12},
         {lvt_11},
         {lvt_10},
         {lvt_9},
         {lvt_8},
         {lvt_7},
         {lvt_6},
         {lvt_5},
         {lvt_4},
         {lvt_3},
         {lvt_2},
         {lvt_1},
         {lvt_0}};
      automatic logic         _lvt_T_4;
      automatic logic         _GEN_0 = w2 & ~_mask2_T;
      automatic logic         _lvt_T_5;
      _lvt_T_4 = _GEN[io_write_address] & ~io_write_mask | w2 & same & mask2;
      _lvt_T_5 = _GEN[io_write_address2] | mask2;
      if (_GEN_0 & io_write_address2 == 7'h0)
        lvt_0 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h0)
        lvt_0 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h1)
        lvt_1 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h1)
        lvt_1 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h2)
        lvt_2 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h2)
        lvt_2 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h3)
        lvt_3 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h3)
        lvt_3 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h4)
        lvt_4 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h4)
        lvt_4 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h5)
        lvt_5 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h5)
        lvt_5 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h6)
        lvt_6 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h6)
        lvt_6 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h7)
        lvt_7 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h7)
        lvt_7 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h8)
        lvt_8 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h8)
        lvt_8 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h9)
        lvt_9 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h9)
        lvt_9 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'hA)
        lvt_10 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'hA)
        lvt_10 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'hB)
        lvt_11 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'hB)
        lvt_11 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'hC)
        lvt_12 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'hC)
        lvt_12 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'hD)
        lvt_13 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'hD)
        lvt_13 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'hE)
        lvt_14 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'hE)
        lvt_14 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'hF)
        lvt_15 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'hF)
        lvt_15 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h10)
        lvt_16 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h10)
        lvt_16 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h11)
        lvt_17 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h11)
        lvt_17 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h12)
        lvt_18 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h12)
        lvt_18 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h13)
        lvt_19 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h13)
        lvt_19 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h14)
        lvt_20 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h14)
        lvt_20 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h15)
        lvt_21 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h15)
        lvt_21 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h16)
        lvt_22 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h16)
        lvt_22 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h17)
        lvt_23 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h17)
        lvt_23 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h18)
        lvt_24 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h18)
        lvt_24 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h19)
        lvt_25 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h19)
        lvt_25 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h1A)
        lvt_26 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h1A)
        lvt_26 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h1B)
        lvt_27 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h1B)
        lvt_27 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h1C)
        lvt_28 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h1C)
        lvt_28 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h1D)
        lvt_29 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h1D)
        lvt_29 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h1E)
        lvt_30 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h1E)
        lvt_30 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h1F)
        lvt_31 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h1F)
        lvt_31 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h20)
        lvt_32 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h20)
        lvt_32 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h21)
        lvt_33 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h21)
        lvt_33 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h22)
        lvt_34 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h22)
        lvt_34 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h23)
        lvt_35 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h23)
        lvt_35 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h24)
        lvt_36 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h24)
        lvt_36 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h25)
        lvt_37 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h25)
        lvt_37 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h26)
        lvt_38 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h26)
        lvt_38 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h27)
        lvt_39 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h27)
        lvt_39 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h28)
        lvt_40 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h28)
        lvt_40 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h29)
        lvt_41 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h29)
        lvt_41 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h2A)
        lvt_42 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h2A)
        lvt_42 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h2B)
        lvt_43 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h2B)
        lvt_43 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h2C)
        lvt_44 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h2C)
        lvt_44 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h2D)
        lvt_45 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h2D)
        lvt_45 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h2E)
        lvt_46 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h2E)
        lvt_46 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h2F)
        lvt_47 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h2F)
        lvt_47 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h30)
        lvt_48 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h30)
        lvt_48 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h31)
        lvt_49 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h31)
        lvt_49 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h32)
        lvt_50 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h32)
        lvt_50 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h33)
        lvt_51 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h33)
        lvt_51 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h34)
        lvt_52 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h34)
        lvt_52 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h35)
        lvt_53 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h35)
        lvt_53 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h36)
        lvt_54 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h36)
        lvt_54 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h37)
        lvt_55 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h37)
        lvt_55 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h38)
        lvt_56 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h38)
        lvt_56 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h39)
        lvt_57 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h39)
        lvt_57 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h3A)
        lvt_58 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h3A)
        lvt_58 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h3B)
        lvt_59 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h3B)
        lvt_59 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h3C)
        lvt_60 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h3C)
        lvt_60 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h3D)
        lvt_61 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h3D)
        lvt_61 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h3E)
        lvt_62 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h3E)
        lvt_62 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h3F)
        lvt_63 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h3F)
        lvt_63 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h40)
        lvt_64 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h40)
        lvt_64 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h41)
        lvt_65 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h41)
        lvt_65 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h42)
        lvt_66 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h42)
        lvt_66 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h43)
        lvt_67 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h43)
        lvt_67 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h44)
        lvt_68 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h44)
        lvt_68 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h45)
        lvt_69 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h45)
        lvt_69 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h46)
        lvt_70 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h46)
        lvt_70 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h47)
        lvt_71 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h47)
        lvt_71 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h48)
        lvt_72 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h48)
        lvt_72 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h49)
        lvt_73 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h49)
        lvt_73 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h4A)
        lvt_74 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h4A)
        lvt_74 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h4B)
        lvt_75 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h4B)
        lvt_75 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h4C)
        lvt_76 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h4C)
        lvt_76 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h4D)
        lvt_77 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h4D)
        lvt_77 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h4E)
        lvt_78 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h4E)
        lvt_78 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h4F)
        lvt_79 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h4F)
        lvt_79 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h50)
        lvt_80 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h50)
        lvt_80 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h51)
        lvt_81 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h51)
        lvt_81 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h52)
        lvt_82 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h52)
        lvt_82 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h53)
        lvt_83 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h53)
        lvt_83 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h54)
        lvt_84 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h54)
        lvt_84 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h55)
        lvt_85 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h55)
        lvt_85 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h56)
        lvt_86 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h56)
        lvt_86 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h57)
        lvt_87 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h57)
        lvt_87 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h58)
        lvt_88 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h58)
        lvt_88 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h59)
        lvt_89 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h59)
        lvt_89 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h5A)
        lvt_90 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h5A)
        lvt_90 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h5B)
        lvt_91 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h5B)
        lvt_91 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h5C)
        lvt_92 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h5C)
        lvt_92 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h5D)
        lvt_93 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h5D)
        lvt_93 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h5E)
        lvt_94 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h5E)
        lvt_94 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h5F)
        lvt_95 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h5F)
        lvt_95 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h60)
        lvt_96 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h60)
        lvt_96 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h61)
        lvt_97 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h61)
        lvt_97 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h62)
        lvt_98 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h62)
        lvt_98 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h63)
        lvt_99 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h63)
        lvt_99 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h64)
        lvt_100 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h64)
        lvt_100 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h65)
        lvt_101 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h65)
        lvt_101 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h66)
        lvt_102 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h66)
        lvt_102 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h67)
        lvt_103 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h67)
        lvt_103 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h68)
        lvt_104 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h68)
        lvt_104 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h69)
        lvt_105 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h69)
        lvt_105 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h6A)
        lvt_106 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h6A)
        lvt_106 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h6B)
        lvt_107 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h6B)
        lvt_107 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h6C)
        lvt_108 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h6C)
        lvt_108 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h6D)
        lvt_109 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h6D)
        lvt_109 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h6E)
        lvt_110 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h6E)
        lvt_110 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h6F)
        lvt_111 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h6F)
        lvt_111 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h70)
        lvt_112 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h70)
        lvt_112 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h71)
        lvt_113 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h71)
        lvt_113 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h72)
        lvt_114 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h72)
        lvt_114 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h73)
        lvt_115 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h73)
        lvt_115 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h74)
        lvt_116 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h74)
        lvt_116 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h75)
        lvt_117 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h75)
        lvt_117 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h76)
        lvt_118 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h76)
        lvt_118 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h77)
        lvt_119 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h77)
        lvt_119 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h78)
        lvt_120 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h78)
        lvt_120 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h79)
        lvt_121 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h79)
        lvt_121 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h7A)
        lvt_122 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h7A)
        lvt_122 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h7B)
        lvt_123 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h7B)
        lvt_123 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h7C)
        lvt_124 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h7C)
        lvt_124 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h7D)
        lvt_125 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h7D)
        lvt_125 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h7E)
        lvt_126 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h7E)
        lvt_126 <= _lvt_T_4;
      if (_GEN_0 & (&io_write_address2))
        lvt_127 <= _lvt_T_5;
      else if (w1 & (&io_write_address))
        lvt_127 <= _lvt_T_4;
      sel_a <= _GEN[io_read_address_a];
      sel_b <= _GEN[io_read_address_b];
      a_x0 <= io_read_address_a[4:0] == 5'h0;
      b_x0 <= io_read_address_b[4:0] == 5'h0;
    end
  end // always @(posedge)
  bank_128x32 bank0_0_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank0_0_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank0_0_ext_R1_data),
    .W0_addr (io_write_address),
    .W0_en   (w1 & io_write_mask),
    .W0_clk  (clock),
    .W0_data (io_in_0)
  );
  bank_128x32 bank1_0_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank1_0_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank1_0_ext_R1_data),
    .W0_addr (io_write_address2),
    .W0_en   (w2 & mask2),
    .W0_clk  (clock),
    .W0_data (io_in2_0)
  );
  assign io_out_a_0 = a_x0 ? 32'h0 : sel_a ? _bank1_0_ext_R1_data : _bank0_0_ext_R1_data;
  assign io_out_b_0 = b_x0 ? 32'h0 : sel_b ? _bank1_0_ext_R0_data : _bank0_0_ext_R0_data;
endmodule

