// Generated by CIRCT firtool-1.128.0
module UartKeyboardTracker(
  input          clock,
                 reset,
                 io_rxd,
  output [255:0] io_keyDown,
  output [7:0]   io_lastCode,
  output         io_lastPressed,
                 io_eventValid,
  output [8:0]   io_numDown
);

  wire [7:0] _uart_io_data;
  wire       _uart_io_valid;
  reg        keyState_0;
  reg        keyState_1;
  reg        keyState_2;
  reg        keyState_3;
  reg        keyState_4;
  reg        keyState_5;
  reg        keyState_6;
  reg        keyState_7;
  reg        keyState_8;
  reg        keyState_9;
  reg        keyState_10;
  reg        keyState_11;
  reg        keyState_12;
  reg        keyState_13;
  reg        keyState_14;
  reg        keyState_15;
  reg        keyState_16;
  reg        keyState_17;
  reg        keyState_18;
  reg        keyState_19;
  reg        keyState_20;
  reg        keyState_21;
  reg        keyState_22;
  reg        keyState_23;
  reg        keyState_24;
  reg        keyState_25;
  reg        keyState_26;
  reg        keyState_27;
  reg        keyState_28;
  reg        keyState_29;
  reg        keyState_30;
  reg        keyState_31;
  reg        keyState_32;
  reg        keyState_33;
  reg        keyState_34;
  reg        keyState_35;
  reg        keyState_36;
  reg        keyState_37;
  reg        keyState_38;
  reg        keyState_39;
  reg        keyState_40;
  reg        keyState_41;
  reg        keyState_42;
  reg        keyState_43;
  reg        keyState_44;
  reg        keyState_45;
  reg        keyState_46;
  reg        keyState_47;
  reg        keyState_48;
  reg        keyState_49;
  reg        keyState_50;
  reg        keyState_51;
  reg        keyState_52;
  reg        keyState_53;
  reg        keyState_54;
  reg        keyState_55;
  reg        keyState_56;
  reg        keyState_57;
  reg        keyState_58;
  reg        keyState_59;
  reg        keyState_60;
  reg        keyState_61;
  reg        keyState_62;
  reg        keyState_63;
  reg        keyState_64;
  reg        keyState_65;
  reg        keyState_66;
  reg        keyState_67;
  reg        keyState_68;
  reg        keyState_69;
  reg        keyState_70;
  reg        keyState_71;
  reg        keyState_72;
  reg        keyState_73;
  reg        keyState_74;
  reg        keyState_75;
  reg        keyState_76;
  reg        keyState_77;
  reg        keyState_78;
  reg        keyState_79;
  reg        keyState_80;
  reg        keyState_81;
  reg        keyState_82;
  reg        keyState_83;
  reg        keyState_84;
  reg        keyState_85;
  reg        keyState_86;
  reg        keyState_87;
  reg        keyState_88;
  reg        keyState_89;
  reg        keyState_90;
  reg        keyState_91;
  reg        keyState_92;
  reg        keyState_93;
  reg        keyState_94;
  reg        keyState_95;
  reg        keyState_96;
  reg        keyState_97;
  reg        keyState_98;
  reg        keyState_99;
  reg        keyState_100;
  reg        keyState_101;
  reg        keyState_102;
  reg        keyState_103;
  reg        keyState_104;
  reg        keyState_105;
  reg        keyState_106;
  reg        keyState_107;
  reg        keyState_108;
  reg        keyState_109;
  reg        keyState_110;
  reg        keyState_111;
  reg        keyState_112;
  reg        keyState_113;
  reg        keyState_114;
  reg        keyState_115;
  reg        keyState_116;
  reg        keyState_117;
  reg        keyState_118;
  reg        keyState_119;
  reg        keyState_120;
  reg        keyState_121;
  reg        keyState_122;
  reg        keyState_123;
  reg        keyState_124;
  reg        keyState_125;
  reg        keyState_126;
  reg        keyState_127;
  reg        keyState_128;
  reg        keyState_129;
  reg        keyState_130;
  reg        keyState_131;
  reg        keyState_132;
  reg        keyState_133;
  reg        keyState_134;
  reg        keyState_135;
  reg        keyState_136;
  reg        keyState_137;
  reg        keyState_138;
  reg        keyState_139;
  reg        keyState_140;
  reg        keyState_141;
  reg        keyState_142;
  reg        keyState_143;
  reg        keyState_144;
  reg        keyState_145;
  reg        keyState_146;
  reg        keyState_147;
  reg        keyState_148;
  reg        keyState_149;
  reg        keyState_150;
  reg        keyState_151;
  reg        keyState_152;
  reg        keyState_153;
  reg        keyState_154;
  reg        keyState_155;
  reg        keyState_156;
  reg        keyState_157;
  reg        keyState_158;
  reg        keyState_159;
  reg        keyState_160;
  reg        keyState_161;
  reg        keyState_162;
  reg        keyState_163;
  reg        keyState_164;
  reg        keyState_165;
  reg        keyState_166;
  reg        keyState_167;
  reg        keyState_168;
  reg        keyState_169;
  reg        keyState_170;
  reg        keyState_171;
  reg        keyState_172;
  reg        keyState_173;
  reg        keyState_174;
  reg        keyState_175;
  reg        keyState_176;
  reg        keyState_177;
  reg        keyState_178;
  reg        keyState_179;
  reg        keyState_180;
  reg        keyState_181;
  reg        keyState_182;
  reg        keyState_183;
  reg        keyState_184;
  reg        keyState_185;
  reg        keyState_186;
  reg        keyState_187;
  reg        keyState_188;
  reg        keyState_189;
  reg        keyState_190;
  reg        keyState_191;
  reg        keyState_192;
  reg        keyState_193;
  reg        keyState_194;
  reg        keyState_195;
  reg        keyState_196;
  reg        keyState_197;
  reg        keyState_198;
  reg        keyState_199;
  reg        keyState_200;
  reg        keyState_201;
  reg        keyState_202;
  reg        keyState_203;
  reg        keyState_204;
  reg        keyState_205;
  reg        keyState_206;
  reg        keyState_207;
  reg        keyState_208;
  reg        keyState_209;
  reg        keyState_210;
  reg        keyState_211;
  reg        keyState_212;
  reg        keyState_213;
  reg        keyState_214;
  reg        keyState_215;
  reg        keyState_216;
  reg        keyState_217;
  reg        keyState_218;
  reg        keyState_219;
  reg        keyState_220;
  reg        keyState_221;
  reg        keyState_222;
  reg        keyState_223;
  reg        keyState_224;
  reg        keyState_225;
  reg        keyState_226;
  reg        keyState_227;
  reg        keyState_228;
  reg        keyState_229;
  reg        keyState_230;
  reg        keyState_231;
  reg        keyState_232;
  reg        keyState_233;
  reg        keyState_234;
  reg        keyState_235;
  reg        keyState_236;
  reg        keyState_237;
  reg        keyState_238;
  reg        keyState_239;
  reg        keyState_240;
  reg        keyState_241;
  reg        keyState_242;
  reg        keyState_243;
  reg        keyState_244;
  reg        keyState_245;
  reg        keyState_246;
  reg        keyState_247;
  reg        keyState_248;
  reg        keyState_249;
  reg        keyState_250;
  reg        keyState_251;
  reg        keyState_252;
  reg        keyState_253;
  reg        keyState_254;
  reg        keyState_255;
  wire [7:0] _io_numDown_T_510 =
    {1'h0,
     {1'h0,
      {1'h0,
       {1'h0,
        {1'h0,
         {1'h0, {1'h0, keyState_0} + {1'h0, keyState_1}}
           + {1'h0, {1'h0, keyState_2} + {1'h0, keyState_3}}}
          + {1'h0,
             {1'h0, {1'h0, keyState_4} + {1'h0, keyState_5}}
               + {1'h0, {1'h0, keyState_6} + {1'h0, keyState_7}}}}
         + {1'h0,
            {1'h0,
             {1'h0, {1'h0, keyState_8} + {1'h0, keyState_9}}
               + {1'h0, {1'h0, keyState_10} + {1'h0, keyState_11}}}
              + {1'h0,
                 {1'h0, {1'h0, keyState_12} + {1'h0, keyState_13}}
                   + {1'h0, {1'h0, keyState_14} + {1'h0, keyState_15}}}}}
        + {1'h0,
           {1'h0,
            {1'h0,
             {1'h0, {1'h0, keyState_16} + {1'h0, keyState_17}}
               + {1'h0, {1'h0, keyState_18} + {1'h0, keyState_19}}}
              + {1'h0,
                 {1'h0, {1'h0, keyState_20} + {1'h0, keyState_21}}
                   + {1'h0, {1'h0, keyState_22} + {1'h0, keyState_23}}}}
             + {1'h0,
                {1'h0,
                 {1'h0, {1'h0, keyState_24} + {1'h0, keyState_25}}
                   + {1'h0, {1'h0, keyState_26} + {1'h0, keyState_27}}}
                  + {1'h0,
                     {1'h0, {1'h0, keyState_28} + {1'h0, keyState_29}}
                       + {1'h0, {1'h0, keyState_30} + {1'h0, keyState_31}}}}}}
       + {1'h0,
          {1'h0,
           {1'h0,
            {1'h0,
             {1'h0, {1'h0, keyState_32} + {1'h0, keyState_33}}
               + {1'h0, {1'h0, keyState_34} + {1'h0, keyState_35}}}
              + {1'h0,
                 {1'h0, {1'h0, keyState_36} + {1'h0, keyState_37}}
                   + {1'h0, {1'h0, keyState_38} + {1'h0, keyState_39}}}}
             + {1'h0,
                {1'h0,
                 {1'h0, {1'h0, keyState_40} + {1'h0, keyState_41}}
                   + {1'h0, {1'h0, keyState_42} + {1'h0, keyState_43}}}
                  + {1'h0,
                     {1'h0, {1'h0, keyState_44} + {1'h0, keyState_45}}
                       + {1'h0, {1'h0, keyState_46} + {1'h0, keyState_47}}}}}
            + {1'h0,
               {1'h0,
                {1'h0,
                 {1'h0, {1'h0, keyState_48} + {1'h0, keyState_49}}
                   + {1'h0, {1'h0, keyState_50} + {1'h0, keyState_51}}}
                  + {1'h0,
                     {1'h0, {1'h0, keyState_52} + {1'h0, keyState_53}}
                       + {1'h0, {1'h0, keyState_54} + {1'h0, keyState_55}}}}
                 + {1'h0,
                    {1'h0,
                     {1'h0, {1'h0, keyState_56} + {1'h0, keyState_57}}
                       + {1'h0, {1'h0, keyState_58} + {1'h0, keyState_59}}}
                      + {1'h0,
                         {1'h0, {1'h0, keyState_60} + {1'h0, keyState_61}}
                           + {1'h0, {1'h0, keyState_62} + {1'h0, keyState_63}}}}}}}
    + {1'h0,
       {1'h0,
        {1'h0,
         {1'h0,
          {1'h0,
           {1'h0, {1'h0, keyState_64} + {1'h0, keyState_65}}
             + {1'h0, {1'h0, keyState_66} + {1'h0, keyState_67}}}
            + {1'h0,
               {1'h0, {1'h0, keyState_68} + {1'h0, keyState_69}}
                 + {1'h0, {1'h0, keyState_70} + {1'h0, keyState_71}}}}
           + {1'h0,
              {1'h0,
               {1'h0, {1'h0, keyState_72} + {1'h0, keyState_73}}
                 + {1'h0, {1'h0, keyState_74} + {1'h0, keyState_75}}}
                + {1'h0,
                   {1'h0, {1'h0, keyState_76} + {1'h0, keyState_77}}
                     + {1'h0, {1'h0, keyState_78} + {1'h0, keyState_79}}}}}
          + {1'h0,
             {1'h0,
              {1'h0,
               {1'h0, {1'h0, keyState_80} + {1'h0, keyState_81}}
                 + {1'h0, {1'h0, keyState_82} + {1'h0, keyState_83}}}
                + {1'h0,
                   {1'h0, {1'h0, keyState_84} + {1'h0, keyState_85}}
                     + {1'h0, {1'h0, keyState_86} + {1'h0, keyState_87}}}}
               + {1'h0,
                  {1'h0,
                   {1'h0, {1'h0, keyState_88} + {1'h0, keyState_89}}
                     + {1'h0, {1'h0, keyState_90} + {1'h0, keyState_91}}}
                    + {1'h0,
                       {1'h0, {1'h0, keyState_92} + {1'h0, keyState_93}}
                         + {1'h0, {1'h0, keyState_94} + {1'h0, keyState_95}}}}}}
         + {1'h0,
            {1'h0,
             {1'h0,
              {1'h0,
               {1'h0, {1'h0, keyState_96} + {1'h0, keyState_97}}
                 + {1'h0, {1'h0, keyState_98} + {1'h0, keyState_99}}}
                + {1'h0,
                   {1'h0, {1'h0, keyState_100} + {1'h0, keyState_101}}
                     + {1'h0, {1'h0, keyState_102} + {1'h0, keyState_103}}}}
               + {1'h0,
                  {1'h0,
                   {1'h0, {1'h0, keyState_104} + {1'h0, keyState_105}}
                     + {1'h0, {1'h0, keyState_106} + {1'h0, keyState_107}}}
                    + {1'h0,
                       {1'h0, {1'h0, keyState_108} + {1'h0, keyState_109}}
                         + {1'h0, {1'h0, keyState_110} + {1'h0, keyState_111}}}}}
              + {1'h0,
                 {1'h0,
                  {1'h0,
                   {1'h0, {1'h0, keyState_112} + {1'h0, keyState_113}}
                     + {1'h0, {1'h0, keyState_114} + {1'h0, keyState_115}}}
                    + {1'h0,
                       {1'h0, {1'h0, keyState_116} + {1'h0, keyState_117}}
                         + {1'h0, {1'h0, keyState_118} + {1'h0, keyState_119}}}}
                   + {1'h0,
                      {1'h0,
                       {1'h0, {1'h0, keyState_120} + {1'h0, keyState_121}}
                         + {1'h0, {1'h0, keyState_122} + {1'h0, keyState_123}}}
                        + {1'h0,
                           {1'h0, {1'h0, keyState_124} + {1'h0, keyState_125}}
                             + {1'h0, {1'h0, keyState_126} + {1'h0, keyState_127}}}}}}};
  wire [7:0] _io_numDown_T_764 =
    {1'h0,
     {1'h0,
      {1'h0,
       {1'h0,
        {1'h0,
         {1'h0, {1'h0, keyState_128} + {1'h0, keyState_129}}
           + {1'h0, {1'h0, keyState_130} + {1'h0, keyState_131}}}
          + {1'h0,
             {1'h0, {1'h0, keyState_132} + {1'h0, keyState_133}}
               + {1'h0, {1'h0, keyState_134} + {1'h0, keyState_135}}}}
         + {1'h0,
            {1'h0,
             {1'h0, {1'h0, keyState_136} + {1'h0, keyState_137}}
               + {1'h0, {1'h0, keyState_138} + {1'h0, keyState_139}}}
              + {1'h0,
                 {1'h0, {1'h0, keyState_140} + {1'h0, keyState_141}}
                   + {1'h0, {1'h0, keyState_142} + {1'h0, keyState_143}}}}}
        + {1'h0,
           {1'h0,
            {1'h0,
             {1'h0, {1'h0, keyState_144} + {1'h0, keyState_145}}
               + {1'h0, {1'h0, keyState_146} + {1'h0, keyState_147}}}
              + {1'h0,
                 {1'h0, {1'h0, keyState_148} + {1'h0, keyState_149}}
                   + {1'h0, {1'h0, keyState_150} + {1'h0, keyState_151}}}}
             + {1'h0,
                {1'h0,
                 {1'h0, {1'h0, keyState_152} + {1'h0, keyState_153}}
                   + {1'h0, {1'h0, keyState_154} + {1'h0, keyState_155}}}
                  + {1'h0,
                     {1'h0, {1'h0, keyState_156} + {1'h0, keyState_157}}
                       + {1'h0, {1'h0, keyState_158} + {1'h0, keyState_159}}}}}}
       + {1'h0,
          {1'h0,
           {1'h0,
            {1'h0,
             {1'h0, {1'h0, keyState_160} + {1'h0, keyState_161}}
               + {1'h0, {1'h0, keyState_162} + {1'h0, keyState_163}}}
              + {1'h0,
                 {1'h0, {1'h0, keyState_164} + {1'h0, keyState_165}}
                   + {1'h0, {1'h0, keyState_166} + {1'h0, keyState_167}}}}
             + {1'h0,
                {1'h0,
                 {1'h0, {1'h0, keyState_168} + {1'h0, keyState_169}}
                   + {1'h0, {1'h0, keyState_170} + {1'h0, keyState_171}}}
                  + {1'h0,
                     {1'h0, {1'h0, keyState_172} + {1'h0, keyState_173}}
                       + {1'h0, {1'h0, keyState_174} + {1'h0, keyState_175}}}}}
            + {1'h0,
               {1'h0,
                {1'h0,
                 {1'h0, {1'h0, keyState_176} + {1'h0, keyState_177}}
                   + {1'h0, {1'h0, keyState_178} + {1'h0, keyState_179}}}
                  + {1'h0,
                     {1'h0, {1'h0, keyState_180} + {1'h0, keyState_181}}
                       + {1'h0, {1'h0, keyState_182} + {1'h0, keyState_183}}}}
                 + {1'h0,
                    {1'h0,
                     {1'h0, {1'h0, keyState_184} + {1'h0, keyState_185}}
                       + {1'h0, {1'h0, keyState_186} + {1'h0, keyState_187}}}
                      + {1'h0,
                         {1'h0, {1'h0, keyState_188} + {1'h0, keyState_189}}
                           + {1'h0, {1'h0, keyState_190} + {1'h0, keyState_191}}}}}}}
    + {1'h0,
       {1'h0,
        {1'h0,
         {1'h0,
          {1'h0,
           {1'h0, {1'h0, keyState_192} + {1'h0, keyState_193}}
             + {1'h0, {1'h0, keyState_194} + {1'h0, keyState_195}}}
            + {1'h0,
               {1'h0, {1'h0, keyState_196} + {1'h0, keyState_197}}
                 + {1'h0, {1'h0, keyState_198} + {1'h0, keyState_199}}}}
           + {1'h0,
              {1'h0,
               {1'h0, {1'h0, keyState_200} + {1'h0, keyState_201}}
                 + {1'h0, {1'h0, keyState_202} + {1'h0, keyState_203}}}
                + {1'h0,
                   {1'h0, {1'h0, keyState_204} + {1'h0, keyState_205}}
                     + {1'h0, {1'h0, keyState_206} + {1'h0, keyState_207}}}}}
          + {1'h0,
             {1'h0,
              {1'h0,
               {1'h0, {1'h0, keyState_208} + {1'h0, keyState_209}}
                 + {1'h0, {1'h0, keyState_210} + {1'h0, keyState_211}}}
                + {1'h0,
                   {1'h0, {1'h0, keyState_212} + {1'h0, keyState_213}}
                     + {1'h0, {1'h0, keyState_214} + {1'h0, keyState_215}}}}
               + {1'h0,
                  {1'h0,
                   {1'h0, {1'h0, keyState_216} + {1'h0, keyState_217}}
                     + {1'h0, {1'h0, keyState_218} + {1'h0, keyState_219}}}
                    + {1'h0,
                       {1'h0, {1'h0, keyState_220} + {1'h0, keyState_221}}
                         + {1'h0, {1'h0, keyState_222} + {1'h0, keyState_223}}}}}}
         + {1'h0,
            {1'h0,
             {1'h0,
              {1'h0,
               {1'h0, {1'h0, keyState_224} + {1'h0, keyState_225}}
                 + {1'h0, {1'h0, keyState_226} + {1'h0, keyState_227}}}
                + {1'h0,
                   {1'h0, {1'h0, keyState_228} + {1'h0, keyState_229}}
                     + {1'h0, {1'h0, keyState_230} + {1'h0, keyState_231}}}}
               + {1'h0,
                  {1'h0,
                   {1'h0, {1'h0, keyState_232} + {1'h0, keyState_233}}
                     + {1'h0, {1'h0, keyState_234} + {1'h0, keyState_235}}}
                    + {1'h0,
                       {1'h0, {1'h0, keyState_236} + {1'h0, keyState_237}}
                         + {1'h0, {1'h0, keyState_238} + {1'h0, keyState_239}}}}}
              + {1'h0,
                 {1'h0,
                  {1'h0,
                   {1'h0, {1'h0, keyState_240} + {1'h0, keyState_241}}
                     + {1'h0, {1'h0, keyState_242} + {1'h0, keyState_243}}}
                    + {1'h0,
                       {1'h0, {1'h0, keyState_244} + {1'h0, keyState_245}}
                         + {1'h0, {1'h0, keyState_246} + {1'h0, keyState_247}}}}
                   + {1'h0,
                      {1'h0,
                       {1'h0, {1'h0, keyState_248} + {1'h0, keyState_249}}
                         + {1'h0, {1'h0, keyState_250} + {1'h0, keyState_251}}}
                        + {1'h0,
                           {1'h0, {1'h0, keyState_252} + {1'h0, keyState_253}}
                             + {1'h0, {1'h0, keyState_254} + {1'h0, keyState_255}}}}}}};
  reg  [7:0] lastCodeReg;
  reg        lastPressedReg;
  reg        eventValidReg;
  reg        state;
  reg        eventType;
  always @(posedge clock) begin
    if (reset) begin
      keyState_0 <= 1'h0;
      keyState_1 <= 1'h0;
      keyState_2 <= 1'h0;
      keyState_3 <= 1'h0;
      keyState_4 <= 1'h0;
      keyState_5 <= 1'h0;
      keyState_6 <= 1'h0;
      keyState_7 <= 1'h0;
      keyState_8 <= 1'h0;
      keyState_9 <= 1'h0;
      keyState_10 <= 1'h0;
      keyState_11 <= 1'h0;
      keyState_12 <= 1'h0;
      keyState_13 <= 1'h0;
      keyState_14 <= 1'h0;
      keyState_15 <= 1'h0;
      keyState_16 <= 1'h0;
      keyState_17 <= 1'h0;
      keyState_18 <= 1'h0;
      keyState_19 <= 1'h0;
      keyState_20 <= 1'h0;
      keyState_21 <= 1'h0;
      keyState_22 <= 1'h0;
      keyState_23 <= 1'h0;
      keyState_24 <= 1'h0;
      keyState_25 <= 1'h0;
      keyState_26 <= 1'h0;
      keyState_27 <= 1'h0;
      keyState_28 <= 1'h0;
      keyState_29 <= 1'h0;
      keyState_30 <= 1'h0;
      keyState_31 <= 1'h0;
      keyState_32 <= 1'h0;
      keyState_33 <= 1'h0;
      keyState_34 <= 1'h0;
      keyState_35 <= 1'h0;
      keyState_36 <= 1'h0;
      keyState_37 <= 1'h0;
      keyState_38 <= 1'h0;
      keyState_39 <= 1'h0;
      keyState_40 <= 1'h0;
      keyState_41 <= 1'h0;
      keyState_42 <= 1'h0;
      keyState_43 <= 1'h0;
      keyState_44 <= 1'h0;
      keyState_45 <= 1'h0;
      keyState_46 <= 1'h0;
      keyState_47 <= 1'h0;
      keyState_48 <= 1'h0;
      keyState_49 <= 1'h0;
      keyState_50 <= 1'h0;
      keyState_51 <= 1'h0;
      keyState_52 <= 1'h0;
      keyState_53 <= 1'h0;
      keyState_54 <= 1'h0;
      keyState_55 <= 1'h0;
      keyState_56 <= 1'h0;
      keyState_57 <= 1'h0;
      keyState_58 <= 1'h0;
      keyState_59 <= 1'h0;
      keyState_60 <= 1'h0;
      keyState_61 <= 1'h0;
      keyState_62 <= 1'h0;
      keyState_63 <= 1'h0;
      keyState_64 <= 1'h0;
      keyState_65 <= 1'h0;
      keyState_66 <= 1'h0;
      keyState_67 <= 1'h0;
      keyState_68 <= 1'h0;
      keyState_69 <= 1'h0;
      keyState_70 <= 1'h0;
      keyState_71 <= 1'h0;
      keyState_72 <= 1'h0;
      keyState_73 <= 1'h0;
      keyState_74 <= 1'h0;
      keyState_75 <= 1'h0;
      keyState_76 <= 1'h0;
      keyState_77 <= 1'h0;
      keyState_78 <= 1'h0;
      keyState_79 <= 1'h0;
      keyState_80 <= 1'h0;
      keyState_81 <= 1'h0;
      keyState_82 <= 1'h0;
      keyState_83 <= 1'h0;
      keyState_84 <= 1'h0;
      keyState_85 <= 1'h0;
      keyState_86 <= 1'h0;
      keyState_87 <= 1'h0;
      keyState_88 <= 1'h0;
      keyState_89 <= 1'h0;
      keyState_90 <= 1'h0;
      keyState_91 <= 1'h0;
      keyState_92 <= 1'h0;
      keyState_93 <= 1'h0;
      keyState_94 <= 1'h0;
      keyState_95 <= 1'h0;
      keyState_96 <= 1'h0;
      keyState_97 <= 1'h0;
      keyState_98 <= 1'h0;
      keyState_99 <= 1'h0;
      keyState_100 <= 1'h0;
      keyState_101 <= 1'h0;
      keyState_102 <= 1'h0;
      keyState_103 <= 1'h0;
      keyState_104 <= 1'h0;
      keyState_105 <= 1'h0;
      keyState_106 <= 1'h0;
      keyState_107 <= 1'h0;
      keyState_108 <= 1'h0;
      keyState_109 <= 1'h0;
      keyState_110 <= 1'h0;
      keyState_111 <= 1'h0;
      keyState_112 <= 1'h0;
      keyState_113 <= 1'h0;
      keyState_114 <= 1'h0;
      keyState_115 <= 1'h0;
      keyState_116 <= 1'h0;
      keyState_117 <= 1'h0;
      keyState_118 <= 1'h0;
      keyState_119 <= 1'h0;
      keyState_120 <= 1'h0;
      keyState_121 <= 1'h0;
      keyState_122 <= 1'h0;
      keyState_123 <= 1'h0;
      keyState_124 <= 1'h0;
      keyState_125 <= 1'h0;
      keyState_126 <= 1'h0;
      keyState_127 <= 1'h0;
      keyState_128 <= 1'h0;
      keyState_129 <= 1'h0;
      keyState_130 <= 1'h0;
      keyState_131 <= 1'h0;
      keyState_132 <= 1'h0;
      keyState_133 <= 1'h0;
      keyState_134 <= 1'h0;
      keyState_135 <= 1'h0;
      keyState_136 <= 1'h0;
      keyState_137 <= 1'h0;
      keyState_138 <= 1'h0;
      keyState_139 <= 1'h0;
      keyState_140 <= 1'h0;
      keyState_141 <= 1'h0;
      keyState_142 <= 1'h0;
      keyState_143 <= 1'h0;
      keyState_144 <= 1'h0;
      keyState_145 <= 1'h0;
      keyState_146 <= 1'h0;
      keyState_147 <= 1'h0;
      keyState_148 <= 1'h0;
      keyState_149 <= 1'h0;
      keyState_150 <= 1'h0;
      keyState_151 <= 1'h0;
      keyState_152 <= 1'h0;
      keyState_153 <= 1'h0;
      keyState_154 <= 1'h0;
      keyState_155 <= 1'h0;
      keyState_156 <= 1'h0;
      keyState_157 <= 1'h0;
      keyState_158 <= 1'h0;
      keyState_159 <= 1'h0;
      keyState_160 <= 1'h0;
      keyState_161 <= 1'h0;
      keyState_162 <= 1'h0;
      keyState_163 <= 1'h0;
      keyState_164 <= 1'h0;
      keyState_165 <= 1'h0;
      keyState_166 <= 1'h0;
      keyState_167 <= 1'h0;
      keyState_168 <= 1'h0;
      keyState_169 <= 1'h0;
      keyState_170 <= 1'h0;
      keyState_171 <= 1'h0;
      keyState_172 <= 1'h0;
      keyState_173 <= 1'h0;
      keyState_174 <= 1'h0;
      keyState_175 <= 1'h0;
      keyState_176 <= 1'h0;
      keyState_177 <= 1'h0;
      keyState_178 <= 1'h0;
      keyState_179 <= 1'h0;
      keyState_180 <= 1'h0;
      keyState_181 <= 1'h0;
      keyState_182 <= 1'h0;
      keyState_183 <= 1'h0;
      keyState_184 <= 1'h0;
      keyState_185 <= 1'h0;
      keyState_186 <= 1'h0;
      keyState_187 <= 1'h0;
      keyState_188 <= 1'h0;
      keyState_189 <= 1'h0;
      keyState_190 <= 1'h0;
      keyState_191 <= 1'h0;
      keyState_192 <= 1'h0;
      keyState_193 <= 1'h0;
      keyState_194 <= 1'h0;
      keyState_195 <= 1'h0;
      keyState_196 <= 1'h0;
      keyState_197 <= 1'h0;
      keyState_198 <= 1'h0;
      keyState_199 <= 1'h0;
      keyState_200 <= 1'h0;
      keyState_201 <= 1'h0;
      keyState_202 <= 1'h0;
      keyState_203 <= 1'h0;
      keyState_204 <= 1'h0;
      keyState_205 <= 1'h0;
      keyState_206 <= 1'h0;
      keyState_207 <= 1'h0;
      keyState_208 <= 1'h0;
      keyState_209 <= 1'h0;
      keyState_210 <= 1'h0;
      keyState_211 <= 1'h0;
      keyState_212 <= 1'h0;
      keyState_213 <= 1'h0;
      keyState_214 <= 1'h0;
      keyState_215 <= 1'h0;
      keyState_216 <= 1'h0;
      keyState_217 <= 1'h0;
      keyState_218 <= 1'h0;
      keyState_219 <= 1'h0;
      keyState_220 <= 1'h0;
      keyState_221 <= 1'h0;
      keyState_222 <= 1'h0;
      keyState_223 <= 1'h0;
      keyState_224 <= 1'h0;
      keyState_225 <= 1'h0;
      keyState_226 <= 1'h0;
      keyState_227 <= 1'h0;
      keyState_228 <= 1'h0;
      keyState_229 <= 1'h0;
      keyState_230 <= 1'h0;
      keyState_231 <= 1'h0;
      keyState_232 <= 1'h0;
      keyState_233 <= 1'h0;
      keyState_234 <= 1'h0;
      keyState_235 <= 1'h0;
      keyState_236 <= 1'h0;
      keyState_237 <= 1'h0;
      keyState_238 <= 1'h0;
      keyState_239 <= 1'h0;
      keyState_240 <= 1'h0;
      keyState_241 <= 1'h0;
      keyState_242 <= 1'h0;
      keyState_243 <= 1'h0;
      keyState_244 <= 1'h0;
      keyState_245 <= 1'h0;
      keyState_246 <= 1'h0;
      keyState_247 <= 1'h0;
      keyState_248 <= 1'h0;
      keyState_249 <= 1'h0;
      keyState_250 <= 1'h0;
      keyState_251 <= 1'h0;
      keyState_252 <= 1'h0;
      keyState_253 <= 1'h0;
      keyState_254 <= 1'h0;
      keyState_255 <= 1'h0;
      lastCodeReg <= 8'h0;
      lastPressedReg <= 1'h0;
      eventValidReg <= 1'h0;
      state <= 1'h0;
      eventType <= 1'h0;
    end
    else begin
      automatic logic _GEN;
      _GEN = state & _uart_io_valid;
      if (state & _uart_io_valid & _uart_io_data == 8'h0)
        keyState_0 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h1)
        keyState_1 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h2)
        keyState_2 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h3)
        keyState_3 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h4)
        keyState_4 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h5)
        keyState_5 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h6)
        keyState_6 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h7)
        keyState_7 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h8)
        keyState_8 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h9)
        keyState_9 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hA)
        keyState_10 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hB)
        keyState_11 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hC)
        keyState_12 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hD)
        keyState_13 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hE)
        keyState_14 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hF)
        keyState_15 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h10)
        keyState_16 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h11)
        keyState_17 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h12)
        keyState_18 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h13)
        keyState_19 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h14)
        keyState_20 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h15)
        keyState_21 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h16)
        keyState_22 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h17)
        keyState_23 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h18)
        keyState_24 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h19)
        keyState_25 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h1A)
        keyState_26 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h1B)
        keyState_27 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h1C)
        keyState_28 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h1D)
        keyState_29 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h1E)
        keyState_30 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h1F)
        keyState_31 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h20)
        keyState_32 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h21)
        keyState_33 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h22)
        keyState_34 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h23)
        keyState_35 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h24)
        keyState_36 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h25)
        keyState_37 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h26)
        keyState_38 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h27)
        keyState_39 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h28)
        keyState_40 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h29)
        keyState_41 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h2A)
        keyState_42 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h2B)
        keyState_43 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h2C)
        keyState_44 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h2D)
        keyState_45 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h2E)
        keyState_46 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h2F)
        keyState_47 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h30)
        keyState_48 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h31)
        keyState_49 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h32)
        keyState_50 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h33)
        keyState_51 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h34)
        keyState_52 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h35)
        keyState_53 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h36)
        keyState_54 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h37)
        keyState_55 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h38)
        keyState_56 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h39)
        keyState_57 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h3A)
        keyState_58 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h3B)
        keyState_59 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h3C)
        keyState_60 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h3D)
        keyState_61 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h3E)
        keyState_62 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h3F)
        keyState_63 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h40)
        keyState_64 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h41)
        keyState_65 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h42)
        keyState_66 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h43)
        keyState_67 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h44)
        keyState_68 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h45)
        keyState_69 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h46)
        keyState_70 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h47)
        keyState_71 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h48)
        keyState_72 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h49)
        keyState_73 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h4A)
        keyState_74 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h4B)
        keyState_75 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h4C)
        keyState_76 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h4D)
        keyState_77 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h4E)
        keyState_78 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h4F)
        keyState_79 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h50)
        keyState_80 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h51)
        keyState_81 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h52)
        keyState_82 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h53)
        keyState_83 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h54)
        keyState_84 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h55)
        keyState_85 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h56)
        keyState_86 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h57)
        keyState_87 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h58)
        keyState_88 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h59)
        keyState_89 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h5A)
        keyState_90 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h5B)
        keyState_91 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h5C)
        keyState_92 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h5D)
        keyState_93 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h5E)
        keyState_94 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h5F)
        keyState_95 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h60)
        keyState_96 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h61)
        keyState_97 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h62)
        keyState_98 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h63)
        keyState_99 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h64)
        keyState_100 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h65)
        keyState_101 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h66)
        keyState_102 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h67)
        keyState_103 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h68)
        keyState_104 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h69)
        keyState_105 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h6A)
        keyState_106 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h6B)
        keyState_107 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h6C)
        keyState_108 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h6D)
        keyState_109 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h6E)
        keyState_110 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h6F)
        keyState_111 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h70)
        keyState_112 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h71)
        keyState_113 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h72)
        keyState_114 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h73)
        keyState_115 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h74)
        keyState_116 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h75)
        keyState_117 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h76)
        keyState_118 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h77)
        keyState_119 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h78)
        keyState_120 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h79)
        keyState_121 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h7A)
        keyState_122 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h7B)
        keyState_123 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h7C)
        keyState_124 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h7D)
        keyState_125 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h7E)
        keyState_126 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h7F)
        keyState_127 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h80)
        keyState_128 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h81)
        keyState_129 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h82)
        keyState_130 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h83)
        keyState_131 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h84)
        keyState_132 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h85)
        keyState_133 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h86)
        keyState_134 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h87)
        keyState_135 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h88)
        keyState_136 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h89)
        keyState_137 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h8A)
        keyState_138 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h8B)
        keyState_139 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h8C)
        keyState_140 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h8D)
        keyState_141 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h8E)
        keyState_142 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h8F)
        keyState_143 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h90)
        keyState_144 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h91)
        keyState_145 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h92)
        keyState_146 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h93)
        keyState_147 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h94)
        keyState_148 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h95)
        keyState_149 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h96)
        keyState_150 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h97)
        keyState_151 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h98)
        keyState_152 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h99)
        keyState_153 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h9A)
        keyState_154 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h9B)
        keyState_155 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h9C)
        keyState_156 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h9D)
        keyState_157 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h9E)
        keyState_158 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'h9F)
        keyState_159 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hA0)
        keyState_160 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hA1)
        keyState_161 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hA2)
        keyState_162 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hA3)
        keyState_163 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hA4)
        keyState_164 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hA5)
        keyState_165 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hA6)
        keyState_166 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hA7)
        keyState_167 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hA8)
        keyState_168 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hA9)
        keyState_169 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hAA)
        keyState_170 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hAB)
        keyState_171 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hAC)
        keyState_172 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hAD)
        keyState_173 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hAE)
        keyState_174 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hAF)
        keyState_175 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hB0)
        keyState_176 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hB1)
        keyState_177 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hB2)
        keyState_178 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hB3)
        keyState_179 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hB4)
        keyState_180 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hB5)
        keyState_181 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hB6)
        keyState_182 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hB7)
        keyState_183 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hB8)
        keyState_184 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hB9)
        keyState_185 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hBA)
        keyState_186 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hBB)
        keyState_187 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hBC)
        keyState_188 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hBD)
        keyState_189 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hBE)
        keyState_190 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hBF)
        keyState_191 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hC0)
        keyState_192 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hC1)
        keyState_193 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hC2)
        keyState_194 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hC3)
        keyState_195 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hC4)
        keyState_196 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hC5)
        keyState_197 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hC6)
        keyState_198 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hC7)
        keyState_199 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hC8)
        keyState_200 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hC9)
        keyState_201 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hCA)
        keyState_202 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hCB)
        keyState_203 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hCC)
        keyState_204 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hCD)
        keyState_205 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hCE)
        keyState_206 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hCF)
        keyState_207 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hD0)
        keyState_208 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hD1)
        keyState_209 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hD2)
        keyState_210 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hD3)
        keyState_211 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hD4)
        keyState_212 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hD5)
        keyState_213 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hD6)
        keyState_214 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hD7)
        keyState_215 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hD8)
        keyState_216 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hD9)
        keyState_217 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hDA)
        keyState_218 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hDB)
        keyState_219 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hDC)
        keyState_220 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hDD)
        keyState_221 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hDE)
        keyState_222 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hDF)
        keyState_223 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hE0)
        keyState_224 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hE1)
        keyState_225 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hE2)
        keyState_226 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hE3)
        keyState_227 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hE4)
        keyState_228 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hE5)
        keyState_229 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hE6)
        keyState_230 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hE7)
        keyState_231 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hE8)
        keyState_232 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hE9)
        keyState_233 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hEA)
        keyState_234 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hEB)
        keyState_235 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hEC)
        keyState_236 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hED)
        keyState_237 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hEE)
        keyState_238 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hEF)
        keyState_239 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hF0)
        keyState_240 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hF1)
        keyState_241 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hF2)
        keyState_242 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hF3)
        keyState_243 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hF4)
        keyState_244 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hF5)
        keyState_245 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hF6)
        keyState_246 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hF7)
        keyState_247 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hF8)
        keyState_248 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hF9)
        keyState_249 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hFA)
        keyState_250 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hFB)
        keyState_251 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hFC)
        keyState_252 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hFD)
        keyState_253 <= eventType;
      if (state & _uart_io_valid & _uart_io_data == 8'hFE)
        keyState_254 <= eventType;
      if (state & _uart_io_valid & (&_uart_io_data))
        keyState_255 <= eventType;
      if (state & _GEN) begin
        lastCodeReg <= _uart_io_data;
        lastPressedReg <= eventType;
      end
      eventValidReg <= state & _uart_io_valid;
      if (state)
        state <= ~_GEN;
      else
        state <= _uart_io_valid;
      if (~state & _uart_io_valid)
        eventType <= _uart_io_data[0];
    end
  end // always @(posedge)
  UartRx uart (
    .clock    (clock),
    .reset    (reset),
    .io_rxd   (io_rxd),
    .io_data  (_uart_io_data),
    .io_valid (_uart_io_valid)
  );
  assign io_keyDown =
    {keyState_255,
     keyState_254,
     keyState_253,
     keyState_252,
     keyState_251,
     keyState_250,
     keyState_249,
     keyState_248,
     keyState_247,
     keyState_246,
     keyState_245,
     keyState_244,
     keyState_243,
     keyState_242,
     keyState_241,
     keyState_240,
     keyState_239,
     keyState_238,
     keyState_237,
     keyState_236,
     keyState_235,
     keyState_234,
     keyState_233,
     keyState_232,
     keyState_231,
     keyState_230,
     keyState_229,
     keyState_228,
     keyState_227,
     keyState_226,
     keyState_225,
     keyState_224,
     keyState_223,
     keyState_222,
     keyState_221,
     keyState_220,
     keyState_219,
     keyState_218,
     keyState_217,
     keyState_216,
     keyState_215,
     keyState_214,
     keyState_213,
     keyState_212,
     keyState_211,
     keyState_210,
     keyState_209,
     keyState_208,
     keyState_207,
     keyState_206,
     keyState_205,
     keyState_204,
     keyState_203,
     keyState_202,
     keyState_201,
     keyState_200,
     keyState_199,
     keyState_198,
     keyState_197,
     keyState_196,
     keyState_195,
     keyState_194,
     keyState_193,
     keyState_192,
     keyState_191,
     keyState_190,
     keyState_189,
     keyState_188,
     keyState_187,
     keyState_186,
     keyState_185,
     keyState_184,
     keyState_183,
     keyState_182,
     keyState_181,
     keyState_180,
     keyState_179,
     keyState_178,
     keyState_177,
     keyState_176,
     keyState_175,
     keyState_174,
     keyState_173,
     keyState_172,
     keyState_171,
     keyState_170,
     keyState_169,
     keyState_168,
     keyState_167,
     keyState_166,
     keyState_165,
     keyState_164,
     keyState_163,
     keyState_162,
     keyState_161,
     keyState_160,
     keyState_159,
     keyState_158,
     keyState_157,
     keyState_156,
     keyState_155,
     keyState_154,
     keyState_153,
     keyState_152,
     keyState_151,
     keyState_150,
     keyState_149,
     keyState_148,
     keyState_147,
     keyState_146,
     keyState_145,
     keyState_144,
     keyState_143,
     keyState_142,
     keyState_141,
     keyState_140,
     keyState_139,
     keyState_138,
     keyState_137,
     keyState_136,
     keyState_135,
     keyState_134,
     keyState_133,
     keyState_132,
     keyState_131,
     keyState_130,
     keyState_129,
     keyState_128,
     keyState_127,
     keyState_126,
     keyState_125,
     keyState_124,
     keyState_123,
     keyState_122,
     keyState_121,
     keyState_120,
     keyState_119,
     keyState_118,
     keyState_117,
     keyState_116,
     keyState_115,
     keyState_114,
     keyState_113,
     keyState_112,
     keyState_111,
     keyState_110,
     keyState_109,
     keyState_108,
     keyState_107,
     keyState_106,
     keyState_105,
     keyState_104,
     keyState_103,
     keyState_102,
     keyState_101,
     keyState_100,
     keyState_99,
     keyState_98,
     keyState_97,
     keyState_96,
     keyState_95,
     keyState_94,
     keyState_93,
     keyState_92,
     keyState_91,
     keyState_90,
     keyState_89,
     keyState_88,
     keyState_87,
     keyState_86,
     keyState_85,
     keyState_84,
     keyState_83,
     keyState_82,
     keyState_81,
     keyState_80,
     keyState_79,
     keyState_78,
     keyState_77,
     keyState_76,
     keyState_75,
     keyState_74,
     keyState_73,
     keyState_72,
     keyState_71,
     keyState_70,
     keyState_69,
     keyState_68,
     keyState_67,
     keyState_66,
     keyState_65,
     keyState_64,
     keyState_63,
     keyState_62,
     keyState_61,
     keyState_60,
     keyState_59,
     keyState_58,
     keyState_57,
     keyState_56,
     keyState_55,
     keyState_54,
     keyState_53,
     keyState_52,
     keyState_51,
     keyState_50,
     keyState_49,
     keyState_48,
     keyState_47,
     keyState_46,
     keyState_45,
     keyState_44,
     keyState_43,
     keyState_42,
     keyState_41,
     keyState_40,
     keyState_39,
     keyState_38,
     keyState_37,
     keyState_36,
     keyState_35,
     keyState_34,
     keyState_33,
     keyState_32,
     keyState_31,
     keyState_30,
     keyState_29,
     keyState_28,
     keyState_27,
     keyState_26,
     keyState_25,
     keyState_24,
     keyState_23,
     keyState_22,
     keyState_21,
     keyState_20,
     keyState_19,
     keyState_18,
     keyState_17,
     keyState_16,
     keyState_15,
     keyState_14,
     keyState_13,
     keyState_12,
     keyState_11,
     keyState_10,
     keyState_9,
     keyState_8,
     keyState_7,
     keyState_6,
     keyState_5,
     keyState_4,
     keyState_3,
     keyState_2,
     keyState_1,
     keyState_0};
  assign io_lastCode = lastCodeReg;
  assign io_lastPressed = lastPressedReg;
  assign io_eventValid = eventValidReg;
  assign io_numDown = {1'h0, _io_numDown_T_510} + {1'h0, _io_numDown_T_764};
endmodule

