// Generated by CIRCT firtool-1.128.0

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_
module UartRx(
  input        clock,
               reset,
               io_rxd,
  output [7:0] io_data,
  output       io_valid
);

  reg [15:0] counter;
  reg [3:0]  bitIdx;
  reg [7:0]  shiftReg;
  reg [7:0]  dataReg;
  reg        validReg;
  reg [1:0]  state;
  reg        rxSync_REG;
  reg        rxSync;
  `ifndef SYNTHESIS
    always @(posedge clock) begin
      if ((`PRINTF_COND_) & validReg & ~reset)
        $fwrite(32'h80000002, "Byte Recieved: %d\n", dataReg);
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin
    if (reset) begin
      counter <= 16'h0;
      bitIdx <= 4'h0;
      shiftReg <= 8'h0;
      dataReg <= 8'h0;
      validReg <= 1'h0;
      state <= 2'h0;
      rxSync_REG <= 1'h1;
      rxSync <= 1'h1;
    end
    else begin
      automatic logic             _GEN = state == 2'h0;
      automatic logic             _GEN_0;
      automatic logic             _GEN_1;
      automatic logic             _GEN_2 = state == 2'h2;
      automatic logic             _GEN_3;
      automatic logic             _GEN_4;
      automatic logic             _GEN_5;
      automatic logic [3:0][15:0] _GEN_6;
      automatic logic [3:0][1:0]  _GEN_7;
      _GEN_0 = state == 2'h1;
      _GEN_1 = counter == 16'h0;
      _GEN_3 = _GEN_2 & _GEN_1;
      _GEN_4 = _GEN | _GEN_0 | _GEN_2;
      _GEN_5 = (&state) & _GEN_1;
      _GEN_6 =
        {{~(&state) | _GEN_1 ? counter : counter - 16'h1},
         {_GEN_1 ? 16'h1A : counter - 16'h1},
         {_GEN_1 ? (rxSync ? counter : 16'h1A) : counter - 16'h1},
         {rxSync ? counter : 16'hC}};
      counter <= _GEN_6[state];
      if (~_GEN) begin
        if (_GEN_0) begin
          if (_GEN_1 & ~rxSync)
            bitIdx <= 4'h0;
        end
        else if (_GEN_3)
          bitIdx <= bitIdx + 4'h1;
      end
      if (_GEN | _GEN_0 | ~_GEN_3) begin
      end
      else
        shiftReg <= {rxSync, shiftReg[7:1]};
      if (_GEN_4 | ~((&state) & _GEN_1 & rxSync)) begin
      end
      else
        dataReg <= shiftReg;
      validReg <= ~_GEN_4 & _GEN_5 & rxSync;
      _GEN_7 =
        {{_GEN_5 ? 2'h0 : state},
         {_GEN_1 & bitIdx == 4'h7 ? 2'h3 : state},
         {_GEN_1 ? {~rxSync, 1'h0} : state},
         {rxSync ? state : 2'h1}};
      state <= _GEN_7[state];
      rxSync_REG <= io_rxd;
      rxSync <= rxSync_REG;
    end
  end // always @(posedge)
  assign io_data = dataReg;
  assign io_valid = validReg;
endmodule

