// Generated by CIRCT firtool-1.128.0
module DCacheQueue(
  input         clock,
                reset,
  input  [31:0] io_req_req_address,
                io_req_req_write_data,
  input  [2:0]  io_req_req_op,
  input         io_req_req_read,
                io_req_req_write,
  input  [6:0]  io_req_rd,
  input  [3:0]  io_req_lane,
  input         io_req_wen,
                io_start,
  output        io_ready,
                io_valid,
  output [31:0] io_data,
  output [6:0]  io_rd,
  output [3:0]  io_lane,
  output        io_wen,
  output [31:0] io_dcache_req_address,
                io_dcache_req_write_data,
  output [2:0]  io_dcache_req_op,
  output        io_dcache_req_write,
                io_dcache_start,
  input         io_dcache_ready,
                io_dcache_valid,
  input  [31:0] io_dcache_data
);

  wire       _deq_q_io_deq_valid;
  wire [6:0] _deq_q_io_deq_bits_rd;
  wire [3:0] _deq_q_io_deq_bits_lane;
  wire       _deq_q_io_deq_bits_wen;
  reg  [6:0] current_req_rd;
  reg  [3:0] current_req_lane;
  reg        current_req_wen;
  wire       io_dcache_start_0 = io_dcache_ready & _deq_q_io_deq_valid;
  always @(posedge clock) begin
    if (reset) begin
      current_req_rd <= 7'h0;
      current_req_lane <= 4'h0;
      current_req_wen <= 1'h0;
    end
    else if (io_dcache_start_0) begin
      current_req_rd <= _deq_q_io_deq_bits_rd;
      current_req_lane <= _deq_q_io_deq_bits_lane;
      current_req_wen <= _deq_q_io_deq_bits_wen;
    end
  end // always @(posedge)
  Queue64_MemReqWrapped deq_q (
    .clock                      (clock),
    .reset                      (reset),
    .io_enq_ready               (io_ready),
    .io_enq_valid               (io_start),
    .io_enq_bits_req_address    (io_req_req_address),
    .io_enq_bits_req_write_data (io_req_req_write_data),
    .io_enq_bits_req_op         (io_req_req_op),
    .io_enq_bits_req_read       (io_req_req_read),
    .io_enq_bits_req_write      (io_req_req_write),
    .io_enq_bits_rd             (io_req_rd),
    .io_enq_bits_lane           (io_req_lane),
    .io_enq_bits_wen            (io_req_wen),
    .io_deq_ready               (io_dcache_start_0),
    .io_deq_valid               (_deq_q_io_deq_valid),
    .io_deq_bits_req_address    (io_dcache_req_address),
    .io_deq_bits_req_write_data (io_dcache_req_write_data),
    .io_deq_bits_req_op         (io_dcache_req_op),
    .io_deq_bits_req_write      (io_dcache_req_write),
    .io_deq_bits_rd             (_deq_q_io_deq_bits_rd),
    .io_deq_bits_lane           (_deq_q_io_deq_bits_lane),
    .io_deq_bits_wen            (_deq_q_io_deq_bits_wen)
  );
  assign io_valid = io_dcache_valid;
  assign io_data = io_dcache_valid ? io_dcache_data : 32'h0;
  assign io_rd = io_dcache_valid ? current_req_rd : 7'h0;
  assign io_lane = io_dcache_valid ? current_req_lane : 4'h0;
  assign io_wen = io_dcache_valid & current_req_wen;
  assign io_dcache_start = io_dcache_start_0;
endmodule

