// Generated by CIRCT firtool-1.128.0

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_
module DCache(
  input          clock,
                 reset,
  input  [31:0]  io_req_address,
                 io_req_write_data,
  input  [2:0]   io_req_op,
  input          io_req_write,
                 io_start,
  output         io_ready,
                 io_done,
                 io_miss,
  output [31:0]  io_data,
  output         io_wb,
  output [511:0] io_wb_data,
  output [31:0]  io_wb_addr,
  input  [511:0] io_line_result,
  output [31:0]  io_line_addr,
  input          io_line_valid
);

  wire [511:0]      _data_array_ext_R0_data;
  wire [19:0]       _meta_array_ext_R0_data;
  reg  [1:0]        state;
  reg  [31:0]       current_mem_req_address;
  reg  [31:0]       current_mem_req_write_data;
  reg  [2:0]        current_mem_req_op;
  reg               current_mem_req_write;
  wire [31:0]       lookup_address = io_start ? io_req_address : current_mem_req_address;
  reg  [31:0]       lookup_address_reg;
  wire              _io_ready_T_1 = state == 2'h1;
  wire              read_enable = ~(|state) | _io_ready_T_1 | (&state);
  reg  [511:0]      wb_data_reg;
  reg  [31:0]       wb_addr_reg;
  reg               valid_cleared;
  wire              _hit_T = lookup_address_reg[31:14] == _meta_array_ext_R0_data[17:0];
  wire              _GEN = state == 2'h1;
  wire              _GEN_0 = _hit_T & _meta_array_ext_R0_data[19];
  wire [15:0][31:0] _GEN_1 =
    {{_data_array_ext_R0_data[511:480]},
     {_data_array_ext_R0_data[479:448]},
     {_data_array_ext_R0_data[447:416]},
     {_data_array_ext_R0_data[415:384]},
     {_data_array_ext_R0_data[383:352]},
     {_data_array_ext_R0_data[351:320]},
     {_data_array_ext_R0_data[319:288]},
     {_data_array_ext_R0_data[287:256]},
     {_data_array_ext_R0_data[255:224]},
     {_data_array_ext_R0_data[223:192]},
     {_data_array_ext_R0_data[191:160]},
     {_data_array_ext_R0_data[159:128]},
     {_data_array_ext_R0_data[127:96]},
     {_data_array_ext_R0_data[95:64]},
     {_data_array_ext_R0_data[63:32]},
     {_data_array_ext_R0_data[31:0]}};
  wire [31:0]       _GEN_2 = _GEN_1[lookup_address_reg[5:2]];
  wire              _GEN_3 = current_mem_req_op == 3'h5;
  wire              _GEN_4 = current_mem_req_op == 3'h6;
  wire              _GEN_5 = lookup_address_reg[1:0] == 2'h1;
  wire              _GEN_6 = lookup_address_reg[1:0] == 2'h2;
  wire [31:0]       updated_word =
    _GEN_3
      ? current_mem_req_write_data
      : _GEN_4
          ? ((|(lookup_address_reg[1:0]))
               ? {current_mem_req_write_data[15:0], _GEN_2[15:0]}
               : {_GEN_2[31:16], current_mem_req_write_data[15:0]})
          : (&current_mem_req_op)
              ? ((|(lookup_address_reg[1:0]))
                   ? (_GEN_5
                        ? {_GEN_2[31:16], current_mem_req_write_data[7:0], _GEN_2[7:0]}
                        : _GEN_6
                            ? {_GEN_2[31:24],
                               current_mem_req_write_data[7:0],
                               _GEN_2[15:0]}
                            : {current_mem_req_write_data[7:0], _GEN_2[23:0]})
                   : {_GEN_2[31:8], current_mem_req_write_data[7:0]})
              : _GEN_2;
  wire              _GEN_7 = _GEN_0 & current_mem_req_write;
  wire [3:0][31:0]  _GEN_8 =
    {{{{24{_GEN_2[31]}}, _GEN_2[31:24]}},
     {{{24{_GEN_2[23]}}, _GEN_2[23:16]}},
     {{{24{_GEN_2[15]}}, _GEN_2[15:8]}},
     {32'h0}};
  wire [3:0][31:0]  _GEN_9 =
    {{{24'h0, _GEN_2[31:24]}},
     {{24'h0, _GEN_2[23:16]}},
     {{24'h0, _GEN_2[15:8]}},
     {32'h0}};
  wire [7:0][31:0]  _GEN_10 =
    {{32'h0},
     {32'h0},
     {32'h0},
     {{16'h0, (|(lookup_address_reg[1:0])) ? _GEN_2[31:16] : _GEN_2[15:0]}},
     {(|(lookup_address_reg[1:0]))
        ? _GEN_9[lookup_address_reg[1:0]]
        : {24'h0, _GEN_2[7:0]}},
     {(|(lookup_address_reg[1:0]))
        ? _GEN_8[lookup_address_reg[1:0]]
        : {{24{_GEN_2[7]}}, _GEN_2[7:0]}},
     {(|(lookup_address_reg[1:0]))
        ? {{16{_GEN_2[31]}}, _GEN_2[31:16]}
        : {{16{_GEN_2[15]}}, _GEN_2[15:0]}},
     {_GEN_2}};
  wire              _GEN_11 = state == 2'h2;
  wire [15:0][31:0] _GEN_12 =
    {{io_line_result[511:480]},
     {io_line_result[479:448]},
     {io_line_result[447:416]},
     {io_line_result[415:384]},
     {io_line_result[383:352]},
     {io_line_result[351:320]},
     {io_line_result[319:288]},
     {io_line_result[287:256]},
     {io_line_result[255:224]},
     {io_line_result[223:192]},
     {io_line_result[191:160]},
     {io_line_result[159:128]},
     {io_line_result[127:96]},
     {io_line_result[95:64]},
     {io_line_result[63:32]},
     {io_line_result[31:0]}};
  wire [31:0]       _GEN_13 = _GEN_12[lookup_address_reg[5:2]];
  wire [31:0]       updated_word_1 =
    _GEN_3
      ? current_mem_req_write_data
      : _GEN_4
          ? ((|(lookup_address_reg[1:0]))
               ? {current_mem_req_write_data[15:0], _GEN_13[15:0]}
               : {_GEN_13[31:16], current_mem_req_write_data[15:0]})
          : (&current_mem_req_op)
              ? ((|(lookup_address_reg[1:0]))
                   ? (_GEN_5
                        ? {_GEN_13[31:16], current_mem_req_write_data[7:0], _GEN_13[7:0]}
                        : _GEN_6
                            ? {_GEN_13[31:24],
                               current_mem_req_write_data[7:0],
                               _GEN_13[15:0]}
                            : {current_mem_req_write_data[7:0], _GEN_13[23:0]})
                   : {_GEN_13[31:8], current_mem_req_write_data[7:0]})
              : _GEN_13;
  wire              _GEN_14 = ~valid_cleared | ~io_line_valid;
  wire              _GEN_15 = ~_GEN_11 & (&state) & ~_GEN_14;
  wire              _GEN_16 = _GEN ? _GEN_0 & current_mem_req_write : _GEN_15;
  wire              _GEN_17 = _GEN_11 | ~(&state) | _GEN_14;
  wire [15:0][31:0] _GEN_18 =
    {{io_line_result[511:480]},
     {io_line_result[479:448]},
     {io_line_result[447:416]},
     {io_line_result[415:384]},
     {io_line_result[383:352]},
     {io_line_result[351:320]},
     {io_line_result[319:288]},
     {io_line_result[287:256]},
     {io_line_result[255:224]},
     {io_line_result[223:192]},
     {io_line_result[191:160]},
     {io_line_result[159:128]},
     {io_line_result[127:96]},
     {io_line_result[95:64]},
     {io_line_result[63:32]},
     {io_line_result[31:0]}};
  wire [31:0]       _GEN_19 = _GEN_18[lookup_address_reg[5:2]];
  wire [3:0][31:0]  _GEN_20 =
    {{{{24{_GEN_19[31]}}, _GEN_19[31:24]}},
     {{{24{_GEN_19[23]}}, _GEN_19[23:16]}},
     {{{24{_GEN_19[15]}}, _GEN_19[15:8]}},
     {32'h0}};
  wire [3:0][31:0]  _GEN_21 =
    {{{24'h0, _GEN_19[31:24]}},
     {{24'h0, _GEN_19[23:16]}},
     {{24'h0, _GEN_19[15:8]}},
     {32'h0}};
  wire [7:0][31:0]  _GEN_22 =
    {{32'h0},
     {32'h0},
     {32'h0},
     {{16'h0, (|(lookup_address_reg[1:0])) ? _GEN_19[31:16] : _GEN_19[15:0]}},
     {(|(lookup_address_reg[1:0]))
        ? _GEN_21[lookup_address_reg[1:0]]
        : {24'h0, _GEN_19[7:0]}},
     {(|(lookup_address_reg[1:0]))
        ? _GEN_20[lookup_address_reg[1:0]]
        : {{24{_GEN_19[7]}}, _GEN_19[7:0]}},
     {(|(lookup_address_reg[1:0]))
        ? {{16{_GEN_19[31]}}, _GEN_19[31:16]}
        : {{16{_GEN_19[15]}}, _GEN_19[15:0]}},
     {_GEN_19}};
  `ifndef SYNTHESIS
    always @(posedge clock) begin
      automatic logic [31:0] _GEN_23;
      _GEN_23 = {_meta_array_ext_R0_data[17:0], current_mem_req_address[13:6], 6'h0};
      if ((`PRINTF_COND_) & (|state) & _GEN & ~_GEN_0
          & (&(_meta_array_ext_R0_data[19:18])) & _GEN_23 < 32'hE48000 & ~reset)
        $fwrite(32'h80000002,
                "WBTRAP wb_addr=%x victim_tag=%x idx=%x req_addr=%x req_write=%d req_data=%x line=%x\n",
                _GEN_23, _meta_array_ext_R0_data[17:0], current_mem_req_address[13:6],
                current_mem_req_address, current_mem_req_write,
                current_mem_req_write_data, _data_array_ext_R0_data);
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin
    if (reset) begin
      state <= 2'h0;
      current_mem_req_address <= 32'h0;
      current_mem_req_write_data <= 32'h0;
      current_mem_req_op <= 3'h0;
      current_mem_req_write <= 1'h0;
      wb_data_reg <= 512'h0;
      wb_addr_reg <= 32'h0;
      valid_cleared <= 1'h1;
    end
    else begin
      if (|state) begin
        if (_GEN) begin
          state <=
            _GEN_0 ? {1'h0, io_start} : {1'h1, ~(&(_meta_array_ext_R0_data[19:18]))};
          if (~_GEN_0)
            valid_cleared <= ~(&(_meta_array_ext_R0_data[19:18]));
        end
        else begin
          if (_GEN_11) begin
            if (io_line_valid)
              state <= 2'h3;
          end
          else if (~(&state) | _GEN_14) begin
          end
          else
            state <= 2'h0;
          valid_cleared <=
            ~_GEN_11 & (&state) & ~valid_cleared & ~io_line_valid | valid_cleared;
        end
      end
      else begin
        if (io_start)
          state <= 2'h1;
        valid_cleared <= io_start | valid_cleared;
      end
      if ((~(|state) | _GEN & _GEN_0) & io_start) begin
        current_mem_req_address <= io_req_address;
        current_mem_req_write_data <= io_req_write_data;
        current_mem_req_op <= io_req_op;
        current_mem_req_write <= io_req_write;
      end
      if (~(|state) | ~_GEN | _GEN_0 | ~(&(_meta_array_ext_R0_data[19:18]))) begin
      end
      else begin
        wb_data_reg <= _data_array_ext_R0_data;
        wb_addr_reg <=
          {_meta_array_ext_R0_data[17:0], current_mem_req_address[13:6], 6'h0};
      end
    end
    lookup_address_reg <= lookup_address;
  end // always @(posedge)
  meta_array_256x20 meta_array_ext (
    .R0_addr (lookup_address[13:6]),
    .R0_en   (read_enable),
    .R0_clk  (clock),
    .R0_data (_meta_array_ext_R0_data),
    .W0_addr (current_mem_req_address[13:6]),
    .W0_en   ((|state) & _GEN_16),
    .W0_clk  (clock),
    .W0_data
      ((|state)
         ? (_GEN
              ? (_GEN_7 ? {2'h3, current_mem_req_address[31:14]} : 20'h0)
              : _GEN_17
                  ? 20'h0
                  : current_mem_req_write
                      ? {2'h3, current_mem_req_address[31:14]}
                      : {2'h2, current_mem_req_address[31:14]})
         : 20'h0)
  );
  data_array_256x512 data_array_ext (
    .R0_addr (lookup_address[13:6]),
    .R0_en   (read_enable),
    .R0_clk  (clock),
    .R0_data (_data_array_ext_R0_data),
    .W0_addr (current_mem_req_address[13:6]),
    .W0_en   ((|state) & _GEN_16),
    .W0_clk  (clock),
    .W0_data
      ((|state)
         ? (_GEN
              ? (_GEN_7
                   ? {(&(lookup_address_reg[5:2]))
                        ? updated_word
                        : _data_array_ext_R0_data[511:480],
                      lookup_address_reg[5:2] == 4'hE
                        ? updated_word
                        : _data_array_ext_R0_data[479:448],
                      lookup_address_reg[5:2] == 4'hD
                        ? updated_word
                        : _data_array_ext_R0_data[447:416],
                      lookup_address_reg[5:2] == 4'hC
                        ? updated_word
                        : _data_array_ext_R0_data[415:384],
                      lookup_address_reg[5:2] == 4'hB
                        ? updated_word
                        : _data_array_ext_R0_data[383:352],
                      lookup_address_reg[5:2] == 4'hA
                        ? updated_word
                        : _data_array_ext_R0_data[351:320],
                      lookup_address_reg[5:2] == 4'h9
                        ? updated_word
                        : _data_array_ext_R0_data[319:288],
                      lookup_address_reg[5:2] == 4'h8
                        ? updated_word
                        : _data_array_ext_R0_data[287:256],
                      lookup_address_reg[5:2] == 4'h7
                        ? updated_word
                        : _data_array_ext_R0_data[255:224],
                      lookup_address_reg[5:2] == 4'h6
                        ? updated_word
                        : _data_array_ext_R0_data[223:192],
                      lookup_address_reg[5:2] == 4'h5
                        ? updated_word
                        : _data_array_ext_R0_data[191:160],
                      lookup_address_reg[5:2] == 4'h4
                        ? updated_word
                        : _data_array_ext_R0_data[159:128],
                      lookup_address_reg[5:2] == 4'h3
                        ? updated_word
                        : _data_array_ext_R0_data[127:96],
                      lookup_address_reg[5:2] == 4'h2
                        ? updated_word
                        : _data_array_ext_R0_data[95:64],
                      lookup_address_reg[5:2] == 4'h1
                        ? updated_word
                        : _data_array_ext_R0_data[63:32],
                      (|(lookup_address_reg[5:2]))
                        ? _data_array_ext_R0_data[31:0]
                        : updated_word}
                   : 512'h0)
              : _GEN_17
                  ? 512'h0
                  : current_mem_req_write
                      ? {(&(lookup_address_reg[5:2]))
                           ? updated_word_1
                           : io_line_result[511:480],
                         lookup_address_reg[5:2] == 4'hE
                           ? updated_word_1
                           : io_line_result[479:448],
                         lookup_address_reg[5:2] == 4'hD
                           ? updated_word_1
                           : io_line_result[447:416],
                         lookup_address_reg[5:2] == 4'hC
                           ? updated_word_1
                           : io_line_result[415:384],
                         lookup_address_reg[5:2] == 4'hB
                           ? updated_word_1
                           : io_line_result[383:352],
                         lookup_address_reg[5:2] == 4'hA
                           ? updated_word_1
                           : io_line_result[351:320],
                         lookup_address_reg[5:2] == 4'h9
                           ? updated_word_1
                           : io_line_result[319:288],
                         lookup_address_reg[5:2] == 4'h8
                           ? updated_word_1
                           : io_line_result[287:256],
                         lookup_address_reg[5:2] == 4'h7
                           ? updated_word_1
                           : io_line_result[255:224],
                         lookup_address_reg[5:2] == 4'h6
                           ? updated_word_1
                           : io_line_result[223:192],
                         lookup_address_reg[5:2] == 4'h5
                           ? updated_word_1
                           : io_line_result[191:160],
                         lookup_address_reg[5:2] == 4'h4
                           ? updated_word_1
                           : io_line_result[159:128],
                         lookup_address_reg[5:2] == 4'h3
                           ? updated_word_1
                           : io_line_result[127:96],
                         lookup_address_reg[5:2] == 4'h2
                           ? updated_word_1
                           : io_line_result[95:64],
                         lookup_address_reg[5:2] == 4'h1
                           ? updated_word_1
                           : io_line_result[63:32],
                         (|(lookup_address_reg[5:2]))
                           ? io_line_result[31:0]
                           : updated_word_1}
                      : io_line_result)
         : 512'h0)
  );
  assign io_ready =
    ~(|state) | _io_ready_T_1 & _hit_T & _meta_array_ext_R0_data[19]
    & ~current_mem_req_write;
  assign io_done = (|state) & (_GEN ? _GEN_0 : _GEN_15);
  assign io_miss =
    ~(~(|state) | _GEN | _GEN_11) & (&state) & (~valid_cleared | ~io_line_valid);
  assign io_data =
    (|state)
      ? (_GEN
           ? (~_GEN_0 | current_mem_req_write ? 32'h0 : _GEN_10[current_mem_req_op])
           : _GEN_11 | ~(&state) | ~valid_cleared | ~io_line_valid | current_mem_req_write
               ? 32'h0
               : _GEN_22[current_mem_req_op])
      : 32'h0;
  assign io_wb = state == 2'h2;
  assign io_wb_data = wb_data_reg;
  assign io_wb_addr = wb_addr_reg;
  assign io_line_addr = {current_mem_req_address[31:6], 6'h0};
endmodule

