// Generated by CIRCT firtool-1.128.0
module Div(
  input         clock,
                reset,
  input  [2:0]  io_func3,
  input  [31:0] io_a,
                io_b,
  output [31:0] io_output,
  output        io_ready,
                io_valid,
  input         io_start
);

  reg  [1:0]  state;
  reg  [2:0]  func3;
  reg  [31:0] a;
  reg  [31:0] b;
  reg         divNeg;
  reg         outNeg;
  reg  [5:0]  counter;
  reg  [32:0] r;
  reg         divByZeroCase;
  reg         overflowCase;
  reg  [31:0] orga;
  wire        _GEN = state == 2'h1;
  wire        _GEN_0 = state == 2'h2;
  wire        isDivOp = func3 == 3'h4 | func3 == 3'h5;
  wire        _GEN_1 = ~(|state) | _GEN;
  always @(posedge clock) begin
    if (reset) begin
      state <= 2'h0;
      func3 <= 3'h0;
      a <= 32'h0;
      b <= 32'h0;
      divNeg <= 1'h0;
      outNeg <= 1'h0;
      counter <= 6'h0;
      r <= 33'h0;
      divByZeroCase <= 1'h0;
      overflowCase <= 1'h0;
      orga <= 32'h0;
    end
    else begin
      automatic logic _GEN_2;
      _GEN_2 = io_func3 == 3'h4 | io_func3 == 3'h6;
      if (|state) begin
        if (_GEN) begin
          automatic logic [32:0] _GEN_3 = {r[31:0], a[31]};
          automatic logic [32:0] _GEN_4 = {1'h0, b};
          automatic logic [32:0] nextR =
            $signed(r) > -33'sh1 ? _GEN_3 - _GEN_4 : _GEN_3 + _GEN_4;
          automatic logic        _GEN_5 = counter == 6'h1;
          if (_GEN_5)
            state <= 2'h2;
          a <= {a[30:0], ~(nextR[32])};
          counter <= counter - 6'h1;
          r <= _GEN_5 & nextR[32] ? nextR + _GEN_4 : nextR;
        end
        else if (_GEN_0)
          state <= 2'h0;
      end
      else if (io_start) begin
        state <= 2'h1;
        a <= _GEN_2 & io_a[31] ? ~io_a + 32'h1 : io_a;
        counter <= 6'h20;
        r <= 33'h0;
      end
      if (~(|state) & io_start) begin
        func3 <= io_func3;
        b <= _GEN_2 & io_b[31] ? ~io_b + 32'h1 : io_b;
        divNeg <= _GEN_2 & io_a[31];
        outNeg <= _GEN_2 & (io_a[31] ^ io_b[31]);
        divByZeroCase <= io_b == 32'h0;
        overflowCase <= _GEN_2 & io_a == 32'h80000000 & (&io_b);
        orga <= io_a;
      end
    end
  end // always @(posedge)
  assign io_output =
    _GEN_1 | ~_GEN_0
      ? 32'h0
      : divByZeroCase
          ? (isDivOp ? 32'hFFFFFFFF : orga)
          : overflowCase
              ? {isDivOp, 31'h0}
              : isDivOp
                  ? (outNeg ? ~a + 32'h1 : a)
                  : func3 == 3'h6 | (&func3)
                      ? (divNeg ? ~(r[31:0]) + 32'h1 : r[31:0])
                      : 32'h0;
  assign io_ready = ~(|state);
  assign io_valid = ~_GEN_1 & _GEN_0;
endmodule

