// Generated by CIRCT firtool-1.128.0
module Execute(
  input         clock,
                reset,
                io_instruction_valid,
  input  [31:0] io_instruction_bits_rs1_val_0,
                io_instruction_bits_rs1_val_1,
                io_instruction_bits_rs1_val_2,
                io_instruction_bits_rs1_val_3,
                io_instruction_bits_rs1_val_4,
                io_instruction_bits_rs1_val_5,
                io_instruction_bits_rs1_val_6,
                io_instruction_bits_rs1_val_7,
                io_instruction_bits_rs1_val_8,
                io_instruction_bits_rs1_val_9,
                io_instruction_bits_rs1_val_10,
                io_instruction_bits_rs1_val_11,
                io_instruction_bits_rs1_val_12,
                io_instruction_bits_rs1_val_13,
                io_instruction_bits_rs1_val_14,
                io_instruction_bits_rs1_val_15,
                io_instruction_bits_rs2_val_0,
                io_instruction_bits_rs2_val_1,
                io_instruction_bits_rs2_val_2,
                io_instruction_bits_rs2_val_3,
                io_instruction_bits_rs2_val_4,
                io_instruction_bits_rs2_val_5,
                io_instruction_bits_rs2_val_6,
                io_instruction_bits_rs2_val_7,
                io_instruction_bits_rs2_val_8,
                io_instruction_bits_rs2_val_9,
                io_instruction_bits_rs2_val_10,
                io_instruction_bits_rs2_val_11,
                io_instruction_bits_rs2_val_12,
                io_instruction_bits_rs2_val_13,
                io_instruction_bits_rs2_val_14,
                io_instruction_bits_rs2_val_15,
  input  [6:0]  io_instruction_bits_rd,
  input  [31:0] io_instruction_bits_immediate,
  input  [6:0]  io_instruction_bits_opcode,
  input  [2:0]  io_instruction_bits_func3,
  input  [6:0]  io_instruction_bits_func7,
  input  [31:0] io_instruction_bits_pc,
  input  [1:0]  io_instruction_bits_warp,
  output        io_next_instruction_valid,
  output [6:0]  io_next_instruction_bits_rd,
  output [31:0] io_next_instruction_bits_rd_val_0,
                io_next_instruction_bits_rd_val_1,
                io_next_instruction_bits_rd_val_2,
                io_next_instruction_bits_rd_val_3,
                io_next_instruction_bits_rd_val_4,
                io_next_instruction_bits_rd_val_5,
                io_next_instruction_bits_rd_val_6,
                io_next_instruction_bits_rd_val_7,
                io_next_instruction_bits_rd_val_8,
                io_next_instruction_bits_rd_val_9,
                io_next_instruction_bits_rd_val_10,
                io_next_instruction_bits_rd_val_11,
                io_next_instruction_bits_rd_val_12,
                io_next_instruction_bits_rd_val_13,
                io_next_instruction_bits_rd_val_14,
                io_next_instruction_bits_rd_val_15,
  output [15:0] io_next_instruction_bits_mask,
  output        io_next_instruction_bits_rd_wen,
  input         io_flush,
  output [31:0] io_pc_redirect_bits,
  input         io_lsu_req_ready,
  output        io_lsu_req_valid,
  output [31:0] io_lsu_req_bits_base_0,
                io_lsu_req_bits_base_1,
                io_lsu_req_bits_base_2,
                io_lsu_req_bits_base_3,
                io_lsu_req_bits_base_4,
                io_lsu_req_bits_base_5,
                io_lsu_req_bits_base_6,
                io_lsu_req_bits_base_7,
                io_lsu_req_bits_base_8,
                io_lsu_req_bits_base_9,
                io_lsu_req_bits_base_10,
                io_lsu_req_bits_base_11,
                io_lsu_req_bits_base_12,
                io_lsu_req_bits_base_13,
                io_lsu_req_bits_base_14,
                io_lsu_req_bits_base_15,
                io_lsu_req_bits_wdata_0,
                io_lsu_req_bits_wdata_1,
                io_lsu_req_bits_wdata_2,
                io_lsu_req_bits_wdata_3,
                io_lsu_req_bits_wdata_4,
                io_lsu_req_bits_wdata_5,
                io_lsu_req_bits_wdata_6,
                io_lsu_req_bits_wdata_7,
                io_lsu_req_bits_wdata_8,
                io_lsu_req_bits_wdata_9,
                io_lsu_req_bits_wdata_10,
                io_lsu_req_bits_wdata_11,
                io_lsu_req_bits_wdata_12,
                io_lsu_req_bits_wdata_13,
                io_lsu_req_bits_wdata_14,
                io_lsu_req_bits_wdata_15,
                io_lsu_req_bits_imm,
  output [15:0] io_lsu_req_bits_mask,
  output [6:0]  io_lsu_req_bits_rd,
  output [2:0]  io_lsu_req_bits_func3,
  output        io_lsu_req_bits_write,
                io_memory_stall,
                io_jump_flush,
                io_mem_issue,
  output [6:0]  io_mem_issue_rd,
  output [4:0]  io_mem_issue_count,
  output        io_warp_swap,
                io_warp_terminate,
                io_mark,
  output [31:0] io_mark_pc,
  output [1:0]  io_mark_warp,
  input  [31:0] io_warp_ids_0,
                io_warp_ids_1,
                io_warp_ids_2,
                io_warp_ids_3,
  output        io_spawn,
  output [31:0] io_spawn_count,
                io_spawn_pc_in,
  input         io_allocate_warp,
  input  [1:0]  io_allocate_id,
  output        io_barrier,
  output [31:0] io_barrier_target
);

  wire [31:0]       _malus_15_io_output;
  wire              _malus_15_io_ready;
  wire              _malus_15_io_valid;
  wire [31:0]       _malus_14_io_output;
  wire              _malus_14_io_ready;
  wire              _malus_14_io_valid;
  wire [31:0]       _malus_13_io_output;
  wire              _malus_13_io_ready;
  wire              _malus_13_io_valid;
  wire [31:0]       _malus_12_io_output;
  wire              _malus_12_io_ready;
  wire              _malus_12_io_valid;
  wire [31:0]       _malus_11_io_output;
  wire              _malus_11_io_ready;
  wire              _malus_11_io_valid;
  wire [31:0]       _malus_10_io_output;
  wire              _malus_10_io_ready;
  wire              _malus_10_io_valid;
  wire [31:0]       _malus_9_io_output;
  wire              _malus_9_io_ready;
  wire              _malus_9_io_valid;
  wire [31:0]       _malus_8_io_output;
  wire              _malus_8_io_ready;
  wire              _malus_8_io_valid;
  wire [31:0]       _malus_7_io_output;
  wire              _malus_7_io_ready;
  wire              _malus_7_io_valid;
  wire [31:0]       _malus_6_io_output;
  wire              _malus_6_io_ready;
  wire              _malus_6_io_valid;
  wire [31:0]       _malus_5_io_output;
  wire              _malus_5_io_ready;
  wire              _malus_5_io_valid;
  wire [31:0]       _malus_4_io_output;
  wire              _malus_4_io_ready;
  wire              _malus_4_io_valid;
  wire [31:0]       _malus_3_io_output;
  wire              _malus_3_io_ready;
  wire              _malus_3_io_valid;
  wire [31:0]       _malus_2_io_output;
  wire              _malus_2_io_ready;
  wire              _malus_2_io_valid;
  wire [31:0]       _malus_1_io_output;
  wire              _malus_1_io_ready;
  wire              _malus_1_io_valid;
  wire [31:0]       _malus_0_io_output;
  wire              _malus_0_io_ready;
  wire              _malus_0_io_valid;
  wire [31:0]       _alus_15_io_output;
  wire [31:0]       _alus_14_io_output;
  wire [31:0]       _alus_13_io_output;
  wire [31:0]       _alus_12_io_output;
  wire [31:0]       _alus_11_io_output;
  wire [31:0]       _alus_10_io_output;
  wire [31:0]       _alus_9_io_output;
  wire [31:0]       _alus_8_io_output;
  wire [31:0]       _alus_7_io_output;
  wire [31:0]       _alus_6_io_output;
  wire [31:0]       _alus_5_io_output;
  wire [31:0]       _alus_4_io_output;
  wire [31:0]       _alus_3_io_output;
  wire [31:0]       _alus_2_io_output;
  wire [31:0]       _alus_1_io_output;
  wire [31:0]       _alus_0_io_output;
  reg  [6:0]        bundle_rd;
  reg  [31:0]       bundle_rd_val_0;
  reg  [31:0]       bundle_rd_val_1;
  reg  [31:0]       bundle_rd_val_2;
  reg  [31:0]       bundle_rd_val_3;
  reg  [31:0]       bundle_rd_val_4;
  reg  [31:0]       bundle_rd_val_5;
  reg  [31:0]       bundle_rd_val_6;
  reg  [31:0]       bundle_rd_val_7;
  reg  [31:0]       bundle_rd_val_8;
  reg  [31:0]       bundle_rd_val_9;
  reg  [31:0]       bundle_rd_val_10;
  reg  [31:0]       bundle_rd_val_11;
  reg  [31:0]       bundle_rd_val_12;
  reg  [31:0]       bundle_rd_val_13;
  reg  [31:0]       bundle_rd_val_14;
  reg  [31:0]       bundle_rd_val_15;
  reg  [15:0]       bundle_mask;
  reg               bundle_rd_wen;
  reg  [6:0]        bundle_opcode;
  reg               valid;
  reg  [15:0]       lmask_0;
  reg  [15:0]       lmask_1;
  reg  [15:0]       lmask_2;
  reg  [15:0]       lmask_3;
  wire [3:0][15:0]  _GEN = {{lmask_3}, {lmask_2}, {lmask_1}, {lmask_0}};
  wire [3:0]        active_lane =
    _GEN[io_instruction_bits_warp][0]
      ? 4'h0
      : _GEN[io_instruction_bits_warp][1]
          ? 4'h1
          : _GEN[io_instruction_bits_warp][2]
              ? 4'h2
              : _GEN[io_instruction_bits_warp][3]
                  ? 4'h3
                  : _GEN[io_instruction_bits_warp][4]
                      ? 4'h4
                      : _GEN[io_instruction_bits_warp][5]
                          ? 4'h5
                          : _GEN[io_instruction_bits_warp][6]
                              ? 4'h6
                              : _GEN[io_instruction_bits_warp][7]
                                  ? 4'h7
                                  : _GEN[io_instruction_bits_warp][8]
                                      ? 4'h8
                                      : _GEN[io_instruction_bits_warp][9]
                                          ? 4'h9
                                          : _GEN[io_instruction_bits_warp][10]
                                              ? 4'hA
                                              : _GEN[io_instruction_bits_warp][11]
                                                  ? 4'hB
                                                  : _GEN[io_instruction_bits_warp][12]
                                                      ? 4'hC
                                                      : _GEN[io_instruction_bits_warp][13]
                                                          ? 4'hD
                                                          : {3'h7,
                                                             ~(_GEN[io_instruction_bits_warp][14])};
  wire              alus_9_io_isR = io_instruction_bits_opcode == 7'h33;
  wire              _GEN_0 = io_flush | ~io_instruction_valid;
  wire [31:0]       _pc_plus_4_T = io_instruction_bits_pc + 32'h4;
  wire [31:0]       _pc_plus_imm_T =
    io_instruction_bits_pc + io_instruction_bits_immediate;
  wire [15:0][31:0] _GEN_1 =
    {{io_instruction_bits_rs1_val_15},
     {io_instruction_bits_rs1_val_14},
     {io_instruction_bits_rs1_val_13},
     {io_instruction_bits_rs1_val_12},
     {io_instruction_bits_rs1_val_11},
     {io_instruction_bits_rs1_val_10},
     {io_instruction_bits_rs1_val_9},
     {io_instruction_bits_rs1_val_8},
     {io_instruction_bits_rs1_val_7},
     {io_instruction_bits_rs1_val_6},
     {io_instruction_bits_rs1_val_5},
     {io_instruction_bits_rs1_val_4},
     {io_instruction_bits_rs1_val_3},
     {io_instruction_bits_rs1_val_2},
     {io_instruction_bits_rs1_val_1},
     {io_instruction_bits_rs1_val_0}};
  wire              _alu_b_T_15 = io_instruction_bits_opcode == 7'h13;
  wire              _GEN_2 = _alu_b_T_15 | alus_9_io_isR;
  wire              isM = alus_9_io_isR & io_instruction_bits_func7 == 7'h1;
  wire              _neg_T_106 = io_instruction_bits_func7 == 7'h20;
  wire              _neg_T_108 = io_instruction_bits_func3 == 3'h0;
  wire              _GEN_3 = io_instruction_valid & _GEN_2;
  wire              _GEN_4 = io_flush | ~_GEN_3;
  wire [31:0]       alus_0_io_b =
    _GEN_4
      ? 32'h0
      : _alu_b_T_15
          ? io_instruction_bits_immediate
          : alus_9_io_isR & _neg_T_106 & _neg_T_108
              ? 32'h0 - io_instruction_bits_rs2_val_0
              : io_instruction_bits_rs2_val_0;
  wire              malus_9_io_start =
    ~io_flush & _GEN_3 & isM & _malus_0_io_ready & _malus_1_io_ready & _malus_2_io_ready
    & _malus_3_io_ready & _malus_4_io_ready & _malus_5_io_ready & _malus_6_io_ready
    & _malus_7_io_ready & _malus_8_io_ready & _malus_9_io_ready & _malus_10_io_ready
    & _malus_11_io_ready & _malus_12_io_ready & _malus_13_io_ready & _malus_14_io_ready
    & _malus_15_io_ready;
  wire [31:0]       alus_1_io_b =
    _GEN_4
      ? 32'h0
      : _alu_b_T_15
          ? io_instruction_bits_immediate
          : alus_9_io_isR & _neg_T_106 & _neg_T_108
              ? 32'h0 - io_instruction_bits_rs2_val_1
              : io_instruction_bits_rs2_val_1;
  wire [31:0]       alus_2_io_b =
    _GEN_4
      ? 32'h0
      : _alu_b_T_15
          ? io_instruction_bits_immediate
          : alus_9_io_isR & _neg_T_106 & _neg_T_108
              ? 32'h0 - io_instruction_bits_rs2_val_2
              : io_instruction_bits_rs2_val_2;
  wire [31:0]       alus_3_io_b =
    _GEN_4
      ? 32'h0
      : _alu_b_T_15
          ? io_instruction_bits_immediate
          : alus_9_io_isR & _neg_T_106 & _neg_T_108
              ? 32'h0 - io_instruction_bits_rs2_val_3
              : io_instruction_bits_rs2_val_3;
  wire [31:0]       alus_4_io_b =
    _GEN_4
      ? 32'h0
      : _alu_b_T_15
          ? io_instruction_bits_immediate
          : alus_9_io_isR & _neg_T_106 & _neg_T_108
              ? 32'h0 - io_instruction_bits_rs2_val_4
              : io_instruction_bits_rs2_val_4;
  wire [31:0]       alus_5_io_b =
    _GEN_4
      ? 32'h0
      : _alu_b_T_15
          ? io_instruction_bits_immediate
          : alus_9_io_isR & _neg_T_106 & _neg_T_108
              ? 32'h0 - io_instruction_bits_rs2_val_5
              : io_instruction_bits_rs2_val_5;
  wire [31:0]       alus_6_io_b =
    _GEN_4
      ? 32'h0
      : _alu_b_T_15
          ? io_instruction_bits_immediate
          : alus_9_io_isR & _neg_T_106 & _neg_T_108
              ? 32'h0 - io_instruction_bits_rs2_val_6
              : io_instruction_bits_rs2_val_6;
  wire [31:0]       alus_7_io_b =
    _GEN_4
      ? 32'h0
      : _alu_b_T_15
          ? io_instruction_bits_immediate
          : alus_9_io_isR & _neg_T_106 & _neg_T_108
              ? 32'h0 - io_instruction_bits_rs2_val_7
              : io_instruction_bits_rs2_val_7;
  wire [31:0]       alus_8_io_b =
    _GEN_4
      ? 32'h0
      : _alu_b_T_15
          ? io_instruction_bits_immediate
          : alus_9_io_isR & _neg_T_106 & _neg_T_108
              ? 32'h0 - io_instruction_bits_rs2_val_8
              : io_instruction_bits_rs2_val_8;
  wire [31:0]       alus_9_io_b =
    _GEN_4
      ? 32'h0
      : _alu_b_T_15
          ? io_instruction_bits_immediate
          : alus_9_io_isR & _neg_T_106 & _neg_T_108
              ? 32'h0 - io_instruction_bits_rs2_val_9
              : io_instruction_bits_rs2_val_9;
  wire [31:0]       alus_10_io_b =
    _GEN_4
      ? 32'h0
      : _alu_b_T_15
          ? io_instruction_bits_immediate
          : alus_9_io_isR & _neg_T_106 & _neg_T_108
              ? 32'h0 - io_instruction_bits_rs2_val_10
              : io_instruction_bits_rs2_val_10;
  wire [31:0]       alus_11_io_b =
    _GEN_4
      ? 32'h0
      : _alu_b_T_15
          ? io_instruction_bits_immediate
          : alus_9_io_isR & _neg_T_106 & _neg_T_108
              ? 32'h0 - io_instruction_bits_rs2_val_11
              : io_instruction_bits_rs2_val_11;
  wire [31:0]       alus_12_io_b =
    _GEN_4
      ? 32'h0
      : _alu_b_T_15
          ? io_instruction_bits_immediate
          : alus_9_io_isR & _neg_T_106 & _neg_T_108
              ? 32'h0 - io_instruction_bits_rs2_val_12
              : io_instruction_bits_rs2_val_12;
  wire [31:0]       alus_13_io_b =
    _GEN_4
      ? 32'h0
      : _alu_b_T_15
          ? io_instruction_bits_immediate
          : alus_9_io_isR & _neg_T_106 & _neg_T_108
              ? 32'h0 - io_instruction_bits_rs2_val_13
              : io_instruction_bits_rs2_val_13;
  wire [31:0]       alus_14_io_b =
    _GEN_4
      ? 32'h0
      : _alu_b_T_15
          ? io_instruction_bits_immediate
          : alus_9_io_isR & _neg_T_106 & _neg_T_108
              ? 32'h0 - io_instruction_bits_rs2_val_14
              : io_instruction_bits_rs2_val_14;
  wire [31:0]       alus_15_io_b =
    _GEN_4
      ? 32'h0
      : _alu_b_T_15
          ? io_instruction_bits_immediate
          : alus_9_io_isR & _neg_T_106 & _neg_T_108
              ? 32'h0 - io_instruction_bits_rs2_val_15
              : io_instruction_bits_rs2_val_15;
  wire              _GEN_5 = io_instruction_bits_opcode == 7'hB;
  wire              _GEN_6 = io_instruction_bits_func7 == 7'h0;
  wire              _GEN_7 = io_instruction_bits_func7 == 7'h1;
  wire              _GEN_8 = io_instruction_bits_func7 == 7'h2;
  wire              _GEN_9 = _GEN_6 | _GEN_7;
  wire              _GEN_10 = io_instruction_bits_func7 == 7'h4;
  wire              _GEN_11 = io_instruction_bits_func7 == 7'h5;
  wire              _GEN_12 = io_instruction_bits_func7 == 7'h6;
  wire              _GEN_13 = _GEN_6 | _GEN_7 | _GEN_8 | _GEN_10 | _GEN_11;
  wire              _GEN_14 =
    io_flush | ~io_instruction_valid | _GEN_2 | ~_GEN_5 | _GEN_13 | ~_GEN_12;
  wire [15:0][31:0] _GEN_15 =
    {{io_instruction_bits_rs2_val_15},
     {io_instruction_bits_rs2_val_14},
     {io_instruction_bits_rs2_val_13},
     {io_instruction_bits_rs2_val_12},
     {io_instruction_bits_rs2_val_11},
     {io_instruction_bits_rs2_val_10},
     {io_instruction_bits_rs2_val_9},
     {io_instruction_bits_rs2_val_8},
     {io_instruction_bits_rs2_val_7},
     {io_instruction_bits_rs2_val_6},
     {io_instruction_bits_rs2_val_5},
     {io_instruction_bits_rs2_val_4},
     {io_instruction_bits_rs2_val_3},
     {io_instruction_bits_rs2_val_2},
     {io_instruction_bits_rs2_val_1},
     {io_instruction_bits_rs2_val_0}};
  wire              _GEN_16 = io_instruction_bits_func7 == 7'h7;
  wire              _GEN_17 = _GEN_10 | _GEN_11 | _GEN_12;
  wire              _GEN_18 = _GEN_6 | _GEN_7 | _GEN_8 | _GEN_17;
  wire              _GEN_19 = io_instruction_bits_opcode == 7'h63;
  wire              take_branch =
    (io_instruction_bits_func3[2]
       ? (io_instruction_bits_func3[1]
            ? _GEN_1[active_lane] < _GEN_15[active_lane]
            : $signed(_GEN_1[active_lane]) < $signed(_GEN_15[active_lane]))
       : _GEN_1[active_lane] == _GEN_15[active_lane]) ^ io_instruction_bits_func3[0];
  wire [31:0]       target = take_branch ? _pc_plus_imm_T : _pc_plus_4_T;
  wire              _GEN_20 = io_instruction_bits_opcode == 7'h37;
  wire              _GEN_21 = io_instruction_bits_opcode == 7'h17;
  wire              _GEN_22 = io_instruction_bits_opcode == 7'h6F;
  wire              _GEN_23 = io_instruction_bits_opcode == 7'h67;
  wire [31:0]       target_1 =
    _GEN_1[active_lane] + io_instruction_bits_immediate & 32'hFFFFFFFE;
  wire              _GEN_24 = _GEN_22 | _GEN_23;
  wire              _GEN_25 = _GEN_20 | _GEN_21;
  wire              _GEN_26 = _GEN_2 | _GEN_5;
  wire              _GEN_27 = io_instruction_bits_opcode == 7'h3;
  wire              _GEN_28 = _GEN_19 | _GEN_20 | _GEN_21 | _GEN_24;
  wire              _GEN_29 = _GEN_5 | _GEN_28;
  wire              _GEN_30 = _GEN_2 | _GEN_29;
  wire              _GEN_31 = io_flush | ~io_instruction_valid | _GEN_30 | ~_GEN_27;
  wire              _GEN_32 = io_instruction_bits_opcode == 7'h23;
  wire              _GEN_33 = _GEN_27 ? ~io_lsu_req_ready : _GEN_32 & ~io_lsu_req_ready;
  wire              io_mark_0 =
    ~io_flush & io_instruction_valid
    & (_GEN_30 | ~(_GEN_27 | _GEN_32) | io_lsu_req_ready);
  always @(posedge clock) begin
    if (reset) begin
      bundle_rd <= 7'h0;
      bundle_rd_val_0 <= 32'h0;
      bundle_rd_val_1 <= 32'h0;
      bundle_rd_val_2 <= 32'h0;
      bundle_rd_val_3 <= 32'h0;
      bundle_rd_val_4 <= 32'h0;
      bundle_rd_val_5 <= 32'h0;
      bundle_rd_val_6 <= 32'h0;
      bundle_rd_val_7 <= 32'h0;
      bundle_rd_val_8 <= 32'h0;
      bundle_rd_val_9 <= 32'h0;
      bundle_rd_val_10 <= 32'h0;
      bundle_rd_val_11 <= 32'h0;
      bundle_rd_val_12 <= 32'h0;
      bundle_rd_val_13 <= 32'h0;
      bundle_rd_val_14 <= 32'h0;
      bundle_rd_val_15 <= 32'h0;
      bundle_mask <= 16'h0;
      bundle_rd_wen <= 1'h0;
      bundle_opcode <= 7'h0;
      valid <= 1'h0;
      lmask_0 <= 16'hFFFF;
      lmask_1 <= 16'hFFFF;
      lmask_2 <= 16'hFFFF;
      lmask_3 <= 16'hFFFF;
    end
    else begin
      automatic logic _GEN_34;
      _GEN_34 = _GEN_6 | _GEN_7 | _GEN_8 | _GEN_10;
      if (_GEN_0) begin
      end
      else begin
        automatic logic [3:0][31:0] _GEN_35 =
          {{io_warp_ids_3}, {io_warp_ids_2}, {io_warp_ids_1}, {io_warp_ids_0}};
        automatic logic [31:0]      _GEN_36 =
          _GEN_7
            ? _GEN_35[io_instruction_bits_warp]
            : _GEN_8
                ? 32'h0
                : _GEN_10
                    ? {16'h0,
                       {|io_instruction_bits_rs1_val_15,
                        |io_instruction_bits_rs1_val_14,
                        |io_instruction_bits_rs1_val_13,
                        |io_instruction_bits_rs1_val_12,
                        |io_instruction_bits_rs1_val_11,
                        |io_instruction_bits_rs1_val_10,
                        |io_instruction_bits_rs1_val_9,
                        |io_instruction_bits_rs1_val_8,
                        |io_instruction_bits_rs1_val_7,
                        |io_instruction_bits_rs1_val_6,
                        |io_instruction_bits_rs1_val_5,
                        |io_instruction_bits_rs1_val_4,
                        |io_instruction_bits_rs1_val_3,
                        |io_instruction_bits_rs1_val_2,
                        |io_instruction_bits_rs1_val_1,
                        |io_instruction_bits_rs1_val_0} & _GEN[io_instruction_bits_warp]}
                    : _GEN_11 ? {16'h0, _GEN[io_instruction_bits_warp]} : 32'h0;
        automatic logic [31:0]      _GEN_37 =
          _GEN_19
            ? 32'h0
            : _GEN_20
                ? io_instruction_bits_immediate
                : _GEN_21 ? _pc_plus_imm_T : _GEN_24 ? _pc_plus_4_T : 32'h0;
        bundle_rd <= io_instruction_bits_rd;
        bundle_rd_val_0 <=
          _GEN_2
            ? (isM ? _malus_0_io_output : _alus_0_io_output)
            : _GEN_5 ? (_GEN_6 ? 32'h0 : _GEN_36) : _GEN_37;
        bundle_rd_val_1 <=
          _GEN_2
            ? (isM ? _malus_1_io_output : _alus_1_io_output)
            : _GEN_5 ? (_GEN_6 ? 32'h1 : _GEN_36) : _GEN_37;
        bundle_rd_val_2 <=
          _GEN_2
            ? (isM ? _malus_2_io_output : _alus_2_io_output)
            : _GEN_5 ? (_GEN_6 ? 32'h2 : _GEN_36) : _GEN_37;
        bundle_rd_val_3 <=
          _GEN_2
            ? (isM ? _malus_3_io_output : _alus_3_io_output)
            : _GEN_5 ? (_GEN_6 ? 32'h3 : _GEN_36) : _GEN_37;
        bundle_rd_val_4 <=
          _GEN_2
            ? (isM ? _malus_4_io_output : _alus_4_io_output)
            : _GEN_5 ? (_GEN_6 ? 32'h4 : _GEN_36) : _GEN_37;
        bundle_rd_val_5 <=
          _GEN_2
            ? (isM ? _malus_5_io_output : _alus_5_io_output)
            : _GEN_5 ? (_GEN_6 ? 32'h5 : _GEN_36) : _GEN_37;
        bundle_rd_val_6 <=
          _GEN_2
            ? (isM ? _malus_6_io_output : _alus_6_io_output)
            : _GEN_5 ? (_GEN_6 ? 32'h6 : _GEN_36) : _GEN_37;
        bundle_rd_val_7 <=
          _GEN_2
            ? (isM ? _malus_7_io_output : _alus_7_io_output)
            : _GEN_5 ? (_GEN_6 ? 32'h7 : _GEN_36) : _GEN_37;
        bundle_rd_val_8 <=
          _GEN_2
            ? (isM ? _malus_8_io_output : _alus_8_io_output)
            : _GEN_5 ? (_GEN_6 ? 32'h8 : _GEN_36) : _GEN_37;
        bundle_rd_val_9 <=
          _GEN_2
            ? (isM ? _malus_9_io_output : _alus_9_io_output)
            : _GEN_5 ? (_GEN_6 ? 32'h9 : _GEN_36) : _GEN_37;
        bundle_rd_val_10 <=
          _GEN_2
            ? (isM ? _malus_10_io_output : _alus_10_io_output)
            : _GEN_5 ? (_GEN_6 ? 32'hA : _GEN_36) : _GEN_37;
        bundle_rd_val_11 <=
          _GEN_2
            ? (isM ? _malus_11_io_output : _alus_11_io_output)
            : _GEN_5 ? (_GEN_6 ? 32'hB : _GEN_36) : _GEN_37;
        bundle_rd_val_12 <=
          _GEN_2
            ? (isM ? _malus_12_io_output : _alus_12_io_output)
            : _GEN_5 ? (_GEN_6 ? 32'hC : _GEN_36) : _GEN_37;
        bundle_rd_val_13 <=
          _GEN_2
            ? (isM ? _malus_13_io_output : _alus_13_io_output)
            : _GEN_5 ? (_GEN_6 ? 32'hD : _GEN_36) : _GEN_37;
        bundle_rd_val_14 <=
          _GEN_2
            ? (isM ? _malus_14_io_output : _alus_14_io_output)
            : _GEN_5 ? (_GEN_6 ? 32'hE : _GEN_36) : _GEN_37;
        bundle_rd_val_15 <=
          _GEN_2
            ? (isM ? _malus_15_io_output : _alus_15_io_output)
            : _GEN_5 ? (_GEN_6 ? 32'hF : _GEN_36) : _GEN_37;
        bundle_mask <= _GEN_2 | ~_GEN_5 ? _GEN[io_instruction_bits_warp] : 16'hFFFF;
        bundle_rd_wen <=
          _GEN_2
          | (_GEN_5
               ? _GEN_9 | ~_GEN_8 & (_GEN_10 | _GEN_11)
               : ~_GEN_19 & (_GEN_20 | _GEN_21 | _GEN_22 | _GEN_23));
        bundle_opcode <= io_instruction_bits_opcode;
      end
      valid <= io_mark_0;
      if (io_allocate_warp & io_allocate_id == 2'h0)
        lmask_0 <= 16'hFFFF;
      else if (io_flush | ~io_instruction_valid | _GEN_2 | ~_GEN_5 | _GEN_34
               | ~(_GEN_11 & io_instruction_bits_warp == 2'h0)) begin
      end
      else
        lmask_0 <= _GEN_1[active_lane][15:0];
      if (io_allocate_warp & io_allocate_id == 2'h1)
        lmask_1 <= 16'hFFFF;
      else if (io_flush | ~io_instruction_valid | _GEN_2 | ~_GEN_5 | _GEN_34
               | ~(_GEN_11 & io_instruction_bits_warp == 2'h1)) begin
      end
      else
        lmask_1 <= _GEN_1[active_lane][15:0];
      if (io_allocate_warp & io_allocate_id == 2'h2)
        lmask_2 <= 16'hFFFF;
      else if (io_flush | ~io_instruction_valid | _GEN_2 | ~_GEN_5 | _GEN_34
               | ~(_GEN_11 & io_instruction_bits_warp == 2'h2)) begin
      end
      else
        lmask_2 <= _GEN_1[active_lane][15:0];
      if (io_allocate_warp & (&io_allocate_id))
        lmask_3 <= 16'hFFFF;
      else if (io_flush | ~io_instruction_valid | _GEN_2 | ~_GEN_5 | _GEN_34
               | ~(_GEN_11 & (&io_instruction_bits_warp))) begin
      end
      else
        lmask_3 <= _GEN_1[active_lane][15:0];
    end
  end // always @(posedge)
  ALU alus_0 (
    .io_func7  (io_instruction_bits_func7),
    .io_func3  (io_instruction_bits_func3),
    .io_isR    (alus_9_io_isR),
    .io_a      (io_instruction_bits_rs1_val_0),
    .io_b      (alus_0_io_b),
    .io_output (_alus_0_io_output)
  );
  ALU alus_1 (
    .io_func7  (io_instruction_bits_func7),
    .io_func3  (io_instruction_bits_func3),
    .io_isR    (alus_9_io_isR),
    .io_a      (io_instruction_bits_rs1_val_1),
    .io_b      (alus_1_io_b),
    .io_output (_alus_1_io_output)
  );
  ALU alus_2 (
    .io_func7  (io_instruction_bits_func7),
    .io_func3  (io_instruction_bits_func3),
    .io_isR    (alus_9_io_isR),
    .io_a      (io_instruction_bits_rs1_val_2),
    .io_b      (alus_2_io_b),
    .io_output (_alus_2_io_output)
  );
  ALU alus_3 (
    .io_func7  (io_instruction_bits_func7),
    .io_func3  (io_instruction_bits_func3),
    .io_isR    (alus_9_io_isR),
    .io_a      (io_instruction_bits_rs1_val_3),
    .io_b      (alus_3_io_b),
    .io_output (_alus_3_io_output)
  );
  ALU alus_4 (
    .io_func7  (io_instruction_bits_func7),
    .io_func3  (io_instruction_bits_func3),
    .io_isR    (alus_9_io_isR),
    .io_a      (io_instruction_bits_rs1_val_4),
    .io_b      (alus_4_io_b),
    .io_output (_alus_4_io_output)
  );
  ALU alus_5 (
    .io_func7  (io_instruction_bits_func7),
    .io_func3  (io_instruction_bits_func3),
    .io_isR    (alus_9_io_isR),
    .io_a      (io_instruction_bits_rs1_val_5),
    .io_b      (alus_5_io_b),
    .io_output (_alus_5_io_output)
  );
  ALU alus_6 (
    .io_func7  (io_instruction_bits_func7),
    .io_func3  (io_instruction_bits_func3),
    .io_isR    (alus_9_io_isR),
    .io_a      (io_instruction_bits_rs1_val_6),
    .io_b      (alus_6_io_b),
    .io_output (_alus_6_io_output)
  );
  ALU alus_7 (
    .io_func7  (io_instruction_bits_func7),
    .io_func3  (io_instruction_bits_func3),
    .io_isR    (alus_9_io_isR),
    .io_a      (io_instruction_bits_rs1_val_7),
    .io_b      (alus_7_io_b),
    .io_output (_alus_7_io_output)
  );
  ALU alus_8 (
    .io_func7  (io_instruction_bits_func7),
    .io_func3  (io_instruction_bits_func3),
    .io_isR    (alus_9_io_isR),
    .io_a      (io_instruction_bits_rs1_val_8),
    .io_b      (alus_8_io_b),
    .io_output (_alus_8_io_output)
  );
  ALU alus_9 (
    .io_func7  (io_instruction_bits_func7),
    .io_func3  (io_instruction_bits_func3),
    .io_isR    (alus_9_io_isR),
    .io_a      (io_instruction_bits_rs1_val_9),
    .io_b      (alus_9_io_b),
    .io_output (_alus_9_io_output)
  );
  ALU alus_10 (
    .io_func7  (io_instruction_bits_func7),
    .io_func3  (io_instruction_bits_func3),
    .io_isR    (alus_9_io_isR),
    .io_a      (io_instruction_bits_rs1_val_10),
    .io_b      (alus_10_io_b),
    .io_output (_alus_10_io_output)
  );
  ALU alus_11 (
    .io_func7  (io_instruction_bits_func7),
    .io_func3  (io_instruction_bits_func3),
    .io_isR    (alus_9_io_isR),
    .io_a      (io_instruction_bits_rs1_val_11),
    .io_b      (alus_11_io_b),
    .io_output (_alus_11_io_output)
  );
  ALU alus_12 (
    .io_func7  (io_instruction_bits_func7),
    .io_func3  (io_instruction_bits_func3),
    .io_isR    (alus_9_io_isR),
    .io_a      (io_instruction_bits_rs1_val_12),
    .io_b      (alus_12_io_b),
    .io_output (_alus_12_io_output)
  );
  ALU alus_13 (
    .io_func7  (io_instruction_bits_func7),
    .io_func3  (io_instruction_bits_func3),
    .io_isR    (alus_9_io_isR),
    .io_a      (io_instruction_bits_rs1_val_13),
    .io_b      (alus_13_io_b),
    .io_output (_alus_13_io_output)
  );
  ALU alus_14 (
    .io_func7  (io_instruction_bits_func7),
    .io_func3  (io_instruction_bits_func3),
    .io_isR    (alus_9_io_isR),
    .io_a      (io_instruction_bits_rs1_val_14),
    .io_b      (alus_14_io_b),
    .io_output (_alus_14_io_output)
  );
  ALU alus_15 (
    .io_func7  (io_instruction_bits_func7),
    .io_func3  (io_instruction_bits_func3),
    .io_isR    (alus_9_io_isR),
    .io_a      (io_instruction_bits_rs1_val_15),
    .io_b      (alus_15_io_b),
    .io_output (_alus_15_io_output)
  );
  MALU malus_0 (
    .clock     (clock),
    .reset     (reset),
    .io_func3  (io_instruction_bits_func3),
    .io_a      (io_instruction_bits_rs1_val_0),
    .io_b      (alus_0_io_b),
    .io_output (_malus_0_io_output),
    .io_ready  (_malus_0_io_ready),
    .io_valid  (_malus_0_io_valid),
    .io_start  (malus_9_io_start)
  );
  MALU malus_1 (
    .clock     (clock),
    .reset     (reset),
    .io_func3  (io_instruction_bits_func3),
    .io_a      (io_instruction_bits_rs1_val_1),
    .io_b      (alus_1_io_b),
    .io_output (_malus_1_io_output),
    .io_ready  (_malus_1_io_ready),
    .io_valid  (_malus_1_io_valid),
    .io_start  (malus_9_io_start)
  );
  MALU malus_2 (
    .clock     (clock),
    .reset     (reset),
    .io_func3  (io_instruction_bits_func3),
    .io_a      (io_instruction_bits_rs1_val_2),
    .io_b      (alus_2_io_b),
    .io_output (_malus_2_io_output),
    .io_ready  (_malus_2_io_ready),
    .io_valid  (_malus_2_io_valid),
    .io_start  (malus_9_io_start)
  );
  MALU malus_3 (
    .clock     (clock),
    .reset     (reset),
    .io_func3  (io_instruction_bits_func3),
    .io_a      (io_instruction_bits_rs1_val_3),
    .io_b      (alus_3_io_b),
    .io_output (_malus_3_io_output),
    .io_ready  (_malus_3_io_ready),
    .io_valid  (_malus_3_io_valid),
    .io_start  (malus_9_io_start)
  );
  MALU malus_4 (
    .clock     (clock),
    .reset     (reset),
    .io_func3  (io_instruction_bits_func3),
    .io_a      (io_instruction_bits_rs1_val_4),
    .io_b      (alus_4_io_b),
    .io_output (_malus_4_io_output),
    .io_ready  (_malus_4_io_ready),
    .io_valid  (_malus_4_io_valid),
    .io_start  (malus_9_io_start)
  );
  MALU malus_5 (
    .clock     (clock),
    .reset     (reset),
    .io_func3  (io_instruction_bits_func3),
    .io_a      (io_instruction_bits_rs1_val_5),
    .io_b      (alus_5_io_b),
    .io_output (_malus_5_io_output),
    .io_ready  (_malus_5_io_ready),
    .io_valid  (_malus_5_io_valid),
    .io_start  (malus_9_io_start)
  );
  MALU malus_6 (
    .clock     (clock),
    .reset     (reset),
    .io_func3  (io_instruction_bits_func3),
    .io_a      (io_instruction_bits_rs1_val_6),
    .io_b      (alus_6_io_b),
    .io_output (_malus_6_io_output),
    .io_ready  (_malus_6_io_ready),
    .io_valid  (_malus_6_io_valid),
    .io_start  (malus_9_io_start)
  );
  MALU malus_7 (
    .clock     (clock),
    .reset     (reset),
    .io_func3  (io_instruction_bits_func3),
    .io_a      (io_instruction_bits_rs1_val_7),
    .io_b      (alus_7_io_b),
    .io_output (_malus_7_io_output),
    .io_ready  (_malus_7_io_ready),
    .io_valid  (_malus_7_io_valid),
    .io_start  (malus_9_io_start)
  );
  MALU malus_8 (
    .clock     (clock),
    .reset     (reset),
    .io_func3  (io_instruction_bits_func3),
    .io_a      (io_instruction_bits_rs1_val_8),
    .io_b      (alus_8_io_b),
    .io_output (_malus_8_io_output),
    .io_ready  (_malus_8_io_ready),
    .io_valid  (_malus_8_io_valid),
    .io_start  (malus_9_io_start)
  );
  MALU malus_9 (
    .clock     (clock),
    .reset     (reset),
    .io_func3  (io_instruction_bits_func3),
    .io_a      (io_instruction_bits_rs1_val_9),
    .io_b      (alus_9_io_b),
    .io_output (_malus_9_io_output),
    .io_ready  (_malus_9_io_ready),
    .io_valid  (_malus_9_io_valid),
    .io_start  (malus_9_io_start)
  );
  MALU malus_10 (
    .clock     (clock),
    .reset     (reset),
    .io_func3  (io_instruction_bits_func3),
    .io_a      (io_instruction_bits_rs1_val_10),
    .io_b      (alus_10_io_b),
    .io_output (_malus_10_io_output),
    .io_ready  (_malus_10_io_ready),
    .io_valid  (_malus_10_io_valid),
    .io_start  (malus_9_io_start)
  );
  MALU malus_11 (
    .clock     (clock),
    .reset     (reset),
    .io_func3  (io_instruction_bits_func3),
    .io_a      (io_instruction_bits_rs1_val_11),
    .io_b      (alus_11_io_b),
    .io_output (_malus_11_io_output),
    .io_ready  (_malus_11_io_ready),
    .io_valid  (_malus_11_io_valid),
    .io_start  (malus_9_io_start)
  );
  MALU malus_12 (
    .clock     (clock),
    .reset     (reset),
    .io_func3  (io_instruction_bits_func3),
    .io_a      (io_instruction_bits_rs1_val_12),
    .io_b      (alus_12_io_b),
    .io_output (_malus_12_io_output),
    .io_ready  (_malus_12_io_ready),
    .io_valid  (_malus_12_io_valid),
    .io_start  (malus_9_io_start)
  );
  MALU malus_13 (
    .clock     (clock),
    .reset     (reset),
    .io_func3  (io_instruction_bits_func3),
    .io_a      (io_instruction_bits_rs1_val_13),
    .io_b      (alus_13_io_b),
    .io_output (_malus_13_io_output),
    .io_ready  (_malus_13_io_ready),
    .io_valid  (_malus_13_io_valid),
    .io_start  (malus_9_io_start)
  );
  MALU malus_14 (
    .clock     (clock),
    .reset     (reset),
    .io_func3  (io_instruction_bits_func3),
    .io_a      (io_instruction_bits_rs1_val_14),
    .io_b      (alus_14_io_b),
    .io_output (_malus_14_io_output),
    .io_ready  (_malus_14_io_ready),
    .io_valid  (_malus_14_io_valid),
    .io_start  (malus_9_io_start)
  );
  MALU malus_15 (
    .clock     (clock),
    .reset     (reset),
    .io_func3  (io_instruction_bits_func3),
    .io_a      (io_instruction_bits_rs1_val_15),
    .io_b      (alus_15_io_b),
    .io_output (_malus_15_io_output),
    .io_ready  (_malus_15_io_ready),
    .io_valid  (_malus_15_io_valid),
    .io_start  (malus_9_io_start)
  );
  assign io_next_instruction_valid =
    valid
    & (~io_flush | bundle_opcode == 7'h6F | bundle_opcode == 7'h67
       | bundle_opcode == 7'h63);
  assign io_next_instruction_bits_rd = bundle_rd;
  assign io_next_instruction_bits_rd_val_0 = bundle_rd_val_0;
  assign io_next_instruction_bits_rd_val_1 = bundle_rd_val_1;
  assign io_next_instruction_bits_rd_val_2 = bundle_rd_val_2;
  assign io_next_instruction_bits_rd_val_3 = bundle_rd_val_3;
  assign io_next_instruction_bits_rd_val_4 = bundle_rd_val_4;
  assign io_next_instruction_bits_rd_val_5 = bundle_rd_val_5;
  assign io_next_instruction_bits_rd_val_6 = bundle_rd_val_6;
  assign io_next_instruction_bits_rd_val_7 = bundle_rd_val_7;
  assign io_next_instruction_bits_rd_val_8 = bundle_rd_val_8;
  assign io_next_instruction_bits_rd_val_9 = bundle_rd_val_9;
  assign io_next_instruction_bits_rd_val_10 = bundle_rd_val_10;
  assign io_next_instruction_bits_rd_val_11 = bundle_rd_val_11;
  assign io_next_instruction_bits_rd_val_12 = bundle_rd_val_12;
  assign io_next_instruction_bits_rd_val_13 = bundle_rd_val_13;
  assign io_next_instruction_bits_rd_val_14 = bundle_rd_val_14;
  assign io_next_instruction_bits_rd_val_15 = bundle_rd_val_15;
  assign io_next_instruction_bits_mask = bundle_mask;
  assign io_next_instruction_bits_rd_wen = bundle_rd_wen;
  assign io_pc_redirect_bits =
    io_flush | ~io_instruction_valid | _GEN_26
      ? 32'h0
      : _GEN_19
          ? target
          : _GEN_25 ? 32'h0 : _GEN_22 ? _pc_plus_imm_T : _GEN_23 ? target_1 : 32'h0;
  assign io_lsu_req_valid =
    ~io_flush & io_instruction_valid & ~_GEN_30 & (_GEN_27 | _GEN_32);
  assign io_lsu_req_bits_base_0 = io_instruction_bits_rs1_val_0;
  assign io_lsu_req_bits_base_1 = io_instruction_bits_rs1_val_1;
  assign io_lsu_req_bits_base_2 = io_instruction_bits_rs1_val_2;
  assign io_lsu_req_bits_base_3 = io_instruction_bits_rs1_val_3;
  assign io_lsu_req_bits_base_4 = io_instruction_bits_rs1_val_4;
  assign io_lsu_req_bits_base_5 = io_instruction_bits_rs1_val_5;
  assign io_lsu_req_bits_base_6 = io_instruction_bits_rs1_val_6;
  assign io_lsu_req_bits_base_7 = io_instruction_bits_rs1_val_7;
  assign io_lsu_req_bits_base_8 = io_instruction_bits_rs1_val_8;
  assign io_lsu_req_bits_base_9 = io_instruction_bits_rs1_val_9;
  assign io_lsu_req_bits_base_10 = io_instruction_bits_rs1_val_10;
  assign io_lsu_req_bits_base_11 = io_instruction_bits_rs1_val_11;
  assign io_lsu_req_bits_base_12 = io_instruction_bits_rs1_val_12;
  assign io_lsu_req_bits_base_13 = io_instruction_bits_rs1_val_13;
  assign io_lsu_req_bits_base_14 = io_instruction_bits_rs1_val_14;
  assign io_lsu_req_bits_base_15 = io_instruction_bits_rs1_val_15;
  assign io_lsu_req_bits_wdata_0 = io_instruction_bits_rs2_val_0;
  assign io_lsu_req_bits_wdata_1 = io_instruction_bits_rs2_val_1;
  assign io_lsu_req_bits_wdata_2 = io_instruction_bits_rs2_val_2;
  assign io_lsu_req_bits_wdata_3 = io_instruction_bits_rs2_val_3;
  assign io_lsu_req_bits_wdata_4 = io_instruction_bits_rs2_val_4;
  assign io_lsu_req_bits_wdata_5 = io_instruction_bits_rs2_val_5;
  assign io_lsu_req_bits_wdata_6 = io_instruction_bits_rs2_val_6;
  assign io_lsu_req_bits_wdata_7 = io_instruction_bits_rs2_val_7;
  assign io_lsu_req_bits_wdata_8 = io_instruction_bits_rs2_val_8;
  assign io_lsu_req_bits_wdata_9 = io_instruction_bits_rs2_val_9;
  assign io_lsu_req_bits_wdata_10 = io_instruction_bits_rs2_val_10;
  assign io_lsu_req_bits_wdata_11 = io_instruction_bits_rs2_val_11;
  assign io_lsu_req_bits_wdata_12 = io_instruction_bits_rs2_val_12;
  assign io_lsu_req_bits_wdata_13 = io_instruction_bits_rs2_val_13;
  assign io_lsu_req_bits_wdata_14 = io_instruction_bits_rs2_val_14;
  assign io_lsu_req_bits_wdata_15 = io_instruction_bits_rs2_val_15;
  assign io_lsu_req_bits_imm = io_instruction_bits_immediate;
  assign io_lsu_req_bits_mask = _GEN[io_instruction_bits_warp];
  assign io_lsu_req_bits_rd = io_instruction_bits_rd;
  assign io_lsu_req_bits_func3 = io_instruction_bits_func3;
  assign io_lsu_req_bits_write =
    ~io_flush & io_instruction_valid
    & ~(_GEN_2 | _GEN_5 | _GEN_19 | _GEN_20 | _GEN_21 | _GEN_22 | _GEN_23 | _GEN_27)
    & _GEN_32;
  assign io_memory_stall =
    ~io_flush & io_instruction_valid
    & (_GEN_2
         ? isM
           & ~(_malus_0_io_valid & _malus_1_io_valid & _malus_2_io_valid
               & _malus_3_io_valid & _malus_4_io_valid & _malus_5_io_valid
               & _malus_6_io_valid & _malus_7_io_valid & _malus_8_io_valid
               & _malus_9_io_valid & _malus_10_io_valid & _malus_11_io_valid
               & _malus_12_io_valid & _malus_13_io_valid & _malus_14_io_valid
               & _malus_15_io_valid)
         : ~_GEN_29 & _GEN_33);
  assign io_jump_flush =
    ~io_flush & io_instruction_valid & ~_GEN_26
    & (_GEN_19 ? take_branch : ~_GEN_25 & (_GEN_22 | _GEN_23));
  assign io_mem_issue =
    ~io_flush & io_instruction_valid & ~_GEN_30 & _GEN_27 & io_lsu_req_ready;
  assign io_mem_issue_rd = _GEN_31 ? 7'h0 : io_instruction_bits_rd;
  assign io_mem_issue_count =
    _GEN_31
      ? 5'h0
      : {1'h0,
         {1'h0,
          {1'h0,
           {1'h0, _GEN[io_instruction_bits_warp][0]}
             + {1'h0, _GEN[io_instruction_bits_warp][1]}}
            + {1'h0,
               {1'h0, _GEN[io_instruction_bits_warp][2]}
                 + {1'h0, _GEN[io_instruction_bits_warp][3]}}}
           + {1'h0,
              {1'h0,
               {1'h0, _GEN[io_instruction_bits_warp][4]}
                 + {1'h0, _GEN[io_instruction_bits_warp][5]}}
                + {1'h0,
                   {1'h0, _GEN[io_instruction_bits_warp][6]}
                     + {1'h0, _GEN[io_instruction_bits_warp][7]}}}}
        + {1'h0,
           {1'h0,
            {1'h0,
             {1'h0, _GEN[io_instruction_bits_warp][8]}
               + {1'h0, _GEN[io_instruction_bits_warp][9]}}
              + {1'h0,
                 {1'h0, _GEN[io_instruction_bits_warp][10]}
                   + {1'h0, _GEN[io_instruction_bits_warp][11]}}}
             + {1'h0,
                {1'h0,
                 {1'h0, _GEN[io_instruction_bits_warp][12]}
                   + {1'h0, _GEN[io_instruction_bits_warp][13]}}
                  + {1'h0,
                     {1'h0, _GEN[io_instruction_bits_warp][14]}
                       + {1'h0, _GEN[io_instruction_bits_warp][15]}}}};
  assign io_warp_swap =
    ~io_flush & io_instruction_valid & ~_GEN_2
    & (_GEN_5 ? ~_GEN_9 & (_GEN_8 | ~_GEN_17 & _GEN_16) : ~_GEN_28 & _GEN_33);
  assign io_warp_terminate =
    ~io_flush & io_instruction_valid & ~_GEN_2 & _GEN_5 & ~_GEN_9 & _GEN_8;
  assign io_mark = io_mark_0;
  assign io_mark_pc =
    _GEN_0
      ? 32'h0
      : _GEN_26
          ? _pc_plus_4_T
          : _GEN_19
              ? target
              : _GEN_25
                  ? _pc_plus_4_T
                  : _GEN_22 ? _pc_plus_imm_T : _GEN_23 ? target_1 : _pc_plus_4_T;
  assign io_mark_warp = _GEN_0 ? 2'h0 : io_instruction_bits_warp;
  assign io_spawn =
    ~io_flush & io_instruction_valid & ~_GEN_2 & _GEN_5 & ~_GEN_13 & _GEN_12;
  assign io_spawn_count = _GEN_14 ? 32'h0 : _GEN_1[active_lane];
  assign io_spawn_pc_in = _GEN_14 ? 32'h0 : _GEN_15[active_lane];
  assign io_barrier =
    ~io_flush & io_instruction_valid & ~_GEN_2 & _GEN_5 & ~_GEN_18 & _GEN_16;
  assign io_barrier_target =
    io_flush | ~io_instruction_valid | _GEN_2 | ~_GEN_5 | _GEN_18 | ~_GEN_16
      ? 32'h0
      : _GEN_1[active_lane];
endmodule

