// Generated by CIRCT firtool-1.128.0
module Fetch(
  input         clock,
                reset,
                io_execute,
  input  [1:0]  io_active_warp,
  input         io_mark,
  input  [31:0] io_mark_pc,
  input  [1:0]  io_mark_warp,
  input         io_allocate_warp,
  input  [31:0] io_allocate_pc,
  input  [1:0]  io_allocate_id,
                io_fetch_request_fetch_op,
  input  [31:0] io_fetch_request_redirect_addr,
  output        io_fetch_result_valid,
  output [31:0] io_fetch_result_bits_pc,
  output [1:0]  io_fetch_result_bits_warp,
  output [31:0] io_fetch_result_bits_inst,
                io_icache_req_address,
  output        io_icache_start,
  input         io_icache_ready,
                io_icache_valid,
  input  [31:0] io_icache_data
);

  reg  [31:0]      speculative_instruction_pointers_0;
  reg  [31:0]      speculative_instruction_pointers_1;
  reg  [31:0]      speculative_instruction_pointers_2;
  reg  [31:0]      speculative_instruction_pointers_3;
  reg  [31:0]      instruction_pointers_0;
  reg  [31:0]      instruction_pointers_1;
  reg  [31:0]      instruction_pointers_2;
  reg  [31:0]      instruction_pointers_3;
  reg              ignore_instruction;
  reg  [31:0]      request_instruction_pointer;
  reg  [1:0]       request_warp;
  reg              request_in_flight;
  reg  [31:0]      fetch_result_pc;
  reg  [1:0]       fetch_result_warp;
  reg  [31:0]      fetch_result_inst;
  reg              fetch_result_valid;
  wire [3:0][31:0] _GEN =
    {{speculative_instruction_pointers_3},
     {speculative_instruction_pointers_2},
     {speculative_instruction_pointers_1},
     {speculative_instruction_pointers_0}};
  wire             dequeuing = io_execute & io_fetch_request_fetch_op == 2'h2;
  wire             redirecting = io_execute & io_fetch_request_fetch_op == 2'h1;
  wire             can_issue = io_icache_ready & ~fetch_result_valid & ~io_icache_valid;
  wire             _GEN_0 =
    (dequeuing | io_execute & io_fetch_request_fetch_op == 2'h0) & can_issue;
  wire             _GEN_1 = redirecting & can_issue;
  wire             io_icache_start_0 = io_execute & (_GEN_1 | _GEN_0);
  always @(posedge clock) begin
    automatic logic warp_switching;
    automatic logic _GEN_2;
    automatic logic _GEN_3;
    warp_switching = io_execute & (&io_fetch_request_fetch_op);
    _GEN_2 = io_icache_valid & ~ignore_instruction;
    _GEN_3 = redirecting | warp_switching;
    if (reset) begin
      speculative_instruction_pointers_0 <= 32'h0;
      speculative_instruction_pointers_1 <= 32'h0;
      speculative_instruction_pointers_2 <= 32'h0;
      speculative_instruction_pointers_3 <= 32'h0;
      instruction_pointers_0 <= 32'h0;
      instruction_pointers_1 <= 32'h0;
      instruction_pointers_2 <= 32'h0;
      instruction_pointers_3 <= 32'h0;
      ignore_instruction <= 1'h0;
      request_instruction_pointer <= 32'h0;
      request_warp <= 2'h0;
      request_in_flight <= 1'h0;
      fetch_result_valid <= 1'h0;
    end
    else begin
      automatic logic [31:0] _speculative_instruction_pointers_T;
      automatic logic [31:0] _GEN_4;
      _speculative_instruction_pointers_T = _GEN[io_active_warp] + 32'h4;
      _GEN_4 =
        can_issue
          ? io_fetch_request_redirect_addr + 32'h4
          : io_fetch_request_redirect_addr;
      if (io_allocate_warp & io_allocate_id == 2'h0) begin
        speculative_instruction_pointers_0 <= io_allocate_pc;
        instruction_pointers_0 <= io_allocate_pc;
      end
      else begin
        if (io_execute) begin
          if (warp_switching)
            speculative_instruction_pointers_0 <= instruction_pointers_0;
          else begin
            automatic logic _GEN_5;
            _GEN_5 = io_active_warp == 2'h0;
            if (redirecting & _GEN_5)
              speculative_instruction_pointers_0 <= _GEN_4;
            else if (_GEN_0 & _GEN_5)
              speculative_instruction_pointers_0 <= _speculative_instruction_pointers_T;
          end
        end
        if (io_mark & io_mark_warp == 2'h0)
          instruction_pointers_0 <= io_mark_pc;
      end
      if (io_allocate_warp & io_allocate_id == 2'h1) begin
        speculative_instruction_pointers_1 <= io_allocate_pc;
        instruction_pointers_1 <= io_allocate_pc;
      end
      else begin
        if (io_execute) begin
          if (warp_switching)
            speculative_instruction_pointers_1 <= instruction_pointers_1;
          else begin
            automatic logic _GEN_6;
            _GEN_6 = io_active_warp == 2'h1;
            if (redirecting & _GEN_6)
              speculative_instruction_pointers_1 <= _GEN_4;
            else if (_GEN_0 & _GEN_6)
              speculative_instruction_pointers_1 <= _speculative_instruction_pointers_T;
          end
        end
        if (io_mark & io_mark_warp == 2'h1)
          instruction_pointers_1 <= io_mark_pc;
      end
      if (io_allocate_warp & io_allocate_id == 2'h2) begin
        speculative_instruction_pointers_2 <= io_allocate_pc;
        instruction_pointers_2 <= io_allocate_pc;
      end
      else begin
        if (io_execute) begin
          if (warp_switching)
            speculative_instruction_pointers_2 <= instruction_pointers_2;
          else begin
            automatic logic _GEN_7;
            _GEN_7 = io_active_warp == 2'h2;
            if (redirecting & _GEN_7)
              speculative_instruction_pointers_2 <= _GEN_4;
            else if (_GEN_0 & _GEN_7)
              speculative_instruction_pointers_2 <= _speculative_instruction_pointers_T;
          end
        end
        if (io_mark & io_mark_warp == 2'h2)
          instruction_pointers_2 <= io_mark_pc;
      end
      if (io_allocate_warp & (&io_allocate_id)) begin
        speculative_instruction_pointers_3 <= io_allocate_pc;
        instruction_pointers_3 <= io_allocate_pc;
      end
      else begin
        if (io_execute) begin
          if (warp_switching)
            speculative_instruction_pointers_3 <= instruction_pointers_3;
          else if (redirecting & (&io_active_warp))
            speculative_instruction_pointers_3 <= _GEN_4;
          else if (_GEN_0 & (&io_active_warp))
            speculative_instruction_pointers_3 <= _speculative_instruction_pointers_T;
        end
        if (io_mark & (&io_mark_warp))
          instruction_pointers_3 <= io_mark_pc;
      end
      ignore_instruction <=
        ~(io_icache_valid & ignore_instruction)
        & (io_execute
             ? (warp_switching
                  ? request_in_flight & ~io_icache_valid
                  : redirecting
                      ? request_in_flight & ~io_icache_valid
                      : ignore_instruction)
             : ignore_instruction);
      if (io_execute) begin
        if (_GEN_1)
          request_instruction_pointer <= io_fetch_request_redirect_addr;
        else if (_GEN_0)
          request_instruction_pointer <= _GEN[io_active_warp];
      end
      if (io_execute & (redirecting & can_issue | _GEN_0))
        request_warp <= io_active_warp;
      request_in_flight <= io_icache_start_0 | ~io_icache_valid & request_in_flight;
      fetch_result_valid <= ~_GEN_3 & (_GEN_2 | ~dequeuing & fetch_result_valid);
    end
    if (_GEN_3 | ~_GEN_2) begin
    end
    else begin
      fetch_result_pc <= request_instruction_pointer;
      fetch_result_warp <= request_warp;
      fetch_result_inst <= io_icache_data;
    end
  end // always @(posedge)
  assign io_fetch_result_valid = fetch_result_valid;
  assign io_fetch_result_bits_pc = fetch_result_pc;
  assign io_fetch_result_bits_warp = fetch_result_warp;
  assign io_fetch_result_bits_inst = fetch_result_inst;
  assign io_icache_req_address =
    _GEN_1 ? io_fetch_request_redirect_addr : _GEN[io_active_warp];
  assign io_icache_start = io_icache_start_0;
endmodule

