// Generated by CIRCT firtool-1.128.0
module HardwareTimer(
  input         clock,
                reset,
  output [31:0] io_micros
);

  reg [31:0] cycleCounter;
  reg [31:0] microsReg;
  always @(posedge clock) begin
    if (reset) begin
      cycleCounter <= 32'h0;
      microsReg <= 32'h0;
    end
    else begin
      automatic logic _GEN = cycleCounter == 32'hA6;
      cycleCounter <= _GEN ? 32'h0 : cycleCounter + 32'h1;
      if (_GEN)
        microsReg <= microsReg + 32'h1;
    end
  end // always @(posedge)
  assign io_micros = microsReg;
endmodule

