// Generated by CIRCT firtool-1.128.0

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_
module ICache(
  input          clock,
                 reset,
  input  [31:0]  io_req_address,
  input          io_start,
  output         io_ready,
                 io_done,
                 io_miss,
  output [31:0]  io_data,
  input  [511:0] io_line_result,
  output [31:0]  io_line_addr,
  input          io_line_valid
);

  wire              io_ready_0;
  wire [511:0]      _data_array_ext_R0_data;
  wire [19:0]       _meta_array_ext_R0_data;
  reg  [1:0]        state;
  reg  [31:0]       current_mem_req_address;
  reg               current_mem_req_read;
  reg               current_mem_req_write;
  wire [31:0]       lookup_address =
    io_ready_0 & io_start ? io_req_address : current_mem_req_address;
  reg  [1:0]        byte_offset_REG;
  reg  [3:0]        word_offset_REG;
  reg  [17:0]       cache_tag_REG;
  reg  [25:0]       line_addr_REG;
  wire              _io_ready_T_1 = state == 2'h1;
  wire              read_enable = ~(|state) | _io_ready_T_1;
  wire              _hit_T = cache_tag_REG == _meta_array_ext_R0_data[17:0];
  assign io_ready_0 = ~(|state) | _io_ready_T_1 & _hit_T & _meta_array_ext_R0_data[19];
  wire              _GEN = state == 2'h1;
  wire              _GEN_0 = _hit_T & _meta_array_ext_R0_data[19];
  wire [15:0][31:0] _GEN_1 =
    {{_data_array_ext_R0_data[511:480]},
     {_data_array_ext_R0_data[479:448]},
     {_data_array_ext_R0_data[447:416]},
     {_data_array_ext_R0_data[415:384]},
     {_data_array_ext_R0_data[383:352]},
     {_data_array_ext_R0_data[351:320]},
     {_data_array_ext_R0_data[319:288]},
     {_data_array_ext_R0_data[287:256]},
     {_data_array_ext_R0_data[255:224]},
     {_data_array_ext_R0_data[223:192]},
     {_data_array_ext_R0_data[191:160]},
     {_data_array_ext_R0_data[159:128]},
     {_data_array_ext_R0_data[127:96]},
     {_data_array_ext_R0_data[95:64]},
     {_data_array_ext_R0_data[63:32]},
     {_data_array_ext_R0_data[31:0]}};
  wire              _GEN_2 = state == 2'h2;
  wire              _GEN_3 = ~(|state) | _GEN | _GEN_2;
  wire              _GEN_4 = ~_GEN_3 & (&state) & io_line_valid & ~current_mem_req_write;
  wire [15:0][31:0] _GEN_5 =
    {{io_line_result[511:480]},
     {io_line_result[479:448]},
     {io_line_result[447:416]},
     {io_line_result[415:384]},
     {io_line_result[383:352]},
     {io_line_result[351:320]},
     {io_line_result[319:288]},
     {io_line_result[287:256]},
     {io_line_result[255:224]},
     {io_line_result[223:192]},
     {io_line_result[191:160]},
     {io_line_result[159:128]},
     {io_line_result[127:96]},
     {io_line_result[95:64]},
     {io_line_result[63:32]},
     {io_line_result[31:0]}};
  always @(posedge clock) begin
    if (reset) begin
      state <= 2'h0;
      current_mem_req_address <= 32'h0;
      current_mem_req_read <= 1'h0;
      current_mem_req_write <= 1'h0;
    end
    else begin
      automatic logic _GEN_6 = _GEN & _GEN_0;
      automatic logic _GEN_7 = _GEN_6 & io_start;
      if (|state) begin
        if (_GEN)
          state <=
            _GEN_0 ? {1'h0, io_start} : {1'h1, _meta_array_ext_R0_data[19:18] != 2'h3};
        else if (_GEN_2)
          state <= 2'h3;
        else if ((&state) & io_line_valid)
          state <= 2'h0;
      end
      else if (io_start)
        state <= 2'h1;
      if ((~(|state) | _GEN_6) & io_start)
        current_mem_req_address <= io_req_address;
      current_mem_req_read <=
        (|state) ? _GEN_7 | current_mem_req_read : io_start | current_mem_req_read;
      current_mem_req_write <=
        (|state) ? ~_GEN_7 & current_mem_req_write : ~io_start & current_mem_req_write;
    end
    byte_offset_REG <= lookup_address[1:0];
    word_offset_REG <= lookup_address[5:2];
    cache_tag_REG <= lookup_address[31:14];
    line_addr_REG <= lookup_address[31:6];
  end // always @(posedge)
  meta_array_256x20 meta_array_ext (
    .R0_addr (lookup_address[13:6]),
    .R0_en   (read_enable),
    .R0_clk  (clock),
    .R0_data (_meta_array_ext_R0_data),
    .W0_addr (lookup_address[13:6]),
    .W0_en   (_GEN_4),
    .W0_clk  (clock),
    .W0_data ({2'h2, cache_tag_REG})
  );
  data_array_256x512 data_array_ext (
    .R0_addr (lookup_address[13:6]),
    .R0_en   (read_enable),
    .R0_clk  (clock),
    .R0_data (_data_array_ext_R0_data),
    .W0_addr (lookup_address[13:6]),
    .W0_en   (_GEN_4),
    .W0_clk  (clock),
    .W0_data (io_line_result)
  );
  assign io_ready = io_ready_0;
  assign io_done = (|state) & (_GEN ? _GEN_0 : ~_GEN_2 & (&state) & io_line_valid);
  assign io_miss = ~_GEN_3 & (&state) & ~io_line_valid;
  assign io_data =
    (|state)
      ? (_GEN
           ? (~_GEN_0 | current_mem_req_write ? 32'h0 : _GEN_1[word_offset_REG])
           : _GEN_2 | ~(&state) | ~io_line_valid | current_mem_req_write
               ? 32'h0
               : _GEN_5[word_offset_REG])
      : 32'h0;
  assign io_line_addr = {line_addr_REG, 6'h0};
endmodule

