// Generated by CIRCT firtool-1.128.0
module L2Cache(
  input          clock,
                 reset,
  output         io_req_ready,
  input          io_req_valid,
  input  [31:0]  io_req_bits_addr,
  input          io_req_bits_write,
  input  [511:0] io_req_bits_wdata,
  output [511:0] io_mem_resp_in,
  output         io_mem_valid_in,
  input          io_mem_req_ready,
  output         io_mem_req_valid,
  output [31:0]  io_mem_req_bits_addr,
  output         io_mem_req_bits_write,
  output [511:0] io_mem_req_bits_wdata,
  input  [511:0] io_mem_resp,
  input          io_mem_valid
);

  wire         want_fill;
  wire [511:0] _data_array_ext_R0_data;
  wire [17:0]  _meta_array_ext_R0_data;
  reg  [1:0]   state;
  reg  [31:0]  current_mem_req_addr;
  reg          current_mem_req_write;
  reg  [511:0] current_mem_req_wdata;
  wire [31:0]  lookup_address = io_req_valid ? io_req_bits_addr : current_mem_req_addr;
  reg  [31:0]  lookup_address_reg;
  wire         _io_req_ready_T_1 = state == 2'h1;
  wire         read_enable = ~(|state) | _io_req_ready_T_1 | (&state);
  reg  [511:0] wb_data_reg;
  reg  [31:0]  wb_addr_reg;
  wire         hit =
    lookup_address_reg[31:16] == _meta_array_ext_R0_data[15:0]
    & _meta_array_ext_R0_data[17];
  wire         want_wb = state == 2'h2;
  reg          mem_req_accepted;
  wire         io_mem_req_valid_0 = (want_fill | want_wb) & ~mem_req_accepted;
  wire         mem_ack = io_mem_valid & mem_req_accepted;
  wire         _GEN = state == 2'h1;
  wire         _GEN_0 = hit & current_mem_req_write;
  wire         _GEN_1 = state == 2'h2;
  wire         _GEN_2 = ~mem_ack & ~current_mem_req_write;
  assign want_fill = ~(~(|state) | _GEN | _GEN_1) & (&state) & _GEN_2;
  wire         _GEN_3 = ~_GEN_1 & (&state) & ~_GEN_2;
  wire         _GEN_4 = _GEN ? hit & current_mem_req_write : _GEN_3;
  wire         _GEN_5 = _GEN_1 | ~(&state) | _GEN_2;
  always @(posedge clock) begin
    if (reset) begin
      state <= 2'h0;
      current_mem_req_addr <= 32'h0;
      current_mem_req_write <= 1'h0;
      current_mem_req_wdata <= 512'h0;
      wb_data_reg <= 512'h0;
      wb_addr_reg <= 32'h0;
      mem_req_accepted <= 1'h0;
    end
    else begin
      automatic logic _GEN_6;
      _GEN_6 = _meta_array_ext_R0_data[17:16] != 2'h3;
      if (|state) begin
        if (_GEN)
          state <= hit ? {1'h0, io_req_valid} : {1'h1, _GEN_6};
        else if (_GEN_1) begin
          if (mem_ack)
            state <= 2'h3;
        end
        else if (~(&state) | _GEN_2) begin
        end
        else
          state <= 2'h0;
      end
      else if (io_req_valid)
        state <= 2'h1;
      if ((~(|state) | _GEN & hit) & io_req_valid) begin
        current_mem_req_addr <= io_req_bits_addr;
        current_mem_req_write <= io_req_bits_write;
        current_mem_req_wdata <= io_req_bits_wdata;
      end
      if (~(|state) | ~_GEN | hit | _GEN_6) begin
      end
      else begin
        wb_data_reg <= _data_array_ext_R0_data;
        wb_addr_reg <= {_meta_array_ext_R0_data[15:0], current_mem_req_addr[15:6], 6'h0};
      end
      mem_req_accepted <=
        ~mem_ack & (io_mem_req_ready & io_mem_req_valid_0 | mem_req_accepted);
    end
    lookup_address_reg <= lookup_address;
  end // always @(posedge)
  meta_array_1024x18 meta_array_ext (
    .R0_addr (lookup_address[15:6]),
    .R0_en   (read_enable),
    .R0_clk  (clock),
    .R0_data (_meta_array_ext_R0_data),
    .W0_addr (current_mem_req_addr[15:6]),
    .W0_en   ((|state) & _GEN_4),
    .W0_clk  (clock),
    .W0_data
      ((|state)
         ? (_GEN
              ? (_GEN_0 ? {2'h3, current_mem_req_addr[31:16]} : 18'h0)
              : _GEN_5
                  ? 18'h0
                  : current_mem_req_write
                      ? {2'h3, current_mem_req_addr[31:16]}
                      : {2'h2, current_mem_req_addr[31:16]})
         : 18'h0)
  );
  data_array_1024x512 data_array_ext (
    .R0_addr (lookup_address[15:6]),
    .R0_en   (read_enable),
    .R0_clk  (clock),
    .R0_data (_data_array_ext_R0_data),
    .W0_addr (current_mem_req_addr[15:6]),
    .W0_en   ((|state) & _GEN_4),
    .W0_clk  (clock),
    .W0_data
      ((|state)
         ? (_GEN
              ? (_GEN_0 ? current_mem_req_wdata : 512'h0)
              : _GEN_5
                  ? 512'h0
                  : current_mem_req_write ? current_mem_req_wdata : io_mem_resp)
         : 512'h0)
  );
  assign io_req_ready = ~(|state) | _io_req_ready_T_1 & hit & ~current_mem_req_write;
  assign io_mem_resp_in =
    (|state)
      ? (_GEN
           ? (~hit | current_mem_req_write ? 512'h0 : _data_array_ext_R0_data)
           : _GEN_1 | ~(&state) | _GEN_2 | current_mem_req_write ? 512'h0 : io_mem_resp)
      : 512'h0;
  assign io_mem_valid_in = (|state) & (_GEN ? hit : _GEN_3);
  assign io_mem_req_valid = io_mem_req_valid_0;
  assign io_mem_req_bits_addr =
    want_wb ? wb_addr_reg : {current_mem_req_addr[31:6], 6'h0};
  assign io_mem_req_bits_write = want_wb;
  assign io_mem_req_bits_wdata = wb_data_reg;
endmodule

