// Generated by CIRCT firtool-1.128.0
module LSU(
  input         clock,
                reset,
  output        io_req_ready,
  input         io_req_valid,
  input  [31:0] io_req_bits_base_0,
                io_req_bits_base_1,
                io_req_bits_base_2,
                io_req_bits_base_3,
                io_req_bits_base_4,
                io_req_bits_base_5,
                io_req_bits_base_6,
                io_req_bits_base_7,
                io_req_bits_base_8,
                io_req_bits_base_9,
                io_req_bits_base_10,
                io_req_bits_base_11,
                io_req_bits_base_12,
                io_req_bits_base_13,
                io_req_bits_base_14,
                io_req_bits_base_15,
                io_req_bits_wdata_0,
                io_req_bits_wdata_1,
                io_req_bits_wdata_2,
                io_req_bits_wdata_3,
                io_req_bits_wdata_4,
                io_req_bits_wdata_5,
                io_req_bits_wdata_6,
                io_req_bits_wdata_7,
                io_req_bits_wdata_8,
                io_req_bits_wdata_9,
                io_req_bits_wdata_10,
                io_req_bits_wdata_11,
                io_req_bits_wdata_12,
                io_req_bits_wdata_13,
                io_req_bits_wdata_14,
                io_req_bits_wdata_15,
                io_req_bits_imm,
  input  [15:0] io_req_bits_mask,
  input  [6:0]  io_req_bits_rd,
  input  [2:0]  io_req_bits_func3,
  input         io_req_bits_write,
  output [31:0] io_dcache_req_address,
                io_dcache_req_write_data,
  output [2:0]  io_dcache_req_op,
  output        io_dcache_req_read,
                io_dcache_req_write,
                io_dcache_start,
  input         io_dcache_ready,
  output [6:0]  io_dcache_rd,
  output [3:0]  io_dcache_lane,
  output        io_dcache_wen,
                io_busy
);

  wire              _q_q_io_deq_valid;
  wire [31:0]       _q_q_io_deq_bits_base_0;
  wire [31:0]       _q_q_io_deq_bits_base_1;
  wire [31:0]       _q_q_io_deq_bits_base_2;
  wire [31:0]       _q_q_io_deq_bits_base_3;
  wire [31:0]       _q_q_io_deq_bits_base_4;
  wire [31:0]       _q_q_io_deq_bits_base_5;
  wire [31:0]       _q_q_io_deq_bits_base_6;
  wire [31:0]       _q_q_io_deq_bits_base_7;
  wire [31:0]       _q_q_io_deq_bits_base_8;
  wire [31:0]       _q_q_io_deq_bits_base_9;
  wire [31:0]       _q_q_io_deq_bits_base_10;
  wire [31:0]       _q_q_io_deq_bits_base_11;
  wire [31:0]       _q_q_io_deq_bits_base_12;
  wire [31:0]       _q_q_io_deq_bits_base_13;
  wire [31:0]       _q_q_io_deq_bits_base_14;
  wire [31:0]       _q_q_io_deq_bits_base_15;
  wire [31:0]       _q_q_io_deq_bits_wdata_0;
  wire [31:0]       _q_q_io_deq_bits_wdata_1;
  wire [31:0]       _q_q_io_deq_bits_wdata_2;
  wire [31:0]       _q_q_io_deq_bits_wdata_3;
  wire [31:0]       _q_q_io_deq_bits_wdata_4;
  wire [31:0]       _q_q_io_deq_bits_wdata_5;
  wire [31:0]       _q_q_io_deq_bits_wdata_6;
  wire [31:0]       _q_q_io_deq_bits_wdata_7;
  wire [31:0]       _q_q_io_deq_bits_wdata_8;
  wire [31:0]       _q_q_io_deq_bits_wdata_9;
  wire [31:0]       _q_q_io_deq_bits_wdata_10;
  wire [31:0]       _q_q_io_deq_bits_wdata_11;
  wire [31:0]       _q_q_io_deq_bits_wdata_12;
  wire [31:0]       _q_q_io_deq_bits_wdata_13;
  wire [31:0]       _q_q_io_deq_bits_wdata_14;
  wire [31:0]       _q_q_io_deq_bits_wdata_15;
  wire [31:0]       _q_q_io_deq_bits_imm;
  wire [15:0]       _q_q_io_deq_bits_mask;
  wire [6:0]        _q_q_io_deq_bits_rd;
  wire [2:0]        _q_q_io_deq_bits_func3;
  wire              _q_q_io_deq_bits_write;
  reg  [4:0]        lane;
  wire [15:0]       _active_T = _q_q_io_deq_bits_mask >> lane;
  wire              last = lane == 5'hF;
  wire [15:0][31:0] _GEN =
    {{_q_q_io_deq_bits_base_15},
     {_q_q_io_deq_bits_base_14},
     {_q_q_io_deq_bits_base_13},
     {_q_q_io_deq_bits_base_12},
     {_q_q_io_deq_bits_base_11},
     {_q_q_io_deq_bits_base_10},
     {_q_q_io_deq_bits_base_9},
     {_q_q_io_deq_bits_base_8},
     {_q_q_io_deq_bits_base_7},
     {_q_q_io_deq_bits_base_6},
     {_q_q_io_deq_bits_base_5},
     {_q_q_io_deq_bits_base_4},
     {_q_q_io_deq_bits_base_3},
     {_q_q_io_deq_bits_base_2},
     {_q_q_io_deq_bits_base_1},
     {_q_q_io_deq_bits_base_0}};
  wire [15:0][31:0] _GEN_0 =
    {{_q_q_io_deq_bits_wdata_15},
     {_q_q_io_deq_bits_wdata_14},
     {_q_q_io_deq_bits_wdata_13},
     {_q_q_io_deq_bits_wdata_12},
     {_q_q_io_deq_bits_wdata_11},
     {_q_q_io_deq_bits_wdata_10},
     {_q_q_io_deq_bits_wdata_9},
     {_q_q_io_deq_bits_wdata_8},
     {_q_q_io_deq_bits_wdata_7},
     {_q_q_io_deq_bits_wdata_6},
     {_q_q_io_deq_bits_wdata_5},
     {_q_q_io_deq_bits_wdata_4},
     {_q_q_io_deq_bits_wdata_3},
     {_q_q_io_deq_bits_wdata_2},
     {_q_q_io_deq_bits_wdata_1},
     {_q_q_io_deq_bits_wdata_0}};
  wire              _io_dcache_req_op_T_6 = _q_q_io_deq_bits_func3 == 3'h0;
  wire              _io_dcache_req_op_T_8 = _q_q_io_deq_bits_func3 == 3'h1;
  wire              _io_dcache_req_op_T_10 = _q_q_io_deq_bits_func3 == 3'h2;
  wire              step = _q_q_io_deq_valid & (~(_active_T[0]) | io_dcache_ready);
  always @(posedge clock) begin
    if (reset)
      lane <= 5'h0;
    else if (step)
      lane <= last ? 5'h0 : lane + 5'h1;
  end // always @(posedge)
  Queue2_VecMemReq q_q (
    .clock                (clock),
    .reset                (reset),
    .io_enq_ready         (io_req_ready),
    .io_enq_valid         (io_req_valid),
    .io_enq_bits_base_0   (io_req_bits_base_0),
    .io_enq_bits_base_1   (io_req_bits_base_1),
    .io_enq_bits_base_2   (io_req_bits_base_2),
    .io_enq_bits_base_3   (io_req_bits_base_3),
    .io_enq_bits_base_4   (io_req_bits_base_4),
    .io_enq_bits_base_5   (io_req_bits_base_5),
    .io_enq_bits_base_6   (io_req_bits_base_6),
    .io_enq_bits_base_7   (io_req_bits_base_7),
    .io_enq_bits_base_8   (io_req_bits_base_8),
    .io_enq_bits_base_9   (io_req_bits_base_9),
    .io_enq_bits_base_10  (io_req_bits_base_10),
    .io_enq_bits_base_11  (io_req_bits_base_11),
    .io_enq_bits_base_12  (io_req_bits_base_12),
    .io_enq_bits_base_13  (io_req_bits_base_13),
    .io_enq_bits_base_14  (io_req_bits_base_14),
    .io_enq_bits_base_15  (io_req_bits_base_15),
    .io_enq_bits_wdata_0  (io_req_bits_wdata_0),
    .io_enq_bits_wdata_1  (io_req_bits_wdata_1),
    .io_enq_bits_wdata_2  (io_req_bits_wdata_2),
    .io_enq_bits_wdata_3  (io_req_bits_wdata_3),
    .io_enq_bits_wdata_4  (io_req_bits_wdata_4),
    .io_enq_bits_wdata_5  (io_req_bits_wdata_5),
    .io_enq_bits_wdata_6  (io_req_bits_wdata_6),
    .io_enq_bits_wdata_7  (io_req_bits_wdata_7),
    .io_enq_bits_wdata_8  (io_req_bits_wdata_8),
    .io_enq_bits_wdata_9  (io_req_bits_wdata_9),
    .io_enq_bits_wdata_10 (io_req_bits_wdata_10),
    .io_enq_bits_wdata_11 (io_req_bits_wdata_11),
    .io_enq_bits_wdata_12 (io_req_bits_wdata_12),
    .io_enq_bits_wdata_13 (io_req_bits_wdata_13),
    .io_enq_bits_wdata_14 (io_req_bits_wdata_14),
    .io_enq_bits_wdata_15 (io_req_bits_wdata_15),
    .io_enq_bits_imm      (io_req_bits_imm),
    .io_enq_bits_mask     (io_req_bits_mask),
    .io_enq_bits_rd       (io_req_bits_rd),
    .io_enq_bits_func3    (io_req_bits_func3),
    .io_enq_bits_write    (io_req_bits_write),
    .io_deq_ready         (step & last),
    .io_deq_valid         (_q_q_io_deq_valid),
    .io_deq_bits_base_0   (_q_q_io_deq_bits_base_0),
    .io_deq_bits_base_1   (_q_q_io_deq_bits_base_1),
    .io_deq_bits_base_2   (_q_q_io_deq_bits_base_2),
    .io_deq_bits_base_3   (_q_q_io_deq_bits_base_3),
    .io_deq_bits_base_4   (_q_q_io_deq_bits_base_4),
    .io_deq_bits_base_5   (_q_q_io_deq_bits_base_5),
    .io_deq_bits_base_6   (_q_q_io_deq_bits_base_6),
    .io_deq_bits_base_7   (_q_q_io_deq_bits_base_7),
    .io_deq_bits_base_8   (_q_q_io_deq_bits_base_8),
    .io_deq_bits_base_9   (_q_q_io_deq_bits_base_9),
    .io_deq_bits_base_10  (_q_q_io_deq_bits_base_10),
    .io_deq_bits_base_11  (_q_q_io_deq_bits_base_11),
    .io_deq_bits_base_12  (_q_q_io_deq_bits_base_12),
    .io_deq_bits_base_13  (_q_q_io_deq_bits_base_13),
    .io_deq_bits_base_14  (_q_q_io_deq_bits_base_14),
    .io_deq_bits_base_15  (_q_q_io_deq_bits_base_15),
    .io_deq_bits_wdata_0  (_q_q_io_deq_bits_wdata_0),
    .io_deq_bits_wdata_1  (_q_q_io_deq_bits_wdata_1),
    .io_deq_bits_wdata_2  (_q_q_io_deq_bits_wdata_2),
    .io_deq_bits_wdata_3  (_q_q_io_deq_bits_wdata_3),
    .io_deq_bits_wdata_4  (_q_q_io_deq_bits_wdata_4),
    .io_deq_bits_wdata_5  (_q_q_io_deq_bits_wdata_5),
    .io_deq_bits_wdata_6  (_q_q_io_deq_bits_wdata_6),
    .io_deq_bits_wdata_7  (_q_q_io_deq_bits_wdata_7),
    .io_deq_bits_wdata_8  (_q_q_io_deq_bits_wdata_8),
    .io_deq_bits_wdata_9  (_q_q_io_deq_bits_wdata_9),
    .io_deq_bits_wdata_10 (_q_q_io_deq_bits_wdata_10),
    .io_deq_bits_wdata_11 (_q_q_io_deq_bits_wdata_11),
    .io_deq_bits_wdata_12 (_q_q_io_deq_bits_wdata_12),
    .io_deq_bits_wdata_13 (_q_q_io_deq_bits_wdata_13),
    .io_deq_bits_wdata_14 (_q_q_io_deq_bits_wdata_14),
    .io_deq_bits_wdata_15 (_q_q_io_deq_bits_wdata_15),
    .io_deq_bits_imm      (_q_q_io_deq_bits_imm),
    .io_deq_bits_mask     (_q_q_io_deq_bits_mask),
    .io_deq_bits_rd       (_q_q_io_deq_bits_rd),
    .io_deq_bits_func3    (_q_q_io_deq_bits_func3),
    .io_deq_bits_write    (_q_q_io_deq_bits_write)
  );
  assign io_dcache_req_address = _GEN[lane[3:0]] + _q_q_io_deq_bits_imm;
  assign io_dcache_req_write_data = _GEN_0[lane[3:0]];
  assign io_dcache_req_op =
    _q_q_io_deq_bits_write
      ? (_io_dcache_req_op_T_10
           ? 3'h5
           : _io_dcache_req_op_T_8 ? 3'h6 : {1'h1, _io_dcache_req_op_T_6, 1'h1})
      : _q_q_io_deq_bits_func3 == 3'h5
          ? 3'h4
          : {1'h0,
             _q_q_io_deq_bits_func3 == 3'h4
               ? 2'h3
               : _io_dcache_req_op_T_10
                   ? 2'h0
                   : _io_dcache_req_op_T_8 ? 2'h1 : {_io_dcache_req_op_T_6, 1'h0}};
  assign io_dcache_req_read = ~_q_q_io_deq_bits_write;
  assign io_dcache_req_write = _q_q_io_deq_bits_write;
  assign io_dcache_start = _q_q_io_deq_valid & _active_T[0] & io_dcache_ready;
  assign io_dcache_rd = _q_q_io_deq_bits_write ? 7'h0 : _q_q_io_deq_bits_rd;
  assign io_dcache_lane = lane[3:0];
  assign io_dcache_wen = ~_q_q_io_deq_bits_write;
  assign io_busy = _q_q_io_deq_valid;
endmodule

