// Generated by CIRCT firtool-1.128.0
module Main(
  input          clock,
                 reset,
                 io_execute,
                 io_allocate_warps,
  input  [31:0]  io_warp_count,
  output         io_complete,
  input          io_vga_clk,
  output         io_hsync,
                 io_vsync,
  output [23:0]  io_rgb,
  output         io_blanking,
  input          io_mem_req_ready,
  output         io_mem_req_valid,
  output [31:0]  io_mem_req_bits_addr,
  output         io_mem_req_bits_write,
  output [511:0] io_mem_req_bits_wdata,
  input  [511:0] io_mem_resp,
  input          io_mem_valid,
                 io_rxd,
  output         io_txd
);

  wire [11:0] _vga_controller_io_rgb;
  wire [31:0] _core_io_icache_req_address;
  wire        _core_io_icache_start;
  wire [31:0] _core_io_dcache_req_address;
  wire [31:0] _core_io_dcache_req_write_data;
  wire [2:0]  _core_io_dcache_req_op;
  wire        _core_io_dcache_req_read;
  wire        _core_io_dcache_req_write;
  wire        _core_io_dcache_start;
  wire [6:0]  _core_io_dcache_rd;
  wire [3:0]  _core_io_dcache_lane;
  wire        _core_io_dcache_wen;
  wire        _memory_io_icache_ready;
  wire        _memory_io_icache_valid;
  wire [31:0] _memory_io_icache_data;
  wire        _memory_io_dcache_ready;
  wire [31:0] _memory_io_dcache_data;
  wire [6:0]  _memory_io_dcache_rd_out;
  wire [3:0]  _memory_io_dcache_lane_out;
  wire        _memory_io_dcache_wen_out;
  wire [31:0] _memory_io_address_vga;
  wire        _memory_io_write_vga;
  wire [31:0] _memory_io_write_value_vga;
  MemoryWrapper memory (
    .clock                    (clock),
    .reset                    (reset),
    .io_icache_req_address    (_core_io_icache_req_address),
    .io_icache_start          (_core_io_icache_start),
    .io_icache_ready          (_memory_io_icache_ready),
    .io_icache_valid          (_memory_io_icache_valid),
    .io_icache_data           (_memory_io_icache_data),
    .io_dcache_req_address    (_core_io_dcache_req_address),
    .io_dcache_req_write_data (_core_io_dcache_req_write_data),
    .io_dcache_req_op         (_core_io_dcache_req_op),
    .io_dcache_req_read       (_core_io_dcache_req_read),
    .io_dcache_req_write      (_core_io_dcache_req_write),
    .io_dcache_start          (_core_io_dcache_start),
    .io_dcache_ready          (_memory_io_dcache_ready),
    .io_dcache_data           (_memory_io_dcache_data),
    .io_dcache_rd             (_core_io_dcache_rd),
    .io_dcache_lane           (_core_io_dcache_lane),
    .io_dcache_wen            (_core_io_dcache_wen),
    .io_dcache_rd_out         (_memory_io_dcache_rd_out),
    .io_dcache_lane_out       (_memory_io_dcache_lane_out),
    .io_dcache_wen_out        (_memory_io_dcache_wen_out),
    .io_mem_req_ready         (io_mem_req_ready),
    .io_mem_req_valid         (io_mem_req_valid),
    .io_mem_req_bits_addr     (io_mem_req_bits_addr),
    .io_mem_req_bits_write    (io_mem_req_bits_write),
    .io_mem_req_bits_wdata    (io_mem_req_bits_wdata),
    .io_mem_resp              (io_mem_resp),
    .io_mem_valid             (io_mem_valid),
    .io_address_vga           (_memory_io_address_vga),
    .io_write_vga             (_memory_io_write_vga),
    .io_write_value_vga       (_memory_io_write_value_vga),
    .io_rxd                   (io_rxd),
    .io_txd                   (io_txd)
  );
  Core core (
    .clock                    (clock),
    .reset                    (reset),
    .io_execute               (io_execute),
    .io_complete              (io_complete),
    .io_icache_req_address    (_core_io_icache_req_address),
    .io_icache_start          (_core_io_icache_start),
    .io_icache_ready          (_memory_io_icache_ready),
    .io_icache_valid          (_memory_io_icache_valid),
    .io_icache_data           (_memory_io_icache_data),
    .io_dcache_req_address    (_core_io_dcache_req_address),
    .io_dcache_req_write_data (_core_io_dcache_req_write_data),
    .io_dcache_req_op         (_core_io_dcache_req_op),
    .io_dcache_req_read       (_core_io_dcache_req_read),
    .io_dcache_req_write      (_core_io_dcache_req_write),
    .io_dcache_start          (_core_io_dcache_start),
    .io_dcache_ready          (_memory_io_dcache_ready),
    .io_dcache_data           (_memory_io_dcache_data),
    .io_dcache_rd             (_core_io_dcache_rd),
    .io_dcache_lane           (_core_io_dcache_lane),
    .io_dcache_wen            (_core_io_dcache_wen),
    .io_mem_rd                (_memory_io_dcache_rd_out),
    .io_mem_lane              (_memory_io_dcache_lane_out),
    .io_mem_wen               (_memory_io_dcache_wen_out)
  );
  VGAController vga_controller (
    .clock          (clock),
    .reset          (reset),
    .io_address     (_memory_io_address_vga),
    .io_write       (_memory_io_write_vga),
    .io_write_value (_memory_io_write_value_vga[11:0]),
    .io_read_clk    (io_vga_clk),
    .io_hsync       (io_hsync),
    .io_vsync       (io_vsync),
    .io_rgb         (_vga_controller_io_rgb),
    .io_blanking    (io_blanking)
  );
  assign io_rgb = {12'h0, _vga_controller_io_rgb};
endmodule

