// Generated by CIRCT firtool-1.128.0

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_
module MemoryWrapper(
  input          clock,
                 reset,
  input  [31:0]  io_icache_req_address,
  input          io_icache_start,
  output         io_icache_ready,
                 io_icache_valid,
  output [31:0]  io_icache_data,
  input  [31:0]  io_dcache_req_address,
                 io_dcache_req_write_data,
  input  [2:0]   io_dcache_req_op,
  input          io_dcache_req_read,
                 io_dcache_req_write,
                 io_dcache_start,
  output         io_dcache_ready,
  output [31:0]  io_dcache_data,
  input  [6:0]   io_dcache_rd,
  input  [3:0]   io_dcache_lane,
  input          io_dcache_wen,
  output [6:0]   io_dcache_rd_out,
  output [3:0]   io_dcache_lane_out,
  output         io_dcache_wen_out,
  input          io_mem_req_ready,
  output         io_mem_req_valid,
  output [31:0]  io_mem_req_bits_addr,
  output         io_mem_req_bits_write,
  output [511:0] io_mem_req_bits_wdata,
  input  [511:0] io_mem_resp,
  input          io_mem_valid,
  output [31:0]  io_address_vga,
  output         io_write_vga,
  output [31:0]  io_write_value_vga,
  input          io_rxd,
  output         io_txd
);

  wire         _uartTx_io_in_ready;
  wire [255:0] _keyTracker_io_keyDown;
  wire [7:0]   _keyTracker_io_lastCode;
  wire         _keyTracker_io_lastPressed;
  wire         _keyTracker_io_eventValid;
  wire [8:0]   _keyTracker_io_numDown;
  wire [31:0]  _hardwareTimer_io_micros;
  wire         _mem_io_dcache_ready;
  wire         _mem_io_dcache_valid;
  wire [31:0]  _mem_io_dcache_data;
  wire [6:0]   _mem_io_dcache_rd_out;
  wire [3:0]   _mem_io_dcache_lane_out;
  wire         _mem_io_dcache_wen_out;
  reg          bypass_pending;
  reg  [6:0]   bypass_rd;
  reg  [3:0]   bypass_lane;
  reg          bypass_wen;
  reg  [31:0]  bypass_val;
  wire         is_htimer = io_dcache_req_address == 32'h8000004;
  wire         is_keytracker =
    io_dcache_req_address > 32'h8000007 & io_dcache_req_address < 32'h8000034;
  wire         is_uarttx = io_dcache_req_address == 32'h8000034;
  wire         is_debug_char = io_dcache_req_address == 32'h70000000;
  wire         is_debug_num = io_dcache_req_address == 32'h70000008;
  wire         is_excep =
    (|(io_dcache_req_address[31:28])) | is_htimer | is_keytracker | is_uarttx
    | is_debug_char | is_debug_num | io_dcache_req_address == 32'h9000000;
  `ifndef SYNTHESIS
    always @(posedge clock) begin
      if ((`PRINTF_COND_) & is_debug_char & io_dcache_start & ~reset)
        $fwrite(32'h80000002, "%c", io_dcache_req_write_data[7:0]);
      if ((`PRINTF_COND_) & is_debug_num & io_dcache_start & ~reset)
        $fwrite(32'h80000002, "0x%x", io_dcache_req_write_data);
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire         bypass_fire = bypass_pending & ~_mem_io_dcache_valid;
  wire         uartTx_io_in_valid = is_uarttx & _uartTx_io_in_ready;
  always @(posedge clock) begin
    if (reset) begin
      bypass_pending <= 1'h0;
      bypass_rd <= 7'h0;
      bypass_lane <= 4'h0;
      bypass_wen <= 1'h0;
      bypass_val <= 32'h0;
    end
    else begin
      automatic logic dcache_bypass = io_dcache_start & is_excep & io_dcache_wen;
      bypass_pending <= dcache_bypass | ~bypass_fire & bypass_pending;
      if (dcache_bypass) begin
        automatic logic [15:0][31:0] _GEN =
          {{32'h0},
           {32'h0},
           {32'h0},
           {32'h0},
           {32'h0},
           {{23'h0, _keyTracker_io_numDown}},
           {{30'h0, _keyTracker_io_eventValid, _keyTracker_io_lastPressed}},
           {{24'h0, _keyTracker_io_lastCode}},
           {_keyTracker_io_keyDown[255:224]},
           {_keyTracker_io_keyDown[223:192]},
           {_keyTracker_io_keyDown[191:160]},
           {_keyTracker_io_keyDown[159:128]},
           {_keyTracker_io_keyDown[127:96]},
           {_keyTracker_io_keyDown[95:64]},
           {_keyTracker_io_keyDown[63:32]},
           {_keyTracker_io_keyDown[31:0]}};
        automatic logic [5:0]        _keytracker_word_T =
          io_dcache_req_address[5:0] - 6'h8;
        bypass_rd <= io_dcache_rd;
        bypass_lane <= io_dcache_lane;
        bypass_wen <= io_dcache_wen;
        bypass_val <=
          is_htimer
            ? _hardwareTimer_io_micros
            : is_keytracker ? _GEN[_keytracker_word_T[5:2]] : 32'h0;
      end
    end
  end // always @(posedge)
  MemoryInterface mem (
    .clock                    (clock),
    .reset                    (reset),
    .io_icache_req_address    (io_icache_req_address),
    .io_icache_start          (io_icache_start),
    .io_icache_ready          (io_icache_ready),
    .io_icache_valid          (io_icache_valid),
    .io_icache_data           (io_icache_data),
    .io_dcache_req_address    (io_dcache_req_address),
    .io_dcache_req_write_data (io_dcache_req_write_data),
    .io_dcache_req_op         (io_dcache_req_op),
    .io_dcache_req_read       (io_dcache_req_read),
    .io_dcache_req_write      (io_dcache_req_write),
    .io_dcache_start          (io_dcache_start & ~is_excep),
    .io_dcache_ready          (_mem_io_dcache_ready),
    .io_dcache_valid          (_mem_io_dcache_valid),
    .io_dcache_data           (_mem_io_dcache_data),
    .io_dcache_rd             (io_dcache_rd),
    .io_dcache_lane           (io_dcache_lane),
    .io_dcache_wen            (io_dcache_wen),
    .io_dcache_rd_out         (_mem_io_dcache_rd_out),
    .io_dcache_lane_out       (_mem_io_dcache_lane_out),
    .io_dcache_wen_out        (_mem_io_dcache_wen_out),
    .io_mem_req_ready         (io_mem_req_ready),
    .io_mem_req_valid         (io_mem_req_valid),
    .io_mem_req_bits_addr     (io_mem_req_bits_addr),
    .io_mem_req_bits_write    (io_mem_req_bits_write),
    .io_mem_req_bits_wdata    (io_mem_req_bits_wdata),
    .io_mem_resp              (io_mem_resp),
    .io_mem_valid             (io_mem_valid)
  );
  HardwareTimer hardwareTimer (
    .clock     (clock),
    .reset     (reset),
    .io_micros (_hardwareTimer_io_micros)
  );
  UartKeyboardTracker keyTracker (
    .clock          (clock),
    .reset          (reset),
    .io_rxd         (io_rxd),
    .io_keyDown     (_keyTracker_io_keyDown),
    .io_lastCode    (_keyTracker_io_lastCode),
    .io_lastPressed (_keyTracker_io_lastPressed),
    .io_eventValid  (_keyTracker_io_eventValid),
    .io_numDown     (_keyTracker_io_numDown)
  );
  UartTxFifo uartTx (
    .clock       (clock),
    .reset       (reset),
    .io_in_ready (_uartTx_io_in_ready),
    .io_in_valid (uartTx_io_in_valid),
    .io_in_bits  (uartTx_io_in_valid ? io_dcache_req_write_data[7:0] : 8'h0),
    .io_out      (io_txd)
  );
  assign io_dcache_ready = _mem_io_dcache_ready & ~bypass_pending;
  assign io_dcache_data = bypass_fire ? bypass_val : _mem_io_dcache_data;
  assign io_dcache_rd_out = bypass_fire ? bypass_rd : _mem_io_dcache_rd_out;
  assign io_dcache_lane_out = bypass_fire ? bypass_lane : _mem_io_dcache_lane_out;
  assign io_dcache_wen_out = bypass_fire ? bypass_wen : _mem_io_dcache_wen_out;
  assign io_address_vga = io_dcache_req_address - 32'h10000000;
  assign io_write_vga = (|(io_dcache_req_address[31:28])) & io_dcache_start;
  assign io_write_value_vga =
    {20'h0,
     io_dcache_req_write_data[23:20],
     io_dcache_req_write_data[15:12],
     io_dcache_req_write_data[7:4]};
endmodule

