// Generated by CIRCT firtool-1.128.0
module Queue2_VecMemReq(
  input         clock,
                reset,
  output        io_enq_ready,
  input         io_enq_valid,
  input  [31:0] io_enq_bits_base_0,
                io_enq_bits_base_1,
                io_enq_bits_base_2,
                io_enq_bits_base_3,
                io_enq_bits_base_4,
                io_enq_bits_base_5,
                io_enq_bits_base_6,
                io_enq_bits_base_7,
                io_enq_bits_base_8,
                io_enq_bits_base_9,
                io_enq_bits_base_10,
                io_enq_bits_base_11,
                io_enq_bits_base_12,
                io_enq_bits_base_13,
                io_enq_bits_base_14,
                io_enq_bits_base_15,
                io_enq_bits_wdata_0,
                io_enq_bits_wdata_1,
                io_enq_bits_wdata_2,
                io_enq_bits_wdata_3,
                io_enq_bits_wdata_4,
                io_enq_bits_wdata_5,
                io_enq_bits_wdata_6,
                io_enq_bits_wdata_7,
                io_enq_bits_wdata_8,
                io_enq_bits_wdata_9,
                io_enq_bits_wdata_10,
                io_enq_bits_wdata_11,
                io_enq_bits_wdata_12,
                io_enq_bits_wdata_13,
                io_enq_bits_wdata_14,
                io_enq_bits_wdata_15,
                io_enq_bits_imm,
  input  [15:0] io_enq_bits_mask,
  input  [6:0]  io_enq_bits_rd,
  input  [2:0]  io_enq_bits_func3,
  input         io_enq_bits_write,
                io_deq_ready,
  output        io_deq_valid,
  output [31:0] io_deq_bits_base_0,
                io_deq_bits_base_1,
                io_deq_bits_base_2,
                io_deq_bits_base_3,
                io_deq_bits_base_4,
                io_deq_bits_base_5,
                io_deq_bits_base_6,
                io_deq_bits_base_7,
                io_deq_bits_base_8,
                io_deq_bits_base_9,
                io_deq_bits_base_10,
                io_deq_bits_base_11,
                io_deq_bits_base_12,
                io_deq_bits_base_13,
                io_deq_bits_base_14,
                io_deq_bits_base_15,
                io_deq_bits_wdata_0,
                io_deq_bits_wdata_1,
                io_deq_bits_wdata_2,
                io_deq_bits_wdata_3,
                io_deq_bits_wdata_4,
                io_deq_bits_wdata_5,
                io_deq_bits_wdata_6,
                io_deq_bits_wdata_7,
                io_deq_bits_wdata_8,
                io_deq_bits_wdata_9,
                io_deq_bits_wdata_10,
                io_deq_bits_wdata_11,
                io_deq_bits_wdata_12,
                io_deq_bits_wdata_13,
                io_deq_bits_wdata_14,
                io_deq_bits_wdata_15,
                io_deq_bits_imm,
  output [15:0] io_deq_bits_mask,
  output [6:0]  io_deq_bits_rd,
  output [2:0]  io_deq_bits_func3,
  output        io_deq_bits_write
);

  wire [1082:0] _ram_ext_R0_data;
  reg           enq_ptr_value;
  reg           deq_ptr_value;
  reg           maybe_full;
  wire          ptr_match = enq_ptr_value == deq_ptr_value;
  wire          empty = ptr_match & ~maybe_full;
  wire          full = ptr_match & maybe_full;
  wire          do_enq = ~full & io_enq_valid;
  always @(posedge clock) begin
    if (reset) begin
      enq_ptr_value <= 1'h0;
      deq_ptr_value <= 1'h0;
      maybe_full <= 1'h0;
    end
    else begin
      automatic logic do_deq = io_deq_ready & ~empty;
      if (do_enq)
        enq_ptr_value <= enq_ptr_value - 1'h1;
      if (do_deq)
        deq_ptr_value <= deq_ptr_value - 1'h1;
      if (do_enq != do_deq)
        maybe_full <= do_enq;
    end
  end // always @(posedge)
  ram_2x1083 ram_ext (
    .R0_addr (deq_ptr_value),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_ram_ext_R0_data),
    .W0_addr (enq_ptr_value),
    .W0_en   (do_enq),
    .W0_clk  (clock),
    .W0_data
      ({io_enq_bits_base_15,
        io_enq_bits_base_14,
        io_enq_bits_base_13,
        io_enq_bits_base_12,
        io_enq_bits_base_11,
        io_enq_bits_base_10,
        io_enq_bits_base_9,
        io_enq_bits_base_8,
        io_enq_bits_base_7,
        io_enq_bits_base_6,
        io_enq_bits_base_5,
        io_enq_bits_base_4,
        io_enq_bits_base_3,
        io_enq_bits_base_2,
        io_enq_bits_base_1,
        io_enq_bits_base_0,
        io_enq_bits_wdata_15,
        io_enq_bits_wdata_14,
        io_enq_bits_wdata_13,
        io_enq_bits_wdata_12,
        io_enq_bits_wdata_11,
        io_enq_bits_wdata_10,
        io_enq_bits_wdata_9,
        io_enq_bits_wdata_8,
        io_enq_bits_wdata_7,
        io_enq_bits_wdata_6,
        io_enq_bits_wdata_5,
        io_enq_bits_wdata_4,
        io_enq_bits_wdata_3,
        io_enq_bits_wdata_2,
        io_enq_bits_wdata_1,
        io_enq_bits_wdata_0,
        io_enq_bits_imm,
        io_enq_bits_mask,
        io_enq_bits_rd,
        io_enq_bits_func3,
        io_enq_bits_write})
  );
  assign io_enq_ready = ~full;
  assign io_deq_valid = ~empty;
  assign io_deq_bits_base_0 = _ram_ext_R0_data[602:571];
  assign io_deq_bits_base_1 = _ram_ext_R0_data[634:603];
  assign io_deq_bits_base_2 = _ram_ext_R0_data[666:635];
  assign io_deq_bits_base_3 = _ram_ext_R0_data[698:667];
  assign io_deq_bits_base_4 = _ram_ext_R0_data[730:699];
  assign io_deq_bits_base_5 = _ram_ext_R0_data[762:731];
  assign io_deq_bits_base_6 = _ram_ext_R0_data[794:763];
  assign io_deq_bits_base_7 = _ram_ext_R0_data[826:795];
  assign io_deq_bits_base_8 = _ram_ext_R0_data[858:827];
  assign io_deq_bits_base_9 = _ram_ext_R0_data[890:859];
  assign io_deq_bits_base_10 = _ram_ext_R0_data[922:891];
  assign io_deq_bits_base_11 = _ram_ext_R0_data[954:923];
  assign io_deq_bits_base_12 = _ram_ext_R0_data[986:955];
  assign io_deq_bits_base_13 = _ram_ext_R0_data[1018:987];
  assign io_deq_bits_base_14 = _ram_ext_R0_data[1050:1019];
  assign io_deq_bits_base_15 = _ram_ext_R0_data[1082:1051];
  assign io_deq_bits_wdata_0 = _ram_ext_R0_data[90:59];
  assign io_deq_bits_wdata_1 = _ram_ext_R0_data[122:91];
  assign io_deq_bits_wdata_2 = _ram_ext_R0_data[154:123];
  assign io_deq_bits_wdata_3 = _ram_ext_R0_data[186:155];
  assign io_deq_bits_wdata_4 = _ram_ext_R0_data[218:187];
  assign io_deq_bits_wdata_5 = _ram_ext_R0_data[250:219];
  assign io_deq_bits_wdata_6 = _ram_ext_R0_data[282:251];
  assign io_deq_bits_wdata_7 = _ram_ext_R0_data[314:283];
  assign io_deq_bits_wdata_8 = _ram_ext_R0_data[346:315];
  assign io_deq_bits_wdata_9 = _ram_ext_R0_data[378:347];
  assign io_deq_bits_wdata_10 = _ram_ext_R0_data[410:379];
  assign io_deq_bits_wdata_11 = _ram_ext_R0_data[442:411];
  assign io_deq_bits_wdata_12 = _ram_ext_R0_data[474:443];
  assign io_deq_bits_wdata_13 = _ram_ext_R0_data[506:475];
  assign io_deq_bits_wdata_14 = _ram_ext_R0_data[538:507];
  assign io_deq_bits_wdata_15 = _ram_ext_R0_data[570:539];
  assign io_deq_bits_imm = _ram_ext_R0_data[58:27];
  assign io_deq_bits_mask = _ram_ext_R0_data[26:11];
  assign io_deq_bits_rd = _ram_ext_R0_data[10:4];
  assign io_deq_bits_func3 = _ram_ext_R0_data[3:1];
  assign io_deq_bits_write = _ram_ext_R0_data[0];
endmodule

