// Generated by CIRCT firtool-1.128.0
// VCS coverage exclude_file
module ram_64x76(
  input  [5:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [75:0] R0_data,
  input  [5:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [75:0] W0_data
);

  reg [75:0] Memory[0:63];
  always @(posedge W0_clk) begin
    if (W0_en)
      Memory[W0_addr] <= W0_data;
  end // always @(posedge)
  assign R0_data = R0_en ? Memory[R0_addr] : 76'bx;
endmodule

