// Generated by CIRCT firtool-1.128.0
module Read(
  input          clock,
                 reset,
                 io_instruction_valid,
  input  [6:0]   io_instruction_bits_rs1,
                 io_instruction_bits_rs2,
                 io_instruction_bits_rd,
  input          io_instruction_bits_rd_wen,
  input  [31:0]  io_instruction_bits_immediate,
  input  [6:0]   io_instruction_bits_opcode,
  input  [2:0]   io_instruction_bits_func3,
  input  [6:0]   io_instruction_bits_func7,
  input  [31:0]  io_instruction_bits_pc,
  input  [1:0]   io_instruction_bits_warp,
  output [6:0]   io_register_read_a,
                 io_register_read_b,
  input  [31:0]  io_register_value_a_0,
                 io_register_value_a_1,
                 io_register_value_a_2,
                 io_register_value_a_3,
                 io_register_value_a_4,
                 io_register_value_a_5,
                 io_register_value_a_6,
                 io_register_value_a_7,
                 io_register_value_a_8,
                 io_register_value_a_9,
                 io_register_value_a_10,
                 io_register_value_a_11,
                 io_register_value_a_12,
                 io_register_value_a_13,
                 io_register_value_a_14,
                 io_register_value_a_15,
                 io_register_value_b_0,
                 io_register_value_b_1,
                 io_register_value_b_2,
                 io_register_value_b_3,
                 io_register_value_b_4,
                 io_register_value_b_5,
                 io_register_value_b_6,
                 io_register_value_b_7,
                 io_register_value_b_8,
                 io_register_value_b_9,
                 io_register_value_b_10,
                 io_register_value_b_11,
                 io_register_value_b_12,
                 io_register_value_b_13,
                 io_register_value_b_14,
                 io_register_value_b_15,
  output         io_next_instruction_valid,
  output [31:0]  io_next_instruction_bits_rs1_val_0,
                 io_next_instruction_bits_rs1_val_1,
                 io_next_instruction_bits_rs1_val_2,
                 io_next_instruction_bits_rs1_val_3,
                 io_next_instruction_bits_rs1_val_4,
                 io_next_instruction_bits_rs1_val_5,
                 io_next_instruction_bits_rs1_val_6,
                 io_next_instruction_bits_rs1_val_7,
                 io_next_instruction_bits_rs1_val_8,
                 io_next_instruction_bits_rs1_val_9,
                 io_next_instruction_bits_rs1_val_10,
                 io_next_instruction_bits_rs1_val_11,
                 io_next_instruction_bits_rs1_val_12,
                 io_next_instruction_bits_rs1_val_13,
                 io_next_instruction_bits_rs1_val_14,
                 io_next_instruction_bits_rs1_val_15,
                 io_next_instruction_bits_rs2_val_0,
                 io_next_instruction_bits_rs2_val_1,
                 io_next_instruction_bits_rs2_val_2,
                 io_next_instruction_bits_rs2_val_3,
                 io_next_instruction_bits_rs2_val_4,
                 io_next_instruction_bits_rs2_val_5,
                 io_next_instruction_bits_rs2_val_6,
                 io_next_instruction_bits_rs2_val_7,
                 io_next_instruction_bits_rs2_val_8,
                 io_next_instruction_bits_rs2_val_9,
                 io_next_instruction_bits_rs2_val_10,
                 io_next_instruction_bits_rs2_val_11,
                 io_next_instruction_bits_rs2_val_12,
                 io_next_instruction_bits_rs2_val_13,
                 io_next_instruction_bits_rs2_val_14,
                 io_next_instruction_bits_rs2_val_15,
  output [6:0]   io_next_instruction_bits_rd,
  output [31:0]  io_next_instruction_bits_immediate,
  output [6:0]   io_next_instruction_bits_opcode,
  output [2:0]   io_next_instruction_bits_func3,
  output [6:0]   io_next_instruction_bits_func7,
  output [31:0]  io_next_instruction_bits_pc,
  output [1:0]   io_next_instruction_bits_warp,
  input          io_flush,
                 io_stall,
  input  [127:0] io_rum,
  output         io_raw_hazard_stall
);

  wire [127:0] _raw_hazard_T = io_rum >> io_instruction_bits_rs1;
  wire [127:0] _raw_hazard_T_5 = io_rum >> io_instruction_bits_rs2;
  wire [127:0] _raw_hazard_T_11 = io_rum >> io_instruction_bits_rd;
  wire         raw_hazard =
    io_instruction_valid
    & (_raw_hazard_T[0] & (|(io_instruction_bits_rs1[4:0])) | _raw_hazard_T_5[0]
       & (|(io_instruction_bits_rs2[4:0])) | io_instruction_bits_rd_wen
       & _raw_hazard_T_11[0] & (|(io_instruction_bits_rd[4:0])));
  reg  [6:0]   bundle_rd;
  reg  [31:0]  bundle_immediate;
  reg  [6:0]   bundle_opcode;
  reg  [2:0]   bundle_func3;
  reg  [6:0]   bundle_func7;
  reg  [31:0]  bundle_pc;
  reg  [1:0]   bundle_warp;
  reg          valid;
  always @(posedge clock) begin
    if (reset) begin
      bundle_rd <= 7'h0;
      bundle_immediate <= 32'h0;
      bundle_opcode <= 7'h0;
      bundle_func3 <= 3'h0;
      bundle_func7 <= 7'h0;
      bundle_pc <= 32'h0;
      bundle_warp <= 2'h0;
      valid <= 1'h0;
    end
    else begin
      if (~(io_flush | io_stall | raw_hazard)) begin
        bundle_rd <= io_instruction_bits_rd;
        bundle_immediate <= io_instruction_bits_immediate;
        bundle_opcode <= io_instruction_bits_opcode;
        bundle_func3 <= io_instruction_bits_func3;
        bundle_func7 <= io_instruction_bits_func7;
        bundle_pc <= io_instruction_bits_pc;
        bundle_warp <= io_instruction_bits_warp;
      end
      valid <= ~io_flush & (io_stall ? valid : ~raw_hazard & io_instruction_valid);
    end
  end // always @(posedge)
  assign io_register_read_a = io_instruction_bits_rs1;
  assign io_register_read_b = io_instruction_bits_rs2;
  assign io_next_instruction_valid = valid;
  assign io_next_instruction_bits_rs1_val_0 = io_register_value_a_0;
  assign io_next_instruction_bits_rs1_val_1 = io_register_value_a_1;
  assign io_next_instruction_bits_rs1_val_2 = io_register_value_a_2;
  assign io_next_instruction_bits_rs1_val_3 = io_register_value_a_3;
  assign io_next_instruction_bits_rs1_val_4 = io_register_value_a_4;
  assign io_next_instruction_bits_rs1_val_5 = io_register_value_a_5;
  assign io_next_instruction_bits_rs1_val_6 = io_register_value_a_6;
  assign io_next_instruction_bits_rs1_val_7 = io_register_value_a_7;
  assign io_next_instruction_bits_rs1_val_8 = io_register_value_a_8;
  assign io_next_instruction_bits_rs1_val_9 = io_register_value_a_9;
  assign io_next_instruction_bits_rs1_val_10 = io_register_value_a_10;
  assign io_next_instruction_bits_rs1_val_11 = io_register_value_a_11;
  assign io_next_instruction_bits_rs1_val_12 = io_register_value_a_12;
  assign io_next_instruction_bits_rs1_val_13 = io_register_value_a_13;
  assign io_next_instruction_bits_rs1_val_14 = io_register_value_a_14;
  assign io_next_instruction_bits_rs1_val_15 = io_register_value_a_15;
  assign io_next_instruction_bits_rs2_val_0 = io_register_value_b_0;
  assign io_next_instruction_bits_rs2_val_1 = io_register_value_b_1;
  assign io_next_instruction_bits_rs2_val_2 = io_register_value_b_2;
  assign io_next_instruction_bits_rs2_val_3 = io_register_value_b_3;
  assign io_next_instruction_bits_rs2_val_4 = io_register_value_b_4;
  assign io_next_instruction_bits_rs2_val_5 = io_register_value_b_5;
  assign io_next_instruction_bits_rs2_val_6 = io_register_value_b_6;
  assign io_next_instruction_bits_rs2_val_7 = io_register_value_b_7;
  assign io_next_instruction_bits_rs2_val_8 = io_register_value_b_8;
  assign io_next_instruction_bits_rs2_val_9 = io_register_value_b_9;
  assign io_next_instruction_bits_rs2_val_10 = io_register_value_b_10;
  assign io_next_instruction_bits_rs2_val_11 = io_register_value_b_11;
  assign io_next_instruction_bits_rs2_val_12 = io_register_value_b_12;
  assign io_next_instruction_bits_rs2_val_13 = io_register_value_b_13;
  assign io_next_instruction_bits_rs2_val_14 = io_register_value_b_14;
  assign io_next_instruction_bits_rs2_val_15 = io_register_value_b_15;
  assign io_next_instruction_bits_rd = bundle_rd;
  assign io_next_instruction_bits_immediate = bundle_immediate;
  assign io_next_instruction_bits_opcode = bundle_opcode;
  assign io_next_instruction_bits_func3 = bundle_func3;
  assign io_next_instruction_bits_func7 = bundle_func7;
  assign io_next_instruction_bits_pc = bundle_pc;
  assign io_next_instruction_bits_warp = bundle_warp;
  assign io_raw_hazard_stall = raw_hazard;
endmodule

