// Generated by CIRCT firtool-1.128.0
module Registers(
  input         clock,
                reset,
                io_write_enable,
  input  [6:0]  io_write_address,
  input  [15:0] io_write_mask,
  input  [31:0] io_in_0,
                io_in_1,
                io_in_2,
                io_in_3,
                io_in_4,
                io_in_5,
                io_in_6,
                io_in_7,
                io_in_8,
                io_in_9,
                io_in_10,
                io_in_11,
                io_in_12,
                io_in_13,
                io_in_14,
                io_in_15,
  input         io_write_enable2,
  input  [6:0]  io_write_address2,
  input  [15:0] io_write_mask2,
  input  [31:0] io_in2_0,
                io_in2_1,
                io_in2_2,
                io_in2_3,
                io_in2_4,
                io_in2_5,
                io_in2_6,
                io_in2_7,
                io_in2_8,
                io_in2_9,
                io_in2_10,
                io_in2_11,
                io_in2_12,
                io_in2_13,
                io_in2_14,
                io_in2_15,
  input  [6:0]  io_read_address_a,
                io_read_address_b,
  output [31:0] io_out_a_0,
                io_out_a_1,
                io_out_a_2,
                io_out_a_3,
                io_out_a_4,
                io_out_a_5,
                io_out_a_6,
                io_out_a_7,
                io_out_a_8,
                io_out_a_9,
                io_out_a_10,
                io_out_a_11,
                io_out_a_12,
                io_out_a_13,
                io_out_a_14,
                io_out_a_15,
                io_out_b_0,
                io_out_b_1,
                io_out_b_2,
                io_out_b_3,
                io_out_b_4,
                io_out_b_5,
                io_out_b_6,
                io_out_b_7,
                io_out_b_8,
                io_out_b_9,
                io_out_b_10,
                io_out_b_11,
                io_out_b_12,
                io_out_b_13,
                io_out_b_14,
                io_out_b_15
);

  wire [31:0] _bank1_15_ext_R0_data;
  wire [31:0] _bank1_15_ext_R1_data;
  wire [31:0] _bank1_14_ext_R0_data;
  wire [31:0] _bank1_14_ext_R1_data;
  wire [31:0] _bank1_13_ext_R0_data;
  wire [31:0] _bank1_13_ext_R1_data;
  wire [31:0] _bank1_12_ext_R0_data;
  wire [31:0] _bank1_12_ext_R1_data;
  wire [31:0] _bank1_11_ext_R0_data;
  wire [31:0] _bank1_11_ext_R1_data;
  wire [31:0] _bank1_10_ext_R0_data;
  wire [31:0] _bank1_10_ext_R1_data;
  wire [31:0] _bank1_9_ext_R0_data;
  wire [31:0] _bank1_9_ext_R1_data;
  wire [31:0] _bank1_8_ext_R0_data;
  wire [31:0] _bank1_8_ext_R1_data;
  wire [31:0] _bank1_7_ext_R0_data;
  wire [31:0] _bank1_7_ext_R1_data;
  wire [31:0] _bank1_6_ext_R0_data;
  wire [31:0] _bank1_6_ext_R1_data;
  wire [31:0] _bank1_5_ext_R0_data;
  wire [31:0] _bank1_5_ext_R1_data;
  wire [31:0] _bank1_4_ext_R0_data;
  wire [31:0] _bank1_4_ext_R1_data;
  wire [31:0] _bank1_3_ext_R0_data;
  wire [31:0] _bank1_3_ext_R1_data;
  wire [31:0] _bank1_2_ext_R0_data;
  wire [31:0] _bank1_2_ext_R1_data;
  wire [31:0] _bank1_1_ext_R0_data;
  wire [31:0] _bank1_1_ext_R1_data;
  wire [31:0] _bank1_0_ext_R0_data;
  wire [31:0] _bank1_0_ext_R1_data;
  wire [31:0] _bank0_15_ext_R0_data;
  wire [31:0] _bank0_15_ext_R1_data;
  wire [31:0] _bank0_14_ext_R0_data;
  wire [31:0] _bank0_14_ext_R1_data;
  wire [31:0] _bank0_13_ext_R0_data;
  wire [31:0] _bank0_13_ext_R1_data;
  wire [31:0] _bank0_12_ext_R0_data;
  wire [31:0] _bank0_12_ext_R1_data;
  wire [31:0] _bank0_11_ext_R0_data;
  wire [31:0] _bank0_11_ext_R1_data;
  wire [31:0] _bank0_10_ext_R0_data;
  wire [31:0] _bank0_10_ext_R1_data;
  wire [31:0] _bank0_9_ext_R0_data;
  wire [31:0] _bank0_9_ext_R1_data;
  wire [31:0] _bank0_8_ext_R0_data;
  wire [31:0] _bank0_8_ext_R1_data;
  wire [31:0] _bank0_7_ext_R0_data;
  wire [31:0] _bank0_7_ext_R1_data;
  wire [31:0] _bank0_6_ext_R0_data;
  wire [31:0] _bank0_6_ext_R1_data;
  wire [31:0] _bank0_5_ext_R0_data;
  wire [31:0] _bank0_5_ext_R1_data;
  wire [31:0] _bank0_4_ext_R0_data;
  wire [31:0] _bank0_4_ext_R1_data;
  wire [31:0] _bank0_3_ext_R0_data;
  wire [31:0] _bank0_3_ext_R1_data;
  wire [31:0] _bank0_2_ext_R0_data;
  wire [31:0] _bank0_2_ext_R1_data;
  wire [31:0] _bank0_1_ext_R0_data;
  wire [31:0] _bank0_1_ext_R1_data;
  wire [31:0] _bank0_0_ext_R0_data;
  wire [31:0] _bank0_0_ext_R1_data;
  reg  [15:0] lvt_0;
  reg  [15:0] lvt_1;
  reg  [15:0] lvt_2;
  reg  [15:0] lvt_3;
  reg  [15:0] lvt_4;
  reg  [15:0] lvt_5;
  reg  [15:0] lvt_6;
  reg  [15:0] lvt_7;
  reg  [15:0] lvt_8;
  reg  [15:0] lvt_9;
  reg  [15:0] lvt_10;
  reg  [15:0] lvt_11;
  reg  [15:0] lvt_12;
  reg  [15:0] lvt_13;
  reg  [15:0] lvt_14;
  reg  [15:0] lvt_15;
  reg  [15:0] lvt_16;
  reg  [15:0] lvt_17;
  reg  [15:0] lvt_18;
  reg  [15:0] lvt_19;
  reg  [15:0] lvt_20;
  reg  [15:0] lvt_21;
  reg  [15:0] lvt_22;
  reg  [15:0] lvt_23;
  reg  [15:0] lvt_24;
  reg  [15:0] lvt_25;
  reg  [15:0] lvt_26;
  reg  [15:0] lvt_27;
  reg  [15:0] lvt_28;
  reg  [15:0] lvt_29;
  reg  [15:0] lvt_30;
  reg  [15:0] lvt_31;
  reg  [15:0] lvt_32;
  reg  [15:0] lvt_33;
  reg  [15:0] lvt_34;
  reg  [15:0] lvt_35;
  reg  [15:0] lvt_36;
  reg  [15:0] lvt_37;
  reg  [15:0] lvt_38;
  reg  [15:0] lvt_39;
  reg  [15:0] lvt_40;
  reg  [15:0] lvt_41;
  reg  [15:0] lvt_42;
  reg  [15:0] lvt_43;
  reg  [15:0] lvt_44;
  reg  [15:0] lvt_45;
  reg  [15:0] lvt_46;
  reg  [15:0] lvt_47;
  reg  [15:0] lvt_48;
  reg  [15:0] lvt_49;
  reg  [15:0] lvt_50;
  reg  [15:0] lvt_51;
  reg  [15:0] lvt_52;
  reg  [15:0] lvt_53;
  reg  [15:0] lvt_54;
  reg  [15:0] lvt_55;
  reg  [15:0] lvt_56;
  reg  [15:0] lvt_57;
  reg  [15:0] lvt_58;
  reg  [15:0] lvt_59;
  reg  [15:0] lvt_60;
  reg  [15:0] lvt_61;
  reg  [15:0] lvt_62;
  reg  [15:0] lvt_63;
  reg  [15:0] lvt_64;
  reg  [15:0] lvt_65;
  reg  [15:0] lvt_66;
  reg  [15:0] lvt_67;
  reg  [15:0] lvt_68;
  reg  [15:0] lvt_69;
  reg  [15:0] lvt_70;
  reg  [15:0] lvt_71;
  reg  [15:0] lvt_72;
  reg  [15:0] lvt_73;
  reg  [15:0] lvt_74;
  reg  [15:0] lvt_75;
  reg  [15:0] lvt_76;
  reg  [15:0] lvt_77;
  reg  [15:0] lvt_78;
  reg  [15:0] lvt_79;
  reg  [15:0] lvt_80;
  reg  [15:0] lvt_81;
  reg  [15:0] lvt_82;
  reg  [15:0] lvt_83;
  reg  [15:0] lvt_84;
  reg  [15:0] lvt_85;
  reg  [15:0] lvt_86;
  reg  [15:0] lvt_87;
  reg  [15:0] lvt_88;
  reg  [15:0] lvt_89;
  reg  [15:0] lvt_90;
  reg  [15:0] lvt_91;
  reg  [15:0] lvt_92;
  reg  [15:0] lvt_93;
  reg  [15:0] lvt_94;
  reg  [15:0] lvt_95;
  reg  [15:0] lvt_96;
  reg  [15:0] lvt_97;
  reg  [15:0] lvt_98;
  reg  [15:0] lvt_99;
  reg  [15:0] lvt_100;
  reg  [15:0] lvt_101;
  reg  [15:0] lvt_102;
  reg  [15:0] lvt_103;
  reg  [15:0] lvt_104;
  reg  [15:0] lvt_105;
  reg  [15:0] lvt_106;
  reg  [15:0] lvt_107;
  reg  [15:0] lvt_108;
  reg  [15:0] lvt_109;
  reg  [15:0] lvt_110;
  reg  [15:0] lvt_111;
  reg  [15:0] lvt_112;
  reg  [15:0] lvt_113;
  reg  [15:0] lvt_114;
  reg  [15:0] lvt_115;
  reg  [15:0] lvt_116;
  reg  [15:0] lvt_117;
  reg  [15:0] lvt_118;
  reg  [15:0] lvt_119;
  reg  [15:0] lvt_120;
  reg  [15:0] lvt_121;
  reg  [15:0] lvt_122;
  reg  [15:0] lvt_123;
  reg  [15:0] lvt_124;
  reg  [15:0] lvt_125;
  reg  [15:0] lvt_126;
  reg  [15:0] lvt_127;
  wire        w1 = io_write_enable & (|(io_write_address[4:0]));
  wire        w2 = io_write_enable2 & (|(io_write_address2[4:0]));
  wire        same = io_write_address == io_write_address2;
  wire        _mask2_T = w1 & same;
  wire [15:0] mask2 = ({16{~_mask2_T}} | ~io_write_mask) & io_write_mask2;
  reg  [15:0] sel_a;
  reg  [15:0] sel_b;
  reg         a_x0;
  reg         b_x0;
  always @(posedge clock) begin
    if (reset) begin
      lvt_0 <= 16'h0;
      lvt_1 <= 16'h0;
      lvt_2 <= 16'h0;
      lvt_3 <= 16'h0;
      lvt_4 <= 16'h0;
      lvt_5 <= 16'h0;
      lvt_6 <= 16'h0;
      lvt_7 <= 16'h0;
      lvt_8 <= 16'h0;
      lvt_9 <= 16'h0;
      lvt_10 <= 16'h0;
      lvt_11 <= 16'h0;
      lvt_12 <= 16'h0;
      lvt_13 <= 16'h0;
      lvt_14 <= 16'h0;
      lvt_15 <= 16'h0;
      lvt_16 <= 16'h0;
      lvt_17 <= 16'h0;
      lvt_18 <= 16'h0;
      lvt_19 <= 16'h0;
      lvt_20 <= 16'h0;
      lvt_21 <= 16'h0;
      lvt_22 <= 16'h0;
      lvt_23 <= 16'h0;
      lvt_24 <= 16'h0;
      lvt_25 <= 16'h0;
      lvt_26 <= 16'h0;
      lvt_27 <= 16'h0;
      lvt_28 <= 16'h0;
      lvt_29 <= 16'h0;
      lvt_30 <= 16'h0;
      lvt_31 <= 16'h0;
      lvt_32 <= 16'h0;
      lvt_33 <= 16'h0;
      lvt_34 <= 16'h0;
      lvt_35 <= 16'h0;
      lvt_36 <= 16'h0;
      lvt_37 <= 16'h0;
      lvt_38 <= 16'h0;
      lvt_39 <= 16'h0;
      lvt_40 <= 16'h0;
      lvt_41 <= 16'h0;
      lvt_42 <= 16'h0;
      lvt_43 <= 16'h0;
      lvt_44 <= 16'h0;
      lvt_45 <= 16'h0;
      lvt_46 <= 16'h0;
      lvt_47 <= 16'h0;
      lvt_48 <= 16'h0;
      lvt_49 <= 16'h0;
      lvt_50 <= 16'h0;
      lvt_51 <= 16'h0;
      lvt_52 <= 16'h0;
      lvt_53 <= 16'h0;
      lvt_54 <= 16'h0;
      lvt_55 <= 16'h0;
      lvt_56 <= 16'h0;
      lvt_57 <= 16'h0;
      lvt_58 <= 16'h0;
      lvt_59 <= 16'h0;
      lvt_60 <= 16'h0;
      lvt_61 <= 16'h0;
      lvt_62 <= 16'h0;
      lvt_63 <= 16'h0;
      lvt_64 <= 16'h0;
      lvt_65 <= 16'h0;
      lvt_66 <= 16'h0;
      lvt_67 <= 16'h0;
      lvt_68 <= 16'h0;
      lvt_69 <= 16'h0;
      lvt_70 <= 16'h0;
      lvt_71 <= 16'h0;
      lvt_72 <= 16'h0;
      lvt_73 <= 16'h0;
      lvt_74 <= 16'h0;
      lvt_75 <= 16'h0;
      lvt_76 <= 16'h0;
      lvt_77 <= 16'h0;
      lvt_78 <= 16'h0;
      lvt_79 <= 16'h0;
      lvt_80 <= 16'h0;
      lvt_81 <= 16'h0;
      lvt_82 <= 16'h0;
      lvt_83 <= 16'h0;
      lvt_84 <= 16'h0;
      lvt_85 <= 16'h0;
      lvt_86 <= 16'h0;
      lvt_87 <= 16'h0;
      lvt_88 <= 16'h0;
      lvt_89 <= 16'h0;
      lvt_90 <= 16'h0;
      lvt_91 <= 16'h0;
      lvt_92 <= 16'h0;
      lvt_93 <= 16'h0;
      lvt_94 <= 16'h0;
      lvt_95 <= 16'h0;
      lvt_96 <= 16'h0;
      lvt_97 <= 16'h0;
      lvt_98 <= 16'h0;
      lvt_99 <= 16'h0;
      lvt_100 <= 16'h0;
      lvt_101 <= 16'h0;
      lvt_102 <= 16'h0;
      lvt_103 <= 16'h0;
      lvt_104 <= 16'h0;
      lvt_105 <= 16'h0;
      lvt_106 <= 16'h0;
      lvt_107 <= 16'h0;
      lvt_108 <= 16'h0;
      lvt_109 <= 16'h0;
      lvt_110 <= 16'h0;
      lvt_111 <= 16'h0;
      lvt_112 <= 16'h0;
      lvt_113 <= 16'h0;
      lvt_114 <= 16'h0;
      lvt_115 <= 16'h0;
      lvt_116 <= 16'h0;
      lvt_117 <= 16'h0;
      lvt_118 <= 16'h0;
      lvt_119 <= 16'h0;
      lvt_120 <= 16'h0;
      lvt_121 <= 16'h0;
      lvt_122 <= 16'h0;
      lvt_123 <= 16'h0;
      lvt_124 <= 16'h0;
      lvt_125 <= 16'h0;
      lvt_126 <= 16'h0;
      lvt_127 <= 16'h0;
      sel_a <= 16'h0;
      sel_b <= 16'h0;
      a_x0 <= 1'h1;
      b_x0 <= 1'h1;
    end
    else begin
      automatic logic [127:0][15:0] _GEN =
        {{lvt_127},
         {lvt_126},
         {lvt_125},
         {lvt_124},
         {lvt_123},
         {lvt_122},
         {lvt_121},
         {lvt_120},
         {lvt_119},
         {lvt_118},
         {lvt_117},
         {lvt_116},
         {lvt_115},
         {lvt_114},
         {lvt_113},
         {lvt_112},
         {lvt_111},
         {lvt_110},
         {lvt_109},
         {lvt_108},
         {lvt_107},
         {lvt_106},
         {lvt_105},
         {lvt_104},
         {lvt_103},
         {lvt_102},
         {lvt_101},
         {lvt_100},
         {lvt_99},
         {lvt_98},
         {lvt_97},
         {lvt_96},
         {lvt_95},
         {lvt_94},
         {lvt_93},
         {lvt_92},
         {lvt_91},
         {lvt_90},
         {lvt_89},
         {lvt_88},
         {lvt_87},
         {lvt_86},
         {lvt_85},
         {lvt_84},
         {lvt_83},
         {lvt_82},
         {lvt_81},
         {lvt_80},
         {lvt_79},
         {lvt_78},
         {lvt_77},
         {lvt_76},
         {lvt_75},
         {lvt_74},
         {lvt_73},
         {lvt_72},
         {lvt_71},
         {lvt_70},
         {lvt_69},
         {lvt_68},
         {lvt_67},
         {lvt_66},
         {lvt_65},
         {lvt_64},
         {lvt_63},
         {lvt_62},
         {lvt_61},
         {lvt_60},
         {lvt_59},
         {lvt_58},
         {lvt_57},
         {lvt_56},
         {lvt_55},
         {lvt_54},
         {lvt_53},
         {lvt_52},
         {lvt_51},
         {lvt_50},
         {lvt_49},
         {lvt_48},
         {lvt_47},
         {lvt_46},
         {lvt_45},
         {lvt_44},
         {lvt_43},
         {lvt_42},
         {lvt_41},
         {lvt_40},
         {lvt_39},
         {lvt_38},
         {lvt_37},
         {lvt_36},
         {lvt_35},
         {lvt_34},
         {lvt_33},
         {lvt_32},
         {lvt_31},
         {lvt_30},
         {lvt_29},
         {lvt_28},
         {lvt_27},
         {lvt_26},
         {lvt_25},
         {lvt_24},
         {lvt_23},
         {lvt_22},
         {lvt_21},
         {lvt_20},
         {lvt_19},
         {lvt_18},
         {lvt_17},
         {lvt_16},
         {lvt_15},
         {lvt_14},
         {lvt_13},
         {lvt_12},
         {lvt_11},
         {lvt_10},
         {lvt_9},
         {lvt_8},
         {lvt_7},
         {lvt_6},
         {lvt_5},
         {lvt_4},
         {lvt_3},
         {lvt_2},
         {lvt_1},
         {lvt_0}};
      automatic logic [15:0]        _lvt_T_4;
      automatic logic               _GEN_0 = w2 & ~_mask2_T;
      automatic logic [15:0]        _lvt_T_5;
      _lvt_T_4 = _GEN[io_write_address] & ~io_write_mask | (w2 & same ? mask2 : 16'h0);
      _lvt_T_5 = _GEN[io_write_address2] | mask2;
      if (_GEN_0 & io_write_address2 == 7'h0)
        lvt_0 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h0)
        lvt_0 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h1)
        lvt_1 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h1)
        lvt_1 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h2)
        lvt_2 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h2)
        lvt_2 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h3)
        lvt_3 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h3)
        lvt_3 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h4)
        lvt_4 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h4)
        lvt_4 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h5)
        lvt_5 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h5)
        lvt_5 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h6)
        lvt_6 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h6)
        lvt_6 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h7)
        lvt_7 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h7)
        lvt_7 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h8)
        lvt_8 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h8)
        lvt_8 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h9)
        lvt_9 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h9)
        lvt_9 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'hA)
        lvt_10 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'hA)
        lvt_10 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'hB)
        lvt_11 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'hB)
        lvt_11 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'hC)
        lvt_12 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'hC)
        lvt_12 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'hD)
        lvt_13 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'hD)
        lvt_13 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'hE)
        lvt_14 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'hE)
        lvt_14 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'hF)
        lvt_15 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'hF)
        lvt_15 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h10)
        lvt_16 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h10)
        lvt_16 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h11)
        lvt_17 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h11)
        lvt_17 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h12)
        lvt_18 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h12)
        lvt_18 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h13)
        lvt_19 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h13)
        lvt_19 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h14)
        lvt_20 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h14)
        lvt_20 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h15)
        lvt_21 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h15)
        lvt_21 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h16)
        lvt_22 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h16)
        lvt_22 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h17)
        lvt_23 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h17)
        lvt_23 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h18)
        lvt_24 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h18)
        lvt_24 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h19)
        lvt_25 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h19)
        lvt_25 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h1A)
        lvt_26 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h1A)
        lvt_26 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h1B)
        lvt_27 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h1B)
        lvt_27 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h1C)
        lvt_28 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h1C)
        lvt_28 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h1D)
        lvt_29 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h1D)
        lvt_29 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h1E)
        lvt_30 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h1E)
        lvt_30 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h1F)
        lvt_31 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h1F)
        lvt_31 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h20)
        lvt_32 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h20)
        lvt_32 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h21)
        lvt_33 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h21)
        lvt_33 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h22)
        lvt_34 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h22)
        lvt_34 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h23)
        lvt_35 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h23)
        lvt_35 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h24)
        lvt_36 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h24)
        lvt_36 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h25)
        lvt_37 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h25)
        lvt_37 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h26)
        lvt_38 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h26)
        lvt_38 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h27)
        lvt_39 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h27)
        lvt_39 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h28)
        lvt_40 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h28)
        lvt_40 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h29)
        lvt_41 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h29)
        lvt_41 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h2A)
        lvt_42 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h2A)
        lvt_42 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h2B)
        lvt_43 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h2B)
        lvt_43 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h2C)
        lvt_44 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h2C)
        lvt_44 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h2D)
        lvt_45 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h2D)
        lvt_45 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h2E)
        lvt_46 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h2E)
        lvt_46 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h2F)
        lvt_47 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h2F)
        lvt_47 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h30)
        lvt_48 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h30)
        lvt_48 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h31)
        lvt_49 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h31)
        lvt_49 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h32)
        lvt_50 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h32)
        lvt_50 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h33)
        lvt_51 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h33)
        lvt_51 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h34)
        lvt_52 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h34)
        lvt_52 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h35)
        lvt_53 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h35)
        lvt_53 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h36)
        lvt_54 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h36)
        lvt_54 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h37)
        lvt_55 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h37)
        lvt_55 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h38)
        lvt_56 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h38)
        lvt_56 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h39)
        lvt_57 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h39)
        lvt_57 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h3A)
        lvt_58 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h3A)
        lvt_58 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h3B)
        lvt_59 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h3B)
        lvt_59 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h3C)
        lvt_60 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h3C)
        lvt_60 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h3D)
        lvt_61 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h3D)
        lvt_61 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h3E)
        lvt_62 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h3E)
        lvt_62 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h3F)
        lvt_63 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h3F)
        lvt_63 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h40)
        lvt_64 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h40)
        lvt_64 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h41)
        lvt_65 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h41)
        lvt_65 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h42)
        lvt_66 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h42)
        lvt_66 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h43)
        lvt_67 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h43)
        lvt_67 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h44)
        lvt_68 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h44)
        lvt_68 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h45)
        lvt_69 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h45)
        lvt_69 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h46)
        lvt_70 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h46)
        lvt_70 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h47)
        lvt_71 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h47)
        lvt_71 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h48)
        lvt_72 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h48)
        lvt_72 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h49)
        lvt_73 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h49)
        lvt_73 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h4A)
        lvt_74 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h4A)
        lvt_74 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h4B)
        lvt_75 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h4B)
        lvt_75 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h4C)
        lvt_76 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h4C)
        lvt_76 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h4D)
        lvt_77 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h4D)
        lvt_77 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h4E)
        lvt_78 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h4E)
        lvt_78 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h4F)
        lvt_79 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h4F)
        lvt_79 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h50)
        lvt_80 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h50)
        lvt_80 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h51)
        lvt_81 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h51)
        lvt_81 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h52)
        lvt_82 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h52)
        lvt_82 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h53)
        lvt_83 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h53)
        lvt_83 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h54)
        lvt_84 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h54)
        lvt_84 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h55)
        lvt_85 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h55)
        lvt_85 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h56)
        lvt_86 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h56)
        lvt_86 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h57)
        lvt_87 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h57)
        lvt_87 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h58)
        lvt_88 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h58)
        lvt_88 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h59)
        lvt_89 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h59)
        lvt_89 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h5A)
        lvt_90 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h5A)
        lvt_90 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h5B)
        lvt_91 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h5B)
        lvt_91 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h5C)
        lvt_92 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h5C)
        lvt_92 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h5D)
        lvt_93 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h5D)
        lvt_93 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h5E)
        lvt_94 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h5E)
        lvt_94 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h5F)
        lvt_95 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h5F)
        lvt_95 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h60)
        lvt_96 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h60)
        lvt_96 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h61)
        lvt_97 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h61)
        lvt_97 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h62)
        lvt_98 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h62)
        lvt_98 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h63)
        lvt_99 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h63)
        lvt_99 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h64)
        lvt_100 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h64)
        lvt_100 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h65)
        lvt_101 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h65)
        lvt_101 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h66)
        lvt_102 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h66)
        lvt_102 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h67)
        lvt_103 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h67)
        lvt_103 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h68)
        lvt_104 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h68)
        lvt_104 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h69)
        lvt_105 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h69)
        lvt_105 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h6A)
        lvt_106 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h6A)
        lvt_106 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h6B)
        lvt_107 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h6B)
        lvt_107 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h6C)
        lvt_108 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h6C)
        lvt_108 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h6D)
        lvt_109 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h6D)
        lvt_109 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h6E)
        lvt_110 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h6E)
        lvt_110 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h6F)
        lvt_111 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h6F)
        lvt_111 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h70)
        lvt_112 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h70)
        lvt_112 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h71)
        lvt_113 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h71)
        lvt_113 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h72)
        lvt_114 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h72)
        lvt_114 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h73)
        lvt_115 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h73)
        lvt_115 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h74)
        lvt_116 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h74)
        lvt_116 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h75)
        lvt_117 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h75)
        lvt_117 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h76)
        lvt_118 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h76)
        lvt_118 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h77)
        lvt_119 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h77)
        lvt_119 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h78)
        lvt_120 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h78)
        lvt_120 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h79)
        lvt_121 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h79)
        lvt_121 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h7A)
        lvt_122 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h7A)
        lvt_122 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h7B)
        lvt_123 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h7B)
        lvt_123 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h7C)
        lvt_124 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h7C)
        lvt_124 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h7D)
        lvt_125 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h7D)
        lvt_125 <= _lvt_T_4;
      if (_GEN_0 & io_write_address2 == 7'h7E)
        lvt_126 <= _lvt_T_5;
      else if (w1 & io_write_address == 7'h7E)
        lvt_126 <= _lvt_T_4;
      if (_GEN_0 & (&io_write_address2))
        lvt_127 <= _lvt_T_5;
      else if (w1 & (&io_write_address))
        lvt_127 <= _lvt_T_4;
      sel_a <= _GEN[io_read_address_a];
      sel_b <= _GEN[io_read_address_b];
      a_x0 <= io_read_address_a[4:0] == 5'h0;
      b_x0 <= io_read_address_b[4:0] == 5'h0;
    end
  end // always @(posedge)
  bank_128x32 bank0_0_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank0_0_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank0_0_ext_R1_data),
    .W0_addr (io_write_address),
    .W0_en   (w1 & io_write_mask[0]),
    .W0_clk  (clock),
    .W0_data (io_in_0)
  );
  bank_128x32 bank0_1_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank0_1_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank0_1_ext_R1_data),
    .W0_addr (io_write_address),
    .W0_en   (w1 & io_write_mask[1]),
    .W0_clk  (clock),
    .W0_data (io_in_1)
  );
  bank_128x32 bank0_2_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank0_2_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank0_2_ext_R1_data),
    .W0_addr (io_write_address),
    .W0_en   (w1 & io_write_mask[2]),
    .W0_clk  (clock),
    .W0_data (io_in_2)
  );
  bank_128x32 bank0_3_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank0_3_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank0_3_ext_R1_data),
    .W0_addr (io_write_address),
    .W0_en   (w1 & io_write_mask[3]),
    .W0_clk  (clock),
    .W0_data (io_in_3)
  );
  bank_128x32 bank0_4_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank0_4_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank0_4_ext_R1_data),
    .W0_addr (io_write_address),
    .W0_en   (w1 & io_write_mask[4]),
    .W0_clk  (clock),
    .W0_data (io_in_4)
  );
  bank_128x32 bank0_5_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank0_5_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank0_5_ext_R1_data),
    .W0_addr (io_write_address),
    .W0_en   (w1 & io_write_mask[5]),
    .W0_clk  (clock),
    .W0_data (io_in_5)
  );
  bank_128x32 bank0_6_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank0_6_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank0_6_ext_R1_data),
    .W0_addr (io_write_address),
    .W0_en   (w1 & io_write_mask[6]),
    .W0_clk  (clock),
    .W0_data (io_in_6)
  );
  bank_128x32 bank0_7_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank0_7_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank0_7_ext_R1_data),
    .W0_addr (io_write_address),
    .W0_en   (w1 & io_write_mask[7]),
    .W0_clk  (clock),
    .W0_data (io_in_7)
  );
  bank_128x32 bank0_8_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank0_8_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank0_8_ext_R1_data),
    .W0_addr (io_write_address),
    .W0_en   (w1 & io_write_mask[8]),
    .W0_clk  (clock),
    .W0_data (io_in_8)
  );
  bank_128x32 bank0_9_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank0_9_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank0_9_ext_R1_data),
    .W0_addr (io_write_address),
    .W0_en   (w1 & io_write_mask[9]),
    .W0_clk  (clock),
    .W0_data (io_in_9)
  );
  bank_128x32 bank0_10_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank0_10_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank0_10_ext_R1_data),
    .W0_addr (io_write_address),
    .W0_en   (w1 & io_write_mask[10]),
    .W0_clk  (clock),
    .W0_data (io_in_10)
  );
  bank_128x32 bank0_11_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank0_11_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank0_11_ext_R1_data),
    .W0_addr (io_write_address),
    .W0_en   (w1 & io_write_mask[11]),
    .W0_clk  (clock),
    .W0_data (io_in_11)
  );
  bank_128x32 bank0_12_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank0_12_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank0_12_ext_R1_data),
    .W0_addr (io_write_address),
    .W0_en   (w1 & io_write_mask[12]),
    .W0_clk  (clock),
    .W0_data (io_in_12)
  );
  bank_128x32 bank0_13_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank0_13_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank0_13_ext_R1_data),
    .W0_addr (io_write_address),
    .W0_en   (w1 & io_write_mask[13]),
    .W0_clk  (clock),
    .W0_data (io_in_13)
  );
  bank_128x32 bank0_14_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank0_14_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank0_14_ext_R1_data),
    .W0_addr (io_write_address),
    .W0_en   (w1 & io_write_mask[14]),
    .W0_clk  (clock),
    .W0_data (io_in_14)
  );
  bank_128x32 bank0_15_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank0_15_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank0_15_ext_R1_data),
    .W0_addr (io_write_address),
    .W0_en   (w1 & io_write_mask[15]),
    .W0_clk  (clock),
    .W0_data (io_in_15)
  );
  bank_128x32 bank1_0_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank1_0_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank1_0_ext_R1_data),
    .W0_addr (io_write_address2),
    .W0_en   (w2 & mask2[0]),
    .W0_clk  (clock),
    .W0_data (io_in2_0)
  );
  bank_128x32 bank1_1_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank1_1_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank1_1_ext_R1_data),
    .W0_addr (io_write_address2),
    .W0_en   (w2 & mask2[1]),
    .W0_clk  (clock),
    .W0_data (io_in2_1)
  );
  bank_128x32 bank1_2_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank1_2_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank1_2_ext_R1_data),
    .W0_addr (io_write_address2),
    .W0_en   (w2 & mask2[2]),
    .W0_clk  (clock),
    .W0_data (io_in2_2)
  );
  bank_128x32 bank1_3_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank1_3_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank1_3_ext_R1_data),
    .W0_addr (io_write_address2),
    .W0_en   (w2 & mask2[3]),
    .W0_clk  (clock),
    .W0_data (io_in2_3)
  );
  bank_128x32 bank1_4_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank1_4_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank1_4_ext_R1_data),
    .W0_addr (io_write_address2),
    .W0_en   (w2 & mask2[4]),
    .W0_clk  (clock),
    .W0_data (io_in2_4)
  );
  bank_128x32 bank1_5_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank1_5_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank1_5_ext_R1_data),
    .W0_addr (io_write_address2),
    .W0_en   (w2 & mask2[5]),
    .W0_clk  (clock),
    .W0_data (io_in2_5)
  );
  bank_128x32 bank1_6_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank1_6_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank1_6_ext_R1_data),
    .W0_addr (io_write_address2),
    .W0_en   (w2 & mask2[6]),
    .W0_clk  (clock),
    .W0_data (io_in2_6)
  );
  bank_128x32 bank1_7_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank1_7_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank1_7_ext_R1_data),
    .W0_addr (io_write_address2),
    .W0_en   (w2 & mask2[7]),
    .W0_clk  (clock),
    .W0_data (io_in2_7)
  );
  bank_128x32 bank1_8_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank1_8_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank1_8_ext_R1_data),
    .W0_addr (io_write_address2),
    .W0_en   (w2 & mask2[8]),
    .W0_clk  (clock),
    .W0_data (io_in2_8)
  );
  bank_128x32 bank1_9_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank1_9_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank1_9_ext_R1_data),
    .W0_addr (io_write_address2),
    .W0_en   (w2 & mask2[9]),
    .W0_clk  (clock),
    .W0_data (io_in2_9)
  );
  bank_128x32 bank1_10_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank1_10_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank1_10_ext_R1_data),
    .W0_addr (io_write_address2),
    .W0_en   (w2 & mask2[10]),
    .W0_clk  (clock),
    .W0_data (io_in2_10)
  );
  bank_128x32 bank1_11_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank1_11_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank1_11_ext_R1_data),
    .W0_addr (io_write_address2),
    .W0_en   (w2 & mask2[11]),
    .W0_clk  (clock),
    .W0_data (io_in2_11)
  );
  bank_128x32 bank1_12_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank1_12_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank1_12_ext_R1_data),
    .W0_addr (io_write_address2),
    .W0_en   (w2 & mask2[12]),
    .W0_clk  (clock),
    .W0_data (io_in2_12)
  );
  bank_128x32 bank1_13_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank1_13_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank1_13_ext_R1_data),
    .W0_addr (io_write_address2),
    .W0_en   (w2 & mask2[13]),
    .W0_clk  (clock),
    .W0_data (io_in2_13)
  );
  bank_128x32 bank1_14_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank1_14_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank1_14_ext_R1_data),
    .W0_addr (io_write_address2),
    .W0_en   (w2 & mask2[14]),
    .W0_clk  (clock),
    .W0_data (io_in2_14)
  );
  bank_128x32 bank1_15_ext (
    .R0_addr (io_read_address_b),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_bank1_15_ext_R0_data),
    .R1_addr (io_read_address_a),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_bank1_15_ext_R1_data),
    .W0_addr (io_write_address2),
    .W0_en   (w2 & mask2[15]),
    .W0_clk  (clock),
    .W0_data (io_in2_15)
  );
  assign io_out_a_0 =
    a_x0 ? 32'h0 : sel_a[0] ? _bank1_0_ext_R1_data : _bank0_0_ext_R1_data;
  assign io_out_a_1 =
    a_x0 ? 32'h0 : sel_a[1] ? _bank1_1_ext_R1_data : _bank0_1_ext_R1_data;
  assign io_out_a_2 =
    a_x0 ? 32'h0 : sel_a[2] ? _bank1_2_ext_R1_data : _bank0_2_ext_R1_data;
  assign io_out_a_3 =
    a_x0 ? 32'h0 : sel_a[3] ? _bank1_3_ext_R1_data : _bank0_3_ext_R1_data;
  assign io_out_a_4 =
    a_x0 ? 32'h0 : sel_a[4] ? _bank1_4_ext_R1_data : _bank0_4_ext_R1_data;
  assign io_out_a_5 =
    a_x0 ? 32'h0 : sel_a[5] ? _bank1_5_ext_R1_data : _bank0_5_ext_R1_data;
  assign io_out_a_6 =
    a_x0 ? 32'h0 : sel_a[6] ? _bank1_6_ext_R1_data : _bank0_6_ext_R1_data;
  assign io_out_a_7 =
    a_x0 ? 32'h0 : sel_a[7] ? _bank1_7_ext_R1_data : _bank0_7_ext_R1_data;
  assign io_out_a_8 =
    a_x0 ? 32'h0 : sel_a[8] ? _bank1_8_ext_R1_data : _bank0_8_ext_R1_data;
  assign io_out_a_9 =
    a_x0 ? 32'h0 : sel_a[9] ? _bank1_9_ext_R1_data : _bank0_9_ext_R1_data;
  assign io_out_a_10 =
    a_x0 ? 32'h0 : sel_a[10] ? _bank1_10_ext_R1_data : _bank0_10_ext_R1_data;
  assign io_out_a_11 =
    a_x0 ? 32'h0 : sel_a[11] ? _bank1_11_ext_R1_data : _bank0_11_ext_R1_data;
  assign io_out_a_12 =
    a_x0 ? 32'h0 : sel_a[12] ? _bank1_12_ext_R1_data : _bank0_12_ext_R1_data;
  assign io_out_a_13 =
    a_x0 ? 32'h0 : sel_a[13] ? _bank1_13_ext_R1_data : _bank0_13_ext_R1_data;
  assign io_out_a_14 =
    a_x0 ? 32'h0 : sel_a[14] ? _bank1_14_ext_R1_data : _bank0_14_ext_R1_data;
  assign io_out_a_15 =
    a_x0 ? 32'h0 : sel_a[15] ? _bank1_15_ext_R1_data : _bank0_15_ext_R1_data;
  assign io_out_b_0 =
    b_x0 ? 32'h0 : sel_b[0] ? _bank1_0_ext_R0_data : _bank0_0_ext_R0_data;
  assign io_out_b_1 =
    b_x0 ? 32'h0 : sel_b[1] ? _bank1_1_ext_R0_data : _bank0_1_ext_R0_data;
  assign io_out_b_2 =
    b_x0 ? 32'h0 : sel_b[2] ? _bank1_2_ext_R0_data : _bank0_2_ext_R0_data;
  assign io_out_b_3 =
    b_x0 ? 32'h0 : sel_b[3] ? _bank1_3_ext_R0_data : _bank0_3_ext_R0_data;
  assign io_out_b_4 =
    b_x0 ? 32'h0 : sel_b[4] ? _bank1_4_ext_R0_data : _bank0_4_ext_R0_data;
  assign io_out_b_5 =
    b_x0 ? 32'h0 : sel_b[5] ? _bank1_5_ext_R0_data : _bank0_5_ext_R0_data;
  assign io_out_b_6 =
    b_x0 ? 32'h0 : sel_b[6] ? _bank1_6_ext_R0_data : _bank0_6_ext_R0_data;
  assign io_out_b_7 =
    b_x0 ? 32'h0 : sel_b[7] ? _bank1_7_ext_R0_data : _bank0_7_ext_R0_data;
  assign io_out_b_8 =
    b_x0 ? 32'h0 : sel_b[8] ? _bank1_8_ext_R0_data : _bank0_8_ext_R0_data;
  assign io_out_b_9 =
    b_x0 ? 32'h0 : sel_b[9] ? _bank1_9_ext_R0_data : _bank0_9_ext_R0_data;
  assign io_out_b_10 =
    b_x0 ? 32'h0 : sel_b[10] ? _bank1_10_ext_R0_data : _bank0_10_ext_R0_data;
  assign io_out_b_11 =
    b_x0 ? 32'h0 : sel_b[11] ? _bank1_11_ext_R0_data : _bank0_11_ext_R0_data;
  assign io_out_b_12 =
    b_x0 ? 32'h0 : sel_b[12] ? _bank1_12_ext_R0_data : _bank0_12_ext_R0_data;
  assign io_out_b_13 =
    b_x0 ? 32'h0 : sel_b[13] ? _bank1_13_ext_R0_data : _bank0_13_ext_R0_data;
  assign io_out_b_14 =
    b_x0 ? 32'h0 : sel_b[14] ? _bank1_14_ext_R0_data : _bank0_14_ext_R0_data;
  assign io_out_b_15 =
    b_x0 ? 32'h0 : sel_b[15] ? _bank1_15_ext_R0_data : _bank0_15_ext_R0_data;
endmodule

