// Generated by CIRCT firtool-1.128.0
module UartTxFifo(
  input        clock,
               reset,
  output       io_in_ready,
  input        io_in_valid,
  input  [7:0] io_in_bits,
  output       io_out
);

  wire       _uartTx_io_ready;
  wire       _fifo_q_io_deq_valid;
  wire [7:0] _fifo_q_io_deq_bits;
  Queue2048_UInt8 fifo_q (
    .clock        (clock),
    .reset        (reset),
    .io_enq_ready (io_in_ready),
    .io_enq_valid (io_in_valid),
    .io_enq_bits  (io_in_bits),
    .io_deq_ready (_uartTx_io_ready),
    .io_deq_valid (_fifo_q_io_deq_valid),
    .io_deq_bits  (_fifo_q_io_deq_bits)
  );
  UartTx uartTx (
    .clock    (clock),
    .reset    (reset),
    .io_data  (_fifo_q_io_deq_bits),
    .io_valid (_fifo_q_io_deq_valid),
    .io_ready (_uartTx_io_ready),
    .io_txd   (io_out)
  );
endmodule

