// Generated by CIRCT firtool-1.128.0
module VGAController(
  input         clock,
                reset,
  input  [31:0] io_address,
  input         io_write,
  input  [11:0] io_write_value,
  input         io_read_clk,
  output        io_hsync,
                io_vsync,
  output [11:0] io_rgb,
  output        io_blanking
);

  wire [11:0] _memory_ext_R0_data;
  reg  [9:0]  hCount;
  reg  [9:0]  vCount;
  wire        active = hCount < 10'h280 & vCount < 10'h1E0;
  wire [9:0]  vCountShifted = (active ? vCount : vCount + 10'h1) / 10'h2;
  wire [16:0] _vCountMult_T_2 = {vCountShifted[8:0], 8'h0} + {1'h0, vCountShifted, 6'h0};
  always @(posedge io_read_clk) begin
    if (reset) begin
      hCount <= 10'h0;
      vCount <= 10'h0;
    end
    else begin
      automatic logic _GEN = hCount == 10'h31F;
      hCount <= _GEN ? 10'h0 : hCount + 10'h1;
      if (_GEN)
        vCount <= vCount == 10'h20C ? 10'h0 : vCount + 10'h1;
    end
  end // always @(posedge)
  memory_76800x12 memory_ext (
    .R0_addr
      (active ? _vCountMult_T_2 + {7'h0, hCount / 10'h2} + 17'h1 : _vCountMult_T_2),
    .R0_en   (1'h1),
    .R0_clk  (io_read_clk),
    .R0_data (_memory_ext_R0_data),
    .W0_addr (io_address[18:2]),
    .W0_en   (io_write),
    .W0_clk  (clock),
    .W0_data (io_write_value)
  );
  assign io_hsync = ~(hCount > 10'h28F & hCount < 10'h2F0);
  assign io_vsync = ~(vCount > 10'h1E9 & vCount < 10'h1EC);
  assign io_rgb = active ? _memory_ext_R0_data : 12'h0;
  assign io_blanking = ~active;
endmodule

