// Generated by CIRCT firtool-1.128.0

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_
module WarpScheduler(
  input         clock,
                reset,
                io_execute,
  output [1:0]  io_active_warp,
  output [31:0] io_warp_ids_out_0,
                io_warp_ids_out_1,
                io_warp_ids_out_2,
                io_warp_ids_out_3,
  input         io_warp_swap,
                io_warp_terminate,
  output        io_warp_swap_flush,
                io_allocate_warp,
  output [1:0]  io_allocate_id,
  output [31:0] io_allocate_pc,
  output        io_complete,
  input         io_spawn,
  input  [31:0] io_spawn_count,
                io_spawn_pc_in,
  input         io_barrier,
  input  [31:0] io_barrier_target,
  input         io_lsu_busy
);

  reg  [1:0]  active_warp;
  reg  [31:0] warp_ids_0;
  reg  [31:0] warp_ids_1;
  reg  [31:0] warp_ids_2;
  reg  [31:0] warp_ids_3;
  reg         active_warps_0;
  reg         active_warps_1;
  reg         active_warps_2;
  reg         active_warps_3;
  reg  [31:0] warp_count;
  reg  [31:0] next_warp;
  reg  [31:0] spawn_pc;
  reg         barrier_waiting_0;
  reg         barrier_waiting_1;
  reg         barrier_waiting_2;
  reg         barrier_waiting_3;
  reg  [2:0]  barrier_count;
  reg  [31:0] barrier_target;
  wire        _GEN = next_warp < warp_count;
  wire [2:0]  free = ~{active_warps_2, active_warps_1, active_warps_0};
  wire [1:0]  _slot_T_5 = free[1] ? 2'h1 : {1'h1, ~(free[2])};
  wire        _GEN_0 =
    _GEN & {active_warps_3, active_warps_2, active_warps_1, active_warps_0} != 4'hF;
  wire        _GEN_1 = io_execute & _GEN_0;
  wire        _GEN_2 =
    io_warp_swap
    & ((|({active_warps_3, active_warps_2, active_warps_1, active_warps_0}
          & ~{barrier_waiting_3, barrier_waiting_2, barrier_waiting_1, barrier_waiting_0}
          & ~(4'h1 << active_warp))) | io_warp_terminate | io_barrier);
  `ifndef SYNTHESIS
    always @(posedge clock) begin
      if ((`PRINTF_COND_) & io_execute & _GEN_2 & io_warp_terminate & ~reset)
        $fwrite(32'h80000002, "Warp terminated!\n");
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire [3:0]  _GEN_3 =
    {{active_warps_3}, {active_warps_2}, {active_warps_1}, {active_warps_0}};
  wire [3:0]  _GEN_4 =
    {{barrier_waiting_3}, {barrier_waiting_2}, {barrier_waiting_1}, {barrier_waiting_0}};
  wire        _GEN_5 = ~_GEN_3[active_warp] | _GEN_4[active_warp];
  always @(posedge clock) begin
    if (reset) begin
      active_warp <= 2'h0;
      warp_ids_0 <= 32'h0;
      warp_ids_1 <= 32'h0;
      warp_ids_2 <= 32'h0;
      warp_ids_3 <= 32'h0;
      active_warps_0 <= 1'h1;
      active_warps_1 <= 1'h0;
      active_warps_2 <= 1'h0;
      active_warps_3 <= 1'h0;
      warp_count <= 32'h1;
      next_warp <= 32'h1;
      spawn_pc <= 32'h0;
      barrier_waiting_0 <= 1'h0;
      barrier_waiting_1 <= 1'h0;
      barrier_waiting_2 <= 1'h0;
      barrier_waiting_3 <= 1'h0;
      barrier_count <= 3'h0;
      barrier_target <= 32'h0;
    end
    else begin
      automatic logic [1:0] slot = free[0] ? 2'h0 : _slot_T_5;
      automatic logic       _GEN_6;
      automatic logic       _GEN_7;
      automatic logic       _GEN_8;
      automatic logic       _GEN_9;
      _GEN_6 = _GEN_0 & slot == 2'h0;
      _GEN_7 = _GEN_0 & slot == 2'h1;
      _GEN_8 = _GEN_0 & slot == 2'h2;
      _GEN_9 = _GEN_0 & (&slot);
      if (io_execute) begin
        automatic logic _GEN_10 =
          {29'h0, barrier_count + {2'h0, io_barrier}} >= barrier_target
          & (|barrier_target) & ~io_lsu_busy;
        automatic logic _GEN_11 = active_warp == 2'h0;
        automatic logic _GEN_12 = active_warp == 2'h1;
        automatic logic _GEN_13 = active_warp == 2'h2;
        if (_GEN_5)
          active_warp <= active_warp + 2'h1;
        else if (_GEN_2)
          active_warp <= active_warp + 2'h1;
        active_warps_0 <=
          ~(_GEN_2 & io_warp_terminate & _GEN_11) & (_GEN_6 | active_warps_0);
        active_warps_1 <=
          ~(_GEN_2 & io_warp_terminate & _GEN_12) & (_GEN_7 | active_warps_1);
        active_warps_2 <=
          ~(_GEN_2 & io_warp_terminate & _GEN_13) & (_GEN_8 | active_warps_2);
        active_warps_3 <=
          ~(_GEN_2 & io_warp_terminate & (&active_warp)) & (_GEN_9 | active_warps_3);
        barrier_waiting_0 <=
          ~_GEN_10 & (io_barrier & _GEN_11 | ~_GEN_6 & barrier_waiting_0);
        barrier_waiting_1 <=
          ~_GEN_10 & (io_barrier & _GEN_12 | ~_GEN_7 & barrier_waiting_1);
        barrier_waiting_2 <=
          ~_GEN_10 & (io_barrier & _GEN_13 | ~_GEN_8 & barrier_waiting_2);
        barrier_waiting_3 <=
          ~_GEN_10 & (io_barrier & (&active_warp) | ~_GEN_9 & barrier_waiting_3);
        if (_GEN_10) begin
          barrier_count <= 3'h0;
          barrier_target <= 32'h0;
        end
        else if (io_barrier) begin
          barrier_count <= barrier_count + 3'h1;
          barrier_target <= io_barrier_target;
        end
      end
      if (io_execute & _GEN_6)
        warp_ids_0 <= next_warp;
      if (io_execute & _GEN_7)
        warp_ids_1 <= next_warp;
      if (io_execute & _GEN_8)
        warp_ids_2 <= next_warp;
      if (io_execute & _GEN_9)
        warp_ids_3 <= next_warp;
      if (io_spawn) begin
        warp_count <= io_spawn_count;
        spawn_pc <= io_spawn_pc_in;
      end
      if (_GEN_1)
        next_warp <= next_warp + 32'h1;
    end
  end // always @(posedge)
  assign io_active_warp = active_warp;
  assign io_warp_ids_out_0 = warp_ids_0;
  assign io_warp_ids_out_1 = warp_ids_1;
  assign io_warp_ids_out_2 = warp_ids_2;
  assign io_warp_ids_out_3 = warp_ids_3;
  assign io_warp_swap_flush = io_execute & (_GEN_5 | _GEN_2);
  assign io_allocate_warp = io_execute & _GEN & _GEN_0;
  assign io_allocate_id = ~_GEN_1 | free[0] ? 2'h0 : _slot_T_5;
  assign io_allocate_pc = _GEN_1 ? spawn_pc : 32'h0;
  assign io_complete =
    next_warp == warp_count & ~active_warps_0 & ~active_warps_1 & ~active_warps_2
    & ~active_warps_3;
endmodule

